### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by zhulinyv** [CMHopeSunshine/LittlePaimon#101]
大佬，我想问一个挺弱的问题，怎么更新哇，呜呜呜＞﹏＜

**Comment by linword** [comment]
1.按照readme文档迁移用户数据文件目录
2.在LittlePaimon插件目录下使用`git pull`命令更新
3.如果之前是下载的压缩包，而不是使用`git clone`命令下载的，建议下载压缩包解压替换。

**Comment by zhulinyv** [comment]
> 

谢谢大佬，已经更新好了，原来是因为我在上一级目录打开了git bash导致找不到仓库＞﹏＜
