### ISSUE TITLE
关于cookie和更新角色信息的一些问题

### ISSUE THREAD

**Issue by wangyousama** [CMHopeSunshine/LittlePaimon#102]
![W4MH JSO74@YX8{~{%0X)JK](https://user-images.githubusercontent.com/107395159/178001477-767bfd26-bf07-4cc0-843b-f6b06742286c.png)
这个是私聊上传了私人COOKIE的
![2BZ)CM`0}N~O@06H5M8S3N1](https://user-images.githubusercontent.com/107395159/178001542-3ffdd13c-13e5-467c-a802-406733c6cc77.png)
这个是群聊的，之前没绑私人cookie也是一样的回复
但是我刚刚绑定了两个公共cookie，也没有提醒失效

![MZABPC4}4_V~3QW~$M4B999](https://user-images.githubusercontent.com/107395159/178001782-3d7ab437-c584-41e3-8029-0514f581bb2f.png)
这个是更新角色信息的回复，目前只有这一个人出现这个问题，其他人均正常、
![J1L@ZUHVWVBD9JVZWW F21F](https://user-images.githubusercontent.com/107395159/178001845-c5fadd48-28a2-45ec-89a7-3081f9cda0db.png)
这个是上面cqhttp的内容

**Comment by wangyousama** [comment]
第二张图片错
![KK81WKD5F@8HU9GDI0V60A8](https://user-images.githubusercontent.com/107395159/178002929-f5b0357b-abe6-49f3-b747-2c6215a1b250.png)
了

**Comment by CMHopeSunshine** [comment]
cookie获取之后不能退出登录，退出就会失效，登录状态过久也可能失效，要重新登录再获取；
如果很肯定私人cookie是有效的，检查一下查询的uid和绑定的私人cookie的uid是不是一致；
更新角色信息bug是enka接口的问题，一般是展示的角色中装备了3星的圣遗物导致的，我这边没法解决，顶多做一个异常处理

**Comment by wangyousama** [comment]
> cookie之后也不能退出，退出获取效力，登录状态过久可能失效，要重新登录重新获取； 如果很确定自己的cookie是有效的，请查看一下自定义的uid和绑定的cookie的uid是不是一致的； 更新处理角色信息的bug是enka接口的问题，一般是展示的角色中装备了3颗星的遗物导致的，我现在无法解决，顶多做一个
ok
