### ISSUE TITLE
公共ck录不进去

### ISSUE THREAD

**Issue by WNCX** [CMHopeSunshine/LittlePaimon#104]
![image](https://user-images.githubusercontent.com/70813274/178097463-6608a3e8-1db7-488a-9684-45e0cf7c96df.png)

会出现上面的情况，但相同的cookie作为私人ck是可以正常使用的。我把所有open和close的issue看过并实践了，也找不到解决方法

**Comment by WNCX** [comment]
刚刚看了一下，是 ys了用来当公共cookie的uid会出现这种情况，其他uid不会出现这种问题，请问这是什么机制呢

**Comment by CMHopeSunshine** [comment]
每个cookie每天只能查询别人的uid30次，这是米游社的限制，你可以试试app登这个cookie的号去查别人战绩看看是不是这个情况

**Comment by WNCX** [comment]
> 每个cookie每天只能查询别人的uid30次，这是米游社的限制，你可以试试app登这个cookie的号去查别人战绩看看是不是这个情况

是这个问题，已经了解怎么回事了，谢谢解答
