### ISSUE TITLE
guess_voice_api error

### ISSUE THREAD

**Issue by DA21S321D** [CMHopeSunshine/LittlePaimon#105]
![image](https://user-images.githubusercontent.com/56549016/178098391-7f894364-4f7c-4052-93d3-dfcace9fd0bf.png)
如图，求解

**Comment by DA21S321D** [comment]
我的确下载了很长时间的语音资源

**Comment by DA21S321D** [comment]
我确定自己已经下载语音资源，“请参考go-cqhttp端的输出”不知道怎么理解

**Comment by DA21S321D** [comment]
![image](https://user-images.githubusercontent.com/56549016/178098714-0d9317b5-d474-4f38-ae7e-f2788010f9d0.png)
ke
可能是这个吧，求助

**Comment by DA21S321D** [comment]
![image](https://user-images.githubusercontent.com/56549016/178098759-884cd440-0248-49de-8e41-ab29f901b8ec.png)
我尽可能多贴一些报错吧

**Comment by DA21S321D** [comment]
难道是缺少ffmpeg吗

**Comment by CMHopeSunshine** [comment]
是，安装ffmpeg

**Comment by DA21S321D** [comment]
哦，谢谢教程有写，我大意了
![image](https://user-images.githubusercontent.com/56549016/178098955-39b309e2-a076-4dd6-952d-2636279f2523.png)
感谢
