### ISSUE TITLE
只是想让派蒙在单独几个群里运行

### ISSUE THREAD

**Issue by WNCX** [CMHopeSunshine/LittlePaimon#108]
bot在安装派蒙之前就已经为十几个不同的群服务了，现在安装派蒙之后出现了在非原神群欢迎旅行者的现象，因为群的变动速度很快（包括频繁进退不同的群），所以不断修改屏蔽名单显然有点不现实。请问有没有白名单能让派蒙在指定的群运行而其他群都屏蔽

**Comment by CMHopeSunshine** [comment]
目前没有，可以用插件管理器将入群欢迎禁用，或者直接修改源代码禁用

**Comment by WNCX** [comment]
> 目前没有，可以用插件管理器将入群欢迎禁用，或者直接修改源代码禁用

想问问具体的操作步骤，之前用的不是nonebot2对这方面不太熟悉

**Comment by CMHopeSunshine** [comment]
将`Paimon_Plugins`里的`auto_handle.py`文件最前面加个_，这个文件是入群欢迎和好友请求相关的

**Comment by WNCX** [comment]
> 将`Paimon_Plugins`里的`auto_handle.py`文件最前面加个_，这个文件是入群欢迎和好友请求相关的

可以了，没有再欢迎了，不知道以后有没有做白名单的打算呢
