### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by zhulinyv** [CMHopeSunshine/LittlePaimon#109]
大佬，请问这样算是成功配置MongoDB了嘛
![image](https://user-images.githubusercontent.com/66541860/178136296-422cd191-5854-4c64-9cdf-413758baafb5.png)
我按照注释更改了env配置文件，但是只能看到关键词触发语音回复在工作。

**Comment by CMHopeSunshine** [comment]
是成功了，发言需要一定的信息量

**Comment by zhulinyv** [comment]
> 是成功了，发言需要一定的信息量

好的了解了，感谢解答！
