### ISSUE TITLE
关于添加ck和删除ck的问题

### ISSUE THREAD

**Issue by HuYo-OS** [CMHopeSunshine/LittlePaimon#11]
在我使用删除ck和添加ck命令的时候无任何反应，排查之后我发现了以下问题
![image](https://user-images.githubusercontent.com/94115384/162784127-b152ad84-75c5-4438-9c02-fb92369a75d5.png)
![image](https://user-images.githubusercontent.com/94115384/162784244-0b99bc0f-0063-4def-9f49-ede5d31b57df.png)
看起来似乎没有导入函数

**Comment by CMHopeSunshine** [comment]
对，疏忽了...明天补上
