### ISSUE TITLE
角色宵宫和神里绫华伤害计算问题

### ISSUE THREAD

**Issue by Noctulus** [CMHopeSunshine/LittlePaimon#110]
由Bot生成的宵宫伤害如下：
![QQ图片20220711105514](https://user-images.githubusercontent.com/39023047/178180773-f63629f6-4951-4932-affd-7a1a39b6fd6a.jpg)
理论计算结果与Bot生成结果差别很大
![QQ图片20220711105509](https://user-images.githubusercontent.com/39023047/178180829-7a4d1def-679e-45d3-b18e-d09ad4c5f497.png)
实际测试，在未叠天赋一的情况下宵宫普攻一段为6211，考虑天赋一，则结果与理论计算相符而与Bot计算不符；
![屏幕截图(1864) (大)](https://user-images.githubusercontent.com/39023047/178181080-aaf735a3-3b91-4a2e-be68-5416fa8eb358.png)
神里绫华同样存在Bot生成结果与实际结果差别很大的问题：
![QQ图片20220711105536](https://user-images.githubusercontent.com/39023047/178181169-a4a22d2f-e3b5-473f-b828-2b93d74e6bfd.jpg)
![屏幕截图(1865) (大)](https://user-images.githubusercontent.com/39023047/178181284-23c3c96c-bd50-4ab5-86a6-f5c62b254f4b.png)

**Comment by CMHopeSunshine** [comment]
已修正

**Comment by Noctulus** [comment]
虽然但是，绫华Q的伤害计算依然有问题（

**Comment by Noctulus** [comment]
似乎是神里绫华Q的等级没有被正确识别？因为按计算器算出来1级Q和2级Q的伤害就符合修复前后的数据了

**Comment by Noctulus** [comment]
![QQ图片20220711154542](https://user-images.githubusercontent.com/39023047/178214273-fd0ac33c-9417-433f-870a-10c53bdbb86f.png)
一个猜测：神里绫华因为多了一个神里流·霰步的天赋，所以Q可能是天赋3而非天赋1？

**Comment by CMHopeSunshine** [comment]
啊对，多一个技能的问题

**Comment by Noctulus** [comment]
OK，可以了
