### ISSUE TITLE
是否有办法管理MongoDB数据库中带有@的信息

### ISSUE THREAD

**Issue by zhulinyv** [CMHopeSunshine/LittlePaimon#113]
机器人学了几句带有**@**的信息，其它插件指令会误触，导致某人每次都会被艾特，所以有没有办法在不删库的情况下轻松管理数据库中带有@的信息，**困难请忽略**，打扰作者了

**Comment by CMHopeSunshine** [comment]
使用数据库管理工具（比如mongodb compass和navicat)，进mongodb里查询删除

**Comment by CMHopeSunshine** [comment]
使用数据库管理工具，进mongodb里查询删除

**Comment by CMHopeSunshine** [comment]
使用数据库管理工具，进mongodb里查询删除

**Comment by zhulinyv** [comment]
> 使用数据库管理工具（比如mongodb compass和navicat)，进mongodb里查询删除

谢谢大佬指点，第一次用数据库，什么都不会望多包涵😓
