### ISSUE TITLE
请问能否一个QQ绑定两个账号信息

### ISSUE THREAD

**Issue by mawMOBai** [CMHopeSunshine/LittlePaimon#114]
请问能否一个QQ绑定两个账号信息，以及绑定两个cookie。并且简化查询命令，如 更新角色信息 账号1，这个样子。

**Comment by CMHopeSunshine** [comment]
涉及cookie的功能是都可以绑多个cookie，查询时写明要查的uid就行。另外`更新角色信息`和`ysd`功能不需要cookie
