### ISSUE TITLE
已安装成功米游社，如何和机器人交互？发送myb无反应

### ISSUE THREAD

**Issue by XRRXRRXRRXRR** [CMHopeSunshine/LittlePaimon#118]
已安装成功米游社，如何和机器人交互？发送myb无反应，发送初始指令 /echo有回复

**Comment by CMHopeSunshine** [comment]
仅限私聊使用

**Comment by XRRXRRXRRXRR** [comment]
已解决




荷包蛋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CMHopeSunshine/LittlePaimon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月20日(星期三) 凌晨2:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CMHopeSunshine/LittlePaimon] 已安装成功米游社，如何和机器人交互？发送myb无反应 (Issue #118)





 
Closed #118 as completed.
