### ISSUE TITLE
启动成功后访问本地http://127.0.0.1:13579/go-cqhttp/报错404

### ISSUE THREAD

**Issue by xuhao-excellent** [CMHopeSunshine/LittlePaimon#120]
请问这是怎么回事，是缺少了什么文件吗
![image](https://user-images.githubusercontent.com/68591858/179456134-b910d85b-55cd-4692-adf5-66debc11a345.png)
![image](https://user-images.githubusercontent.com/68591858/179456157-72d89367-01b5-4570-9a9c-9bdce7517645.png)

**Comment by CMHopeSunshine** [comment]
插件`nonebot-plugin-gocqhttp`没有安装，运行`nb plugin install nonebot-plugin-gocqhttp`

**Comment by xuhao-excellent** [comment]
好的，谢谢，我试一下

**Comment by xuhao-excellent** [comment]
你好，请问有qq交流群吗

**Comment by CMHopeSunshine** [comment]
没有群，可以来qq频道交流
