### ISSUE TITLE
resources文件下载失败

### ISSUE THREAD

**Issue by zmy15** [CMHopeSunshine/LittlePaimon#122]
下载的文件大小都是153字节,无法正常打开

**Comment by FBIOpentheDoor26** [comment]
我也一样!
![image](https://user-images.githubusercontent.com/59684700/179545788-5b28ee29-c413-495d-95a1-71835b6a68aa.png)
![image](https://user-images.githubusercontent.com/59684700/179545948-055105fa-a469-4b69-b7e3-49c22900007c.png)

**Comment by FBIOpentheDoor26** [comment]
不过作者发布了resource的release,可以手动放到resource目录?

**Comment by CMHopeSunshine** [comment]
现在再试试？之前域名调错了

**Comment by FBIOpentheDoor26** [comment]
可以了

**Comment by zmy15** [comment]
可以了
