### ISSUE TITLE
未配置mongodb连接url

### ISSUE THREAD

**Issue by nimeng1299** [CMHopeSunshine/LittlePaimon#123]
显示派蒙机器学习启用失败，未配置mongodb连接url
本地mongodb服务启动了，本地27017端口显示：It looks like you are trying to access MongoDB over HTTP on the native driver port.
应该是正常的，哪里出了问题？

**Comment by CMHopeSunshine** [comment]
是否已在`.env.prod`文件中配置了`paimon_mongodb_url`

**Comment by nimeng1299** [comment]
> 是否已在文件中配置了`.env.prod``paimon_mongodb_url`
大大
我现在在文件里添加了paimon_mongodb_url=localhost:27017，
现在提示 可能是mongodb连接失败或缺少相关库（jieba_fast,pymongo,pypinyin）
我把pymongo和pypinyin安装了，jieba_fast不管用pip还是.tar.gz包安装都报错，就用jieba代替了
是链接填错了还是一定要jieba_fast这个包？

**Comment by CMHopeSunshine** [comment]
一定要这个包，如果是windows的话，要安装c++生成工具，具体可以搜索引擎搜一下

**Comment by nimeng1299** [comment]
> 一定要这个包，如果是windows的话，要安装c++生成工具，具体可以搜索引擎搜一下
我看网上都是要安装vs，但因为是服务器没有这么大的空间，如果改用linux是不是就没有这个问题？

**Comment by CMHopeSunshine** [comment]
是的

**Comment by nimeng1299** [comment]
> 
大佬
我现在pip list 能显示安装了jieba_fast,pymongo,pypinyin这三个包
配置文件写了paimon_mongodb_url = None
为什么还是提示可能是mongodb连接失败或缺少相关库（jieba_fast,pymongo,pypinyin）

**Comment by nimeng1299** [comment]
> 是的

大佬
我现在pip list 能显示安装了jieba_fast,pymongo,pypinyin这三个包
配置文件写了paimon_mongodb_url = None
为什么还是提示可能是mongodb连接失败或缺少相关库（jieba_fast,pymongo,pypinyin）

**Comment by CMHopeSunshine** [comment]
确认一下安装的环境对了没有，有种可能是没装在虚拟环境里

**Comment by nimeng1299** [comment]
> 确认一下安装的环境对了没有，有种可能是没装在虚拟环境里

应该是装了的，cmd标题栏写着 - poetry shell - nb run

**Comment by CMHopeSunshine** [comment]
那怪了，再确认一下？`pip show jieba_fast pymongo pypinyin`

**Comment by nimeng1299** [comment]
> 那怪了，再确认一下？`pip show jieba_fast pymongo pypinyin`

都有，版本分别为0.53 4.1.1 0.46.0

**Comment by ALEXsun0** [comment]
发生同样问题（

**Comment by ALEXsun0** [comment]
好吧我解决了，根据作者说的把包在虚拟环境安装

**Comment by nimeng1299** [comment]
> 好吧我解决了，根据作者说的把包在虚拟环境安装

 应该是的，如果在外面安装的话在虚拟环境使用pip list是不会有这三个包的
要在虚拟环境里再装一次
