### ISSUE TITLE
派蒙缺少daily_note\透明圆.png资源，请联系开发者补充

### ISSUE THREAD

**Issue by GuiltyKirito** [CMHopeSunshine/LittlePaimon#126]
执行 `ssbq` 提示一下

> 派蒙缺少daily_note\透明圆.png资源，请联系开发者补充

**Comment by CMHopeSunshine** [comment]
资源会在启动时自动下载的，重启一下吧

**Comment by GuiltyKirito** [comment]
> 资源会在启动时自动下载的，重启一下吧

我git pull了最新代码，执行 nb run 的时候提示了如图所示的错误

![image](https://user-images.githubusercontent.com/13746290/179749874-790e9168-87aa-46f7-9680-8888a8f38872.png)

**Comment by GuiltyKirito** [comment]
> 资源会在启动时自动下载的，重启一下吧

宝儿宝儿99我，我杀掉之前的进程，执行nb run 的时候 检查LittlePaimon资源文件 似乎没能下下来，我是不是搞砸了~

**Comment by CMHopeSunshine** [comment]
按照readme迁移一下资源吧

**Comment by GuiltyKirito** [comment]
> 按照readme迁移一下资源吧

亲爱的，爱你，重装OK了~

**Comment by qjsrsxy** [comment]
> 

我遇到了相同的错误，但是我应该已经完成了迁移。gocqhttp根目录下resources/LittlePaimon和/data/LittlePaimon/user_data 两个文件夹都在。启动时依然下载错误

**Comment by GuiltyKirito** [comment]
> > 
> 
> 我遇到了相同的错误，但是我应该已经完成了迁移。gocqhttp根目录下resources/LittlePaimon和/data/LittlePaimon/user_data 两个文件夹都在。启动时依然下载错误

我的做法挺极端的，直接把 resources里的Littxxx和根目录的Littxxx都删了 重新clone 重新 run 就全好了 YYDS

**Comment by CMHopeSunshine** [comment]
> > 
> 
> 我遇到了相同的错误，但是我应该已经完成了迁移。gocqhttp根目录下resources/LittlePaimon和/data/LittlePaimon/user_data 两个文件夹都在。启动时依然下载错误

迁移之后原文件删除了就没报错了，这个报错是windows系统特有的python3.8的bug

**Comment by qjksxy** [comment]
> 

centos8.5也有

**Comment by CMHopeSunshine** [comment]
> 

那你们应该不是同一个报错，有截图吗
