### ISSUE TITLE
后台可以收到信息但没有回复，WARNINGProtocol -> device lock is disable. http api may fail.

### ISSUE THREAD

**Issue by supersuperstar** [CMHopeSunshine/LittlePaimon#127]
WARNINGProtocol -> device lock is disable. http api may fail.

**Comment by CMHopeSunshine** [comment]
> WARNINGProtocol -> device lock is disable. http api may fail.

和这个报错没有关系，如果没有其他报错的话，那就是插件没有被加载，原因可能有：
1、没有在`bot.py`中加载插件
2、LittlePaimon存放目录和声明的加载目录不一致

**Comment by supersuperstar** [comment]
发现问题所在了。
我是按照 不熟悉NoneBot->手动部署 方式一步一步来的，中间也没有出错。
但是在启动的时候报错
`ModuleNotFoundError: No module named 'littlepaimon_utils'`
我在执行
`pip install -r requirements.txt`
这一步以后再启动就不报错了。
手动方式里好像没有提及这一步。。

**Comment by nicklly** [comment]
`ARNINGProtocol -> device lock is disable. http api may fail` 请左转GoCQhttp提交issue
