### ISSUE TITLE
深渊满星好像是36星

### ISSUE THREAD

**Issue by FBIOpentheDoor26** [CMHopeSunshine/LittlePaimon#128]
![3e12569b284493be](https://user-images.githubusercontent.com/59684700/180005262-7837bcd8-ada5-451c-948d-9b5aee77fac4.jpg)
这个是不是显示错了呀，为啥有5个9星

**Comment by CMHopeSunshine** [comment]
1-8层的打了也算的

**Comment by FBIOpentheDoor26** [comment]
啥意思，没看懂

**Comment by CMHopeSunshine** [comment]
就是你这次的深渊把1-8层的打了，也算进去，比如你在7-1试了下核爆，那这里就显示3-9-9-9-9

**Comment by FBIOpentheDoor26** [comment]
噢噢，明白了，谢谢
