### ISSUE TITLE
[建议]：关于推送消息

### ISSUE THREAD

**Issue by LittleMio** [CMHopeSunshine/LittlePaimon#129]
就是，定时自动签到和定时自动获取米游币使用的人多了之后，会唰的一下发出很长的推送消息（而且容易被风控），可否采用转发形式发出或者是简化签到、获取的状态信息

**Comment by CMHopeSunshine** [comment]
计划在重构版本中修改为以图片形式发出

**Comment by LittleMio** [comment]
好的，辛苦了~
