### ISSUE TITLE
参考面板功能风系角色结果错乱

### ISSUE THREAD

**Issue by Noctulus** [CMHopeSunshine/LittlePaimon#130]
如图，问A答B（
是不是因为加了小鹿没有重新适配
![581d71cfb2bf379d](https://user-images.githubusercontent.com/39023047/180118340-7729ef1d-f3a5-4c41-89df-591b27c8469d.png)

**Comment by CMHopeSunshine** [comment]
已经适配了，把nb目录/resources/LittlePaimon/blue文件夹删除，让它重新下载就可以了
