### ISSUE TITLE
ssbq uid 关闭提醒不可用

### ISSUE THREAD

**Issue by GuiltyKirito** [CMHopeSunshine/LittlePaimon#136]
ssbq 开启提醒后，无法触发关闭提醒

**Comment by CMHopeSunshine** [comment]
`ssbq关闭提醒`，无响应吗，还是说有响应但是已经继续提醒

**Comment by GuiltyKirito** [comment]
> `ssbq关闭提醒`，无响应吗，还是说有响应但是已经继续提醒

执行  `ssbq关闭提醒` 提示 ：关闭提醒成功， 依旧有提醒
