### ISSUE TITLE
图片发送问题

### ISSUE THREAD

**Issue by BZBY** [CMHopeSunshine/LittlePaimon#140]
点餐的 没有响应 我用的 点餐派蒙
今日早报也没反应

命令：
来点银发图
来点兽耳图
来点原神图
WARNING警告: 群 xxxxxxx 图片上传失败: image type error: text/html; charset=utf-8
WARNING群消息发送失败: 消息为空.

 [ERROR] nonebot | Running matcher <Matcher from LittlePaimon.Paimon_Plugins.random_img, type=message, priority=13, temp=False> failed.
Traceback (most recent call last):
  File "C:\cpp\LittlePaimon-Bot\bot.py", line 37, in <module>
    nonebot.run(app="__mp_main__:app")

nonebot.adapters.onebot.exception.ActionFailed: <ActionFailed data=None, echo=69, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>

不知道啥问题，用的集成包。
手动部署的 报错：
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 22: invalid start byte
不知道是不是因为我用了 win自带的 文本编辑器。。。。
如果是的 话我再重新搭一下

**Comment by CMHopeSunshine** [comment]
集成包版本太老了，这几个接口的api都已经失效了，下面的'utf-8'报错确实是编码原因

**Comment by BZBY** [comment]
> 

版本太老，所以是得用采用手动部署的方案安装吗？

**Comment by BZBY** [comment]
> 

版本太老，所以是得用采用手动部署的方案安装吗？
