### ISSUE TITLE
bug, suggestion, question 

### ISSUE THREAD

**Issue by FBIOpentheDoor26** [CMHopeSunshine/LittlePaimon#141]
![-46c41b5d4d657696](https://user-images.githubusercontent.com/59684700/181042641-61e84935-12ff-441b-9b22-749425c7ecfe.jpg)
bug，获取五星后会重置四星数量
Suggestion 
抽卡记录部分
1. 在图片上显示抽卡链接获取到的第一次和最后一次的抽卡时间
2. 添加各个四星物品获取的总数模块
提醒部分
1. 增加参量质变仪和其他部分的提醒
2. 机器人进入免打扰模式之前一段时间，检查在免打扰时间段是否有人的树脂达到阈值，若是，则提前提醒
3. 个人觉得可以优化一下ssbq的参量质变仪和每日委托的进度条样式或者逻辑。其他的模块，进度条都是满了代表要上线，而这两个正好反过来了
![-317ef6e891e04ece](https://user-images.githubusercontent.com/59684700/181046752-2bc0a5cf-fe8f-451d-af74-21d217dfbc8f.png)

question 超过6个月以后的抽卡记录，链接里没有，怎么能将本地的抽卡记录合并？

谢谢

**Comment by CMHopeSunshine** [comment]
感谢建议！
要合并抽卡记录的话，旧抽卡记录的文件格式要和本项目获取的格式一模一样才行，放到相应数据目录下，之后获取抽卡记录时会合并写入到这个文件，格式具体可以看[这个仓库](https://github.com/sunfkny/genshin-gacha-export)，本项目的抽卡记录是参考~~抄~~这个的
