### ISSUE TITLE
[BUG]更新角色信息功能，2开头的UID会错误识别为B服

### ISSUE THREAD

**Issue by qjksxy** [CMHopeSunshine/LittlePaimon#142]
如图。
![图片](https://user-images.githubusercontent.com/81305669/181068078-939b0125-8881-4713-9b06-d4c47cadbf4a.png)
复现概率：100%
最近更新时间：7.22

**Comment by qjksxy** [comment]
这个bug存在很长时间了，原谅我没升级到最新版本，最近更新日志中没有提及此事，所以认为此bug依旧没有解决

**Comment by CMHopeSunshine** [comment]
enka接口无法获取这个uid的信息，误判为b服了

**Comment by CMHopeSunshine** [comment]
因为之前enka是2和5开头的uid用不了，查询时会返回空数据，就做了这个提示，后来支持2开头的了，但是我一直忘了改提示。
