### ISSUE TITLE
派蒙聊天功能可能会把其他群聊中的消息发送出来

### ISSUE THREAD

**Issue by qjksxy** [CMHopeSunshine/LittlePaimon#146]
能不能修改为每个群聊分别进行学习？目测是将所有的群作为一整个语料库去学习，发送消息时不对群进行区分

**Comment by CMHopeSunshine** [comment]
不是吧，现在就是每个群聊单独学习的，多个群聊都有相同发言时，才会将这句作为全局发言。应该是阈值调太低了才导致区分度不够

**Comment by qjksxy** [comment]
我观察到的现象是，在A群会主动发出B群的消息，所以有这个疑问，不过阈值确实不高

**Comment by CMHopeSunshine** [comment]
```
# N个群有相同的回复，就跨群作为全局回复
paimon_cross_group_threshold = 2
```
这个是跨群阈值，默认是2

**Comment by qjksxy** [comment]
没有修改过这个阈值。我只修改过两个：主动发言阈值和派蒙聊天学习阈值，都由3改为2。引起我注意的消息只在一个群里出现过一次（因为只有俩群，一个讨论原神，一个不讨论），机器人会**主动**把原神群的消息发到非原神群里，也把非原神群里的消息发到了原神群里。这个现象不明显，机器人运行10天左右只观测到了两次（可能发生过更多次）。这个现象是正常的吗

**Comment by CMHopeSunshine** [comment]
可能是随机触发了喝醉...喝醉了会自己降低阈值，一会后恢复

**Comment by qjksxy** [comment]
OK，我去看看
