### ISSUE TITLE
静态资源下载问题

### ISSUE THREAD

**Issue by naotoseri** [CMHopeSunshine/LittlePaimon#151]
最近一次更新之后自动下载下来的静态资源文件均是100多b的损坏文件，无法正常使用
![image](https://user-images.githubusercontent.com/110286630/181906462-2c8533fd-b56f-4672-a844-c504d01c0ed7.png)
![image](https://user-images.githubusercontent.com/110286630/181906474-a0898714-49ae-4f73-ac09-6c6c2db24cc7.png)

**Comment by CMHopeSunshine** [comment]
确认是否能正常访问外部网络，开了代理之类的会导致无法访问而下载了404页面资源，这个小鹿的资源链接是`http://genshin.cherishmoon.fun/res/gacha_res/鹿野院平藏.png`

**Comment by naotoseri** [comment]
> 确认是否能正常访问外部网络，开了代理之类的会导致无法访问而下载了404页面资源，这个小鹿的资源链接是`http://genshin.cherishmoon.fun/res/gacha_res/鹿野院平藏.png`

没挂代理，链接打不开，报错是{"error":"not such file"}

**Comment by CMHopeSunshine** [comment]
> > 确认是否能正常访问外部网络，开了代理之类的会导致无法访问而下载了404页面资源，这个小鹿的资源链接是`http://genshin.cherishmoon.fun/res/gacha_res/鹿野院平藏.png`
> 
> 没挂代理，链接打不开，报错是{"error":"not such file"}

打漏了，是`http://genshin.cherishmoon.fun/res/gacha_res/角色/鹿野院平藏.png`

**Comment by naotoseri** [comment]
> > > 确认是否能正常访问外部网络，开了代理之类的会导致无法访问而下载了404页面资源，这个小鹿的资源链接是`http://genshin.cherishmoon.fun/res/gacha_res/鹿野院平藏.png`
> > 
> > 
> > 没挂代理，链接打不开，报错是{"error":"not such file"}
> 
> 打漏了，是`http://genshin.cherishmoon.fun/res/gacha_res/角色/鹿野院平藏.png`

已解决，谢谢
