### ISSUE TITLE
更新日志

### ISSUE THREAD

**Issue by contradiction123** [CMHopeSunshine/LittlePaimon#152]
大佬 能不能加一个  发送机器人更新日志的功能 比如 管理员账号给机器人账号 发送指令 发送更新日志 给制定账号（群聊）或者全部发送

**Comment by CMHopeSunshine** [comment]
敬请期待全新重构版本

**Comment by forchannot** [comment]
> 敬请期待全新重构版本

又要重构😂，这工作量真大，辛苦了
