### ISSUE TITLE
需要怎么去守护这个进程 关掉后 依旧可以运行

### ISSUE THREAD

**Issue by Jinyihua** [CMHopeSunshine/LittlePaimon#157]
谢谢 我不太懂这个 求解答一下 就是退出终端后 机器人可以继续运行 现在我是关掉终端 机器人就关掉了 网页也打不开

**Comment by CMHopeSunshine** [comment]
nohup、screen、pm2、supervisor等等工具，具体用法自行搜索

**Comment by SCUOP** [comment]
nohup nb run &输出日志后台运行
nohup >/dev/null 2>&1 &不输出日志后台运行(Linux下)

**Comment by Jinyihua** [comment]
> 所有者

好的谢谢

**Comment by Jinyihua** [comment]
> nohup nb run &输出日志后台运行 nohup >/dev/null 2>&1 &不输出日志后台运行(Linux下)

好的谢谢
