### ISSUE TITLE
使用云原神解绑报错，无法解绑

### ISSUE THREAD

**Issue by xrzxrzx** [CMHopeSunshine/LittlePaimon#160]
在Paimon_CloudGenshin的__init__.py的第62行，我调试了一下，发现data的值为{}，往上追溯到加载json文件的那一行里的Path()函数，这个函数获取的值是 . ，我用了everything也没有找到这个相应的json文件。
```python
data = load_json(Path() / 'data' / 'LittlePaimon' / 'CloudGenshin.json')#出错未知，第60行，直接print(Path)为.，json文件找不到
print(Path())
print(data)
try:
     del data[user_id]
except Exception as e:
     print(e)
```

**Comment by CMHopeSunshine** [comment]
绑定过了吗，有绑定记录才会有这个文件，文件在`nonebot目录/data/LittlePaimon/CloudGenshin.json`

**Comment by xrzxrzx** [comment]
绑定过了，其他需要绑定的功能都能用
JSON文件找到了，但里面就一对大括号

**Comment by nicklly** [comment]
大概知道什么问题了 或许明天会修复（咕）

**Comment by nicklly** [comment]
已经修复 #164
