### ISSUE TITLE
米游社更新，接口寄了，签到，米币获取功能不能使用

### ISSUE THREAD

**Issue by Sailious** [CMHopeSunshine/LittlePaimon#161]

**Comment by CMHopeSunshine** [comment]
请更新至最新代码

**Comment by 64luo** [comment]
> 请更新至最新代码

为什么我下载了最新的代码并且替换文件还是签到不了

**Comment by CMHopeSunshine** [comment]
确认替换完整并重启了吗，我们今天凌晨的签到都没问题，可以签到成功

**Comment by 64luo** [comment]
> 确认替换完整并重启了吗，我们今天凌晨的签到都没问题，可以签到成功

雀实是替换完成了，我是电脑上直接网站下载的，并且替换完了之后gocq和派蒙都重启过了

**Comment by 64luo** [comment]
他提示的是签到成功但是签到物品还是昨天的甜甜花酿鸡

**Comment by 64luo** [comment]
只有一个号签到的物品是今天的经验书

**Comment by Sailious** [comment]
> 请更新至最新代码

是的，昨天我确认更新到了最新代码并重新获取了cookie和stoken，但是米游币的获取仍然无法使用

**Comment by 64luo** [comment]
我的签到功能也还是没用

**Comment by 64luo** [comment]
我甚至还找了其他更新成功了的人要了他们的资源包替换，但还是老样子签到用不了
