### ISSUE TITLE
指令 ysa   派蒙报错

### ISSUE THREAD

**Issue by inoring** [CMHopeSunshine/LittlePaimon#163]
派蒙缺少role_card\10000059.png资源，请联系开发者补充

**Comment by CMHopeSunshine** [comment]
更新至最新代码并重启bot

**Comment by nicklly** [comment]
无意义issue就别发了 先更新了再说

**Comment by inoring** [comment]
> 更新至最新代码并重启bot

好了   之前用的gitee那边的代码

**Comment by inoring** [comment]
> 无意义issue就别发了 先更新了再说

没注意到gitee那边没更新
