### ISSUE TITLE
NoneBot2成功运行可在web端发送消息没有被风控

### ISSUE THREAD

**Issue by motian16** [CMHopeSunshine/LittlePaimon#165]
但是小派蒙的任何指令都无响应
我感觉py3.9没装好 但又不知道如何解决
日志很长 有20mb 只能放蓝奏云了[https://motian.lanzouw.com/iRTNJ094ybcb](url)
[root@VM-24-9-centos ~]# python -V
Python 2.7.5

[root@VM-24-9-centos ~]# python3 --version
Python 3.9.10

**Comment by CMHopeSunshine** [comment]
nonebot2升级至beta4以上，以下版本不适配

**Comment by motian16** [comment]
我用这个教程里的脚手架安装的，也不是最新版吗
![Uploading Screenshot_2022-08-07-13-29-30-00.jpg…]()

**Comment by CMHopeSunshine** [comment]
可能是安装的是旧版的脚手架，升级nonebot版本`pip install nonebot2 --upgrade`
