### ISSUE TITLE
获取抽卡记录不返回图片

### ISSUE THREAD

**Issue by FBIOpentheDoor26** [CMHopeSunshine/LittlePaimon#166]
![Screenshot_2022-08-07-22-43-50-76](https://user-images.githubusercontent.com/59684700/183296566-e3a6f6e2-a39d-40d8-95f1-e35d396c5cb0.jpg)
大佬这是怎么回事呀，不知道从什么时候不好使的，发现不好使之后用git pull 更新一下还是不好使。谢谢

**Comment by CMHopeSunshine** [comment]
确定是最新代码了吗，这个bug我的3天前修过了
