### ISSUE TITLE
发不了图，报错

### ISSUE THREAD

**Issue by nimeng1299** [CMHopeSunshine/LittlePaimon#168]
指令：来点二次元图.
报错内容
noebot.adapters.onebot.exception.ActionFailed: <ActionFailed data=None,echo=3, msg=SEND_MSG_API_ERROR,retcode=100,statys=failed,wording=请参考go-cqhttp 端输出>

报错之前成功发过一次，不过一会自己就撤回了。

**Comment by nimeng1299** [comment]
私聊是正常的，群聊就不行了

**Comment by nimeng1299** [comment]
私聊的会发出来，但是过几秒就撤回了。
群聊的直接发不出来报错

**Comment by CMHopeSunshine** [comment]
风控了吧，`请参考go-cqhttp 端输出`，看gocq日志

**Comment by nimeng1299** [comment]
在日志里，收到信息和发出信息都会显示4次，在cmd是正常的，
使用help等指令发的图是不会撤回的

**Comment by CMHopeSunshine** [comment]
基本上是风控，这个解决不了，随缘

**Comment by CMHopeSunshine** [comment]
撤回是正常的，因为不能保证随机图的涩涩程度，为了保护账号，就设了撤回

**Comment by nimeng1299** [comment]
这个情况只能等风控过了
