### ISSUE TITLE
个人部署出现问题

### ISSUE THREAD

**Issue by Amireon** [CMHopeSunshine/LittlePaimon#169]
大大，如图所示，
![image](https://user-images.githubusercontent.com/80996151/183675017-81968438-edc4-426c-b9a6-8678ec2abb5e.png)

![image](https://user-images.githubusercontent.com/80996151/183673318-f5cae7e6-3ccb-421f-8f80-d53cd3ec6969.png)
之后重复多次`poetry install`仍未解决问题，求解答

**Comment by Anlieh** [comment]
经过一番折腾，重装系统了....

**Comment by Amireon** [comment]
问题已解决，参见：
https://github.com/microsoft/playwright-python/issues/498
