### ISSUE TITLE
web 页面无法进入，求解

### ISSUE THREAD

**Issue by Amireon** [CMHopeSunshine/LittlePaimon#170]
![image](https://user-images.githubusercontent.com/80996151/183820634-15f546c9-7b0f-46d2-97ae-ccee0fcaad3a.png)

手动部署，bot已正常工作，云服务器端口以开放，防火墙已关闭，终端退出了

**Comment by CMHopeSunshine** [comment]
`nonebot-plugin-gocqhttp`装了吗，nb启动完的时候有没有提示`Web UI running on http:ip:端口`

**Comment by Amireon** [comment]
已装载，有提示，第一次`nb run`时能正常进入，但是重启bot后无法进入（bot目前正常运行）

**Comment by CMHopeSunshine** [comment]
你确定bot启动成功了，没被杀掉进程吧？没见过第一次行第二次不行的情况，关于这个插件的详细用法请看它的github仓库，实在不行就用独立的原版go-cqhttp

**Comment by Amireon** [comment]
离谱，真被杀掉了，我还特意检查了好几次进程，但是真的能用。再再次启动，现在可以了，感谢大佬

**Comment by Amireon** [comment]
danshi但是疑问又来了，请问这个进程是被怎样杀掉的
![image](https://user-images.githubusercontent.com/80996151/183824521-089341ae-2a87-412f-a18b-f8777608a6c6.png)

**Comment by CMHopeSunshine** [comment]
关闭终端就会杀掉当前前台进程，你需要借助进程守护工具让程序在后台运行，比如`nohup`、`screen`等

**Comment by Amireon** [comment]
明白了，再次感谢
