### ISSUE TITLE
绑定cookie后无法使用myzj

### ISSUE THREAD

**Issue by MotocoZg** [CMHopeSunshine/LittlePaimon#174]
只有sy是正常输出的，ysa和myzj都无法正确识别cookie
![image](https://user-images.githubusercontent.com/111079540/184195250-bae31848-1632-4d98-96ce-119c4c19ab9e.png)
![image](https://user-images.githubusercontent.com/111079540/184195267-365dc08e-7fac-47e7-9f1a-b3c9814954d8.png)

**Comment by CMHopeSunshine** [comment]
看日志，是否提示ck已失效

**Comment by MotocoZg** [comment]
> 看日志，是否提示ck已失效

我这边用无痕上他号重新生成了一个已绑定成功。不知道他哪里操作有误..
