### ISSUE TITLE
发癫全局生效

### ISSUE THREAD

**Issue by ALEXsun0** [CMHopeSunshine/LittlePaimon#175]
`@bot 发癫`后
在所有机器人在的群都话特别多
全局生效了

**Comment by CMHopeSunshine** [comment]
本来就是这样的啊，`发癫`将所有阈值调至最低

**Comment by ALEXsun0** [comment]
那能不能单群聊生效

**Comment by CMHopeSunshine** [comment]
这部分是由 @SCUOP 修改的，可以和他提个建议(bushi

**Comment by ALEXsun0** [comment]
自己回去找了下[https://github.com/MistEO/Pallas-Bot](url)，把发癫这个全局改变量的直接禁了，然后把喝酒（喝奶），睡觉之类的整合进去，又小小更新了一下，pallas-Bot那边有更新（改别人代码真的被变量名坑爆）算是自我解决了（
讲道理我是先用的牛牛后面才过来架的派蒙（
（改代码的时候看到模块里面都是`牛牛`真的很难顶

**Comment by ALEXsun0** [comment]
让 @SCUOP 更新一下？
隔壁优化的更新过来？（bushi
刚上github啥都不会（
