### ISSUE TITLE
不发癫的时候机器人还是会自己说话

### ISSUE THREAD

**Issue by coconutzzZ336** [CMHopeSunshine/LittlePaimon#176]
群里有另外一个机器人每天准点报时，然后这个机器人就会在没人说话的时候突然重复报时的内容，还会随机戳一戳一个人，用不准说指令也不行。我想在MongoDB compass里把这个数据删了，不过我用模糊搜索没找到这句话在哪

**Comment by ALEXsun0** [comment]
Paimon_Chat这个模块去参考[https://github.com/MistEO/Pallas-Bot](url)是有自主发言功能的
`# 主动说话加上随机戳一戳群友的概率
paimon_speak_poke_probability = 0.5`
把这个概率调成0就可以不戳了
回复不可以就可以删除（或者只是降低权重？）
`@机器人 不准说(内容)`应该是可以禁用的
内容左右两边的括号是半角：`（`与`(`的区分
