### ISSUE TITLE
poetry的一键启动问题

### ISSUE THREAD

**Issue by Cathgao** [CMHopeSunshine/LittlePaimon#177]
请问在windows环境中，手动使用poetry部署之后，如何使用批处理或py一键启动小派蒙？
目前只能手动开启cmd来分步输入命令启动，没法开机自启
谢谢！

**Comment by ljx-code** [comment]
> 请问在windows环境中，手动使用poetry部署之后，如何使用批处理或py一键启动小派蒙？ 目前只能手动开启cmd来分步输入命令启动，没法开机自启 谢谢！

Windows本来就不适合当服务器，真当服务器还得看Linux，去b站搜派蒙机器人能找到对应的教程的就写个.bat文件

**Comment by shoucandanghehe** [comment]
poetry run nb run
