### ISSUE TITLE
能不能删除图片的撤回功能

### ISSUE THREAD

**Issue by coconutzzZ336** [CMHopeSunshine/LittlePaimon#179]
我改了下图片的api，基本上不会被疼讯检测，能不能把那个撤回的功能给注释掉？

**Comment by CMHopeSunshine** [comment]
你可以自己注释掉

**Comment by coconutzzZ336** [comment]
> 你可以自己注释掉

我没找到在哪..
能不能指个方向？

**Comment by CMHopeSunshine** [comment]
`@auto_withdraw(秒数)`，搜索一下全部注释就行

**Comment by coconutzzZ336** [comment]
> `@auto_withdraw(秒数)`，搜索一下全部注释就行
谢谢了
