### ISSUE TITLE
cookie

### ISSUE THREAD

**Issue by zhangjy1318** [CMHopeSunshine/LittlePaimon#18]
为什么我公共ck添加成功了但是群里还是无法进行使用

**Comment by zhangjy1318** [comment]
![屏幕截图 2022-04-28 112811](https://user-images.githubusercontent.com/46964259/165670649-bb8f1e77-0956-4d81-8ec1-b6fa0c509c6e.png)
![屏幕截图 2022-04-28 112855](https://user-images.githubusercontent.com/46964259/165670650-822c5526-7548-4148-9b8d-256f8d7569bd.png)

**Comment by CMHopeSunshine** [comment]
提供一下后台日志

**Comment by zhangjy1318** [comment]
[error.log](https://github.com/CMHopeSunshine/LittlePaimon/files/8579355/error.log)

**Comment by zhangjy1318** [comment]
![Uploading image.png…]()

**Comment by zhangjy1318** [comment]
![屏幕截图 2022-04-28 125435](https://user-images.githubusercontent.com/46964259/165679196-93daf998-b8d9-4447-bc87-4c6fe8814567.png)
？

**Comment by CMHopeSunshine** [comment]
> ![屏幕截图 2022-04-28 125435](https://user-images.githubusercontent.com/46964259/165679196-93daf998-b8d9-4447-bc87-4c6fe8814567.png) ？

这个是开了代理导致的，关掉就行，而且我看日志，好像都是`ActionFailed`，账号风控发不出消息
