### ISSUE TITLE
更新角色信息失败

### ISSUE THREAD

**Issue by Chinzicam** [CMHopeSunshine/LittlePaimon#183]
**日志**未报错，已是最新版派蒙。
![image](https://user-images.githubusercontent.com/108013361/185520891-c073713c-e755-4341-855e-bcbfc3c2d82a.png)
派蒙好像出了点问题，get() got an unexpected keyword argument 'follow_redirects'

**Comment by Chinzicam** [comment]
这个问题通过查询聊天记录，是昨天（18号）出现的，17号还是正常的

**Comment by CMHopeSunshine** [comment]
我这里没有这个问题，httpx版本是多少？`pip show httpx`查看版本

**Comment by Chinzicam** [comment]
> 我这里没有这个问题，httpx版本是多少？`pip show httpx`查看版本

0.19.0

**Comment by CMHopeSunshine** [comment]
升到0.23.0，`pip install httpx --upgrade`

**Comment by Chinzicam** [comment]
> 升到0.23.0，`pip install httpx --upgrade`

ok了，感谢
