### ISSUE TITLE
米游社签到失败

### ISSUE THREAD

**Issue by Paosin** [CMHopeSunshine/LittlePaimon#185]
已更新nonebot2分支最新代码还是失败
1. 重新clone再install后启动
2. 重新获取cookie
发起签到后仅提示当日获取的物品，实际米游社查看未签到

**Comment by CMHopeSunshine** [comment]
看下后台日志，现在签到概率出验证码导致失败

**Comment by Paosin** [comment]
> 看下后台日志，现在签到概率出验证码导致失败

访问签到接口```/event/bbs_sign_reward/sign```
响应值：
```json
{
    "data": null,
    "message": "invalid request",
    "retcode": -10001
}
```
这好像不是验证码的问题
