### ISSUE TITLE
原神语音资源更新失败

### ISSUE THREAD

**Issue by Yql66** [CMHopeSunshine/LittlePaimon#188]
![QQ浏览器截图20220824172154](https://user-images.githubusercontent.com/111969738/186382114-b0a89c19-98bf-4288-8c19-49a6494b6732.png)

**Comment by CMHopeSunshine** [comment]
估计是出了新角色改了布局，有空再修

**Comment by nimeng1299** [comment]
> 估计是出了新角色改了布局，有空再修

我是一直出现 随机到了哑巴，重新随机，如果反复出现这个，请检查下数据库
`data\LittlePaimon\guess_voice\voice` 这里是有语音文件的
