### ISSUE TITLE
无法读取LittlePaimon配置文件

### ISSUE THREAD

**Issue by nimeng1299** [CMHopeSunshine/LittlePaimon#189]
启动时提示
[插件管理器]无法读取LittlePaimon配置文件，请检查目录。
但可以启动，请问这个怎么解决？

**Comment by CMHopeSunshine** [comment]
不用管，实际功能还没写，占坑用的(

**Comment by nimeng1299** [comment]
> 不用管，实际功能还没写，占坑用的(

啊这...那个欢迎群友和学群友说话的功能没了吗

**Comment by CMHopeSunshine** [comment]
还没完成重构，后续会加上
