### ISSUE TITLE
关于import和gocq的配置问题

### ISSUE THREAD

**Issue by coconutzzZ336** [CMHopeSunshine/LittlePaimon#190]
报错`Failed to import "LittlePaimon"`和`cannot inport name connections from tortoise`
使用`pip install LittlePaimon`和`pip install tortoise`发现所有的依赖都安装好了

gocqhttp使用反向WS配置`universal: ws://0.0.0.0:13579`
提示
uvicorn | <127.0.0.1,56039> - WebSocket /" 403
websockets | connection failed <403 Forbidden>
websockets | connection closed
网址127.0.0.1:13579打不开
大佬，有没有什么解决方法？

**Comment by CMHopeSunshine** [comment]
哪个分支版本啊，哪来的pip install LittlePaimon呢。。。
gocq的配置是`universal: ws://0.0.0.0:13579/onebot/v11/ws`

**Comment by coconutzzZ336** [comment]
> 
gocq那里已经好了
用的是bot分支的，
![image](https://user-images.githubusercontent.com/111185928/186462195-d256c23e-560e-4d10-9b3d-0f98df9d249d.png)

**Comment by CMHopeSunshine** [comment]
截全一点啊，有用的在最后几句

**Comment by coconutzzZ336** [comment]
> 截全一点啊，有用的在最后几句
屏幕只有这么长>_<
这是后半部分
![image](https://user-images.githubusercontent.com/111185928/186462911-1c8b8d7d-f780-4265-a893-c4f97a1fbb6f.png)

**Comment by CMHopeSunshine** [comment]
`poetry install`了没

**Comment by coconutzzZ336** [comment]
> `poetry install`了没

用了，我再用一次显示`No dependencies to install or update`

**Comment by CMHopeSunshine** [comment]
`poetry run pip install tortoise-orm==0.19.2`试试

**Comment by coconutzzZ336** [comment]
> 

显示一堆Requirement already,应该是安装好了的，再次启动还是报错这个

**Comment by CMHopeSunshine** [comment]
环境不是同一个吧，启动要用`poetry run nb run`

**Comment by coconutzzZ336** [comment]
> 环境不是同一个吧，启动要用`poetry run nb run`

我是先用`poetry shell`再安装依赖的，用`poetry run nb run`还是不行

**Comment by CMHopeSunshine** [comment]
一样的报错？`poetry run pip show tortoise-orm`看看这个库的版本

**Comment by CMHopeSunshine** [comment]
把tortoise卸载掉，`poetry run pip uninstall tortoise`

**Comment by coconutzzZ336** [comment]
> 把tortoise卸载掉，`poetry run pip uninstall tortoise`

版本是0.19.2，卸载后重新安装`poetry run pip install tortoise`还是出现这个

**Comment by CMHopeSunshine** [comment]
卸载了就不要安装，tortoise和tortoise-orm不是同一个东西，但是tortoise-orm用的包名也叫tortoise，这两个完全不一样，所以要把tortoise卸载掉，安装tortoise-orm

**Comment by coconutzzZ336** [comment]
> 卸载了就不要安装，tortoise和tortoise-orm不是同一个东西，但是tortoise-orm用的包名也叫tortoise，这两个完全不一样，所以要把tortoise卸载掉，安装tortoise-orm

这样的话报错就变成了 `connot import name Tortoise from tortoise <unknown location>`

**Comment by coconutzzZ336** [comment]
> 卸载了就不要安装，tortoise和tortoise-orm不是同一个东西，但是tortoise-orm用的包名也叫tortoise，这两个完全不一样，所以要把tortoise卸载掉，安装tortoise-orm

这样的话报错就变成了 `connot import name Tortoise from tortoise <unknown location>`

**Comment by CMHopeSunshine** [comment]
要不重新来过吧，我觉得这个虚拟环境已经乱了

**Comment by coconutzzZ336** [comment]
> 要不重新来过吧，我觉得这个虚拟环境已经乱了

好，我整个服务器重装过试试

**Comment by coconutzzZ336** [comment]
> 要不重新来过吧，我觉得这个虚拟环境已经乱了

真的可能是环境乱了，我重装就好了，不过柯莱和提纳里的语音获取失败，其他都能正常用了

**Comment by CMHopeSunshine** [comment]
米游社观测枢还没上线这两个角色的语音，上线之后再更新语音资源就可以了
