### ISSUE TITLE
ysd命令报错，无法绑定个人ck和公共ck

### ISSUE THREAD

**Issue by Mr233sir** [CMHopeSunshine/LittlePaimon#192]
![QQ图片20220825120002](https://user-images.githubusercontent.com/30330282/186572352-d08fe671-4e4a-4608-9aba-3e60958a22a4.png)
![QQ图片20220825120113](https://user-images.githubusercontent.com/30330282/186572357-86a731b7-a8bd-4a18-a700-a997680ef727.png)

**Comment by CMHopeSunshine** [comment]
cookie中要有cookie_token才有效，ysd的话今天已经修复好，更新重启即可

**Comment by Mr233sir** [comment]
cookie_token用文档的方法获取不了啊，里面没这行信息

**Comment by ljx-code** [comment]
> cookie_token用文档的方法获取不了啊，里面没这行信息

你的指令里怎么加了个cookie？不应该是ysb+[cookie链接]吗

**Comment by Mr233sir** [comment]
> > cookie_token用文档的方法获取不了啊，里面没这行信息
> 
> 你的指令里怎么加了个cookie？不应该是ysb+[cookie链接]吗

之前也试过不加这个的也绑不了

**Comment by CMHopeSunshine** [comment]
先去米游社登录，登完再去通行证登录，然后获取ck

**Comment by ljx-code** [comment]
1.登录米游社打开原神或米游社通行证界面使用无痕模式获取cookie
2.查看你的大号是否在.env.prod文件的SUPERMAN[]配置里
3.以上都确认了，去看项目日志
