### ISSUE TITLE
有没有考虑发布到nonebot 的插件商店

### ISSUE THREAD

**Issue by wayne0926** [CMHopeSunshine/LittlePaimon#193]
https://v2.nonebot.dev/store
不知道可不可行，如果能的话回方便管理很多

**Comment by CMHopeSunshine** [comment]
可能会发布机器人，但是插件的话，派蒙核心的功能耦合性都太高了，不太好解耦，挺难发布的。一些小的功能，比如米游币兑换啥的，已经有发布到商店中。
