### ISSUE TITLE
更新后启动显示账户密码错误

### ISSUE THREAD

**Issue by wayne0926** [CMHopeSunshine/LittlePaimon#194]
我在派蒙的目录下git pull后启动
显示账户密码错误（确认账户密码无误，并且尝试二维码登录也无果

**Comment by CMHopeSunshine** [comment]
账号问题和小派蒙无关，建议再仔细确认，你很肯定密码没错但就是登录不上的话，可以去go-cqhttp仓库发issue

**Comment by wayne0926** [comment]
好像是帐号不安全登录受限，就尼玛离了谱，号又没被封，就是远程登不起

**Comment by wayne0926** [comment]
> 账号问题和小派蒙无关，建议再仔细确认，你很肯定密码没错但就是登录不上的话，可以去go-cqhttp仓库发issue

不过我好像没更新成功？我这里还显示的是v1.0.0，也没有圣遗物图鉴啥的

**Comment by wayne0926** [comment]
解决了谢谢
