### ISSUE TITLE
请问这个怎么解决

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#196]
服务器上很多字加载不出来
![image](https://user-images.githubusercontent.com/100580891/186680283-4729700b-d932-4560-b2fb-517f5d345a60.png)
本地电脑上就没问题

**Comment by CMHopeSunshine** [comment]
换个终端主题

**Comment by forchannot** [comment]
> 换个终端主题

 ̶怎̶么̶弄̶啊̶，̶服̶务̶器̶网̶速̶太̶慢̶了̶有̶啥̶方̶便̶点̶的̶办̶法̶吗̶，̶而̶且̶只̶有̶p̶o̶w̶e̶r̶s̶h̶e̶l̶l̶5̶
换了个背景，有点丑，但勉强能看清了
