### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Zoe-Wh1t3zZ** [CMHopeSunshine/LittlePaimon#2]
手动改了user _cookies.json后用指令加cookie和配置公共cookie没反应

**Comment by CMHopeSunshine** [comment]
手动改了json文件要重启一下才能让机器人读取到，但是为何要又用指令加呢，指令加cookie的目的就是写入到json里，然后进行读取使用。

**Comment by Zoe-Wh1t3zZ** [comment]
谢谢谢谢！
