### ISSUE TITLE
已经修改webui地址为公网ip仍无法访问

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#202]
![image](https://user-images.githubusercontent.com/100580891/186891778-9cb78f28-bbde-403c-ad79-c6e8cc138003.png)
![image](https://user-images.githubusercontent.com/100580891/186891868-ef1735d5-978c-4723-bed3-9eb7cfaab87f.png)
服务器也放开了端口，还是访问不了怎么弄呢
![image](https://user-images.githubusercontent.com/100580891/186891808-5825358a-622f-492e-8981-9f388eb7f921.png)

**Comment by CMHopeSunshine** [comment]
还要将13579修改为你nonebot的端口

**Comment by forchannot** [comment]
> 还要将13579修改为你nonebot的端口

nonebot端口就是默认的13579
![image](https://user-images.githubusercontent.com/100580891/186892397-65782799-7293-4892-94a0-99e368a875c2.png)

**Comment by CMHopeSunshine** [comment]
服务器内的防火墙也要开放端口，可以用telnet命令查看确认是否已开放

**Comment by forchannot** [comment]
> 服务器内的防火墙也要开放端口，可以用telnet命令查看确认是否已开放

我把服务器内的防火墙也开放了出入规则，腾讯云控制台也开放了，还是无法解决怎么办呢

**Comment by CMHopeSunshine** [comment]
用`telnet 公网ip:13579`看下是否响应成功，启动时有没有提示`[原神Cookie]启用CookieWeb成功，地址xxxx`呢

**Comment by forchannot** [comment]
> 用`telnet 公网ip:13579`看下是否响应成功，启动时有没有提示`[原神Cookie]启用CookieWeb成功，地址xxxx`呢

启动时提示了启用成功，但是telnet无法连接

**Comment by forchannot** [comment]
我电脑本地启动用局域网ip地址手机就能访问，但是服务器就是不知道为啥不行😂

**Comment by forchannot** [comment]
用netstat -aon显示这个
![image](https://user-images.githubusercontent.com/100580891/186906320-2a6bb79c-070f-41b7-a21c-798d4f99e2b5.png)

**Comment by nimeng1299** [comment]
> 用netstat -aon显示这个 ![image](https://user-images.githubusercontent.com/100580891/186906320-2a6bb79c-070f-41b7-a21c-798d4f99e2b5.png)

我直接用默认的配置，开了端口就能用了

**Comment by forchannot** [comment]
> > 用netstat -aon显示这个 ![image](https://user-images.githubusercontent.com/100580891/186906320-2a6bb79c-070f-41b7-a21c-798d4f99e2b5.png)
> 
> 我直接用默认的配置，开了端口就能用了

我也都是默认配置也开了端口就是用不了

**Comment by nimeng1299** [comment]
> > > 用netstat -aon显示这个 ![image](https://user-images.githubusercontent.com/100580891/186906320-2a6bb79c-070f-41b7-a21c-798d4f99e2b5.png)
> > 
> > 
> > 我直接用默认的配置，开了端口就能用了
> 
> 我也都是默认配置也开了端口就是用不了

服务器上用`127.0.0.1:13579/LittlePaimon/cookie`能不能打开？不能的话就是你搞错了，可以的话用公网也能打开的

**Comment by forchannot** [comment]
> > > > 用netstat -aon显示这个 ![image](https://user-images.githubusercontent.com/100580891/186906320-2a6bb79c-070f-41b7-a21c-798d4f99e2b5.png)
> > > 
> > > 
> > > 我直接用默认的配置，开了端口就能用了
> > 
> > 
> > 我也都是默认配置也开了端口就是用不了
> 
> 服务器上用`127.0.0.1:13579/LittlePaimon/cookie`能不能打开？不能的话就是你搞错了，可以的话用公网也能打开的

能，本地可以打开，就是公网打不开

**Comment by nimeng1299** [comment]
那就是没开端口了，用的腾讯云吗，去管理面板把端口打开就行了

**Comment by forchannot** [comment]
> 那就是没开端口了，用的腾讯云吗，去管理面板把端口打开就行了

开了的

**Comment by ljx-code** [comment]
> > 那就是没开端口了，用的腾讯云吗，去管理面板把端口打开就行了
> 
> 开了的

我用的也是腾讯云 一切正常啊

**Comment by forchannot** [comment]
> > > 那就是没开端口了，用的腾讯云吗，去管理面板把端口打开就行了
> > 
> > 
> > 开了的
> 
> 我用的也是腾讯云 一切正常啊

我不知道为什么不正常，腾讯云那边反复确认安全组开了端口，服务器内的防火墙也开了端口，用telnet -a显示无法外部访问只能本地访问
