### ISSUE TITLE
连发help会导致服务器资源占用极大

### ISSUE THREAD

**Issue by wayne0926** [CMHopeSunshine/LittlePaimon#203]
我注意到好像每次`help`的指令都是实时生成的，会占用很大的内存以及CPU
建议可以做一个缓存，即在开启后第一次`help`被触发时缓存这个图片，后面按需发送
我这里是比较低端的机器，以至于基本上连着发送3~4（运气不好2~3）个`help`就直接`Killed`
![image](https://user-images.githubusercontent.com/63389859/186933918-2531feee-e5da-4b85-9137-579fca7edd60.png)

**Comment by CMHopeSunshine** [comment]
可以 ~~(要是连发ysa那不是更惨)~~

**Comment by CMHopeSunshine** [comment]
已经添加缓存
