### ISSUE TITLE
获取记录的请求和现版本的不适配，求大大优化一下

### ISSUE THREAD

**Issue by ljx-code** [CMHopeSunshine/LittlePaimon#209]
如题，3.0版本mhy修改了抽卡记录获取的方式（可能），求优化。学Java的我看python真的跟天书一样

**Comment by CMHopeSunshine** [comment]
在修了，现在就差新UI绘制，预计明天弄好

**Comment by ljx-code** [comment]
大大米游社签到呢？米游币可以获取成功，米游社签到死活不成功

**Comment by CMHopeSunshine** [comment]
签到没办法，mhy封死了，基本上现在所有相关签到项目都无法稳定签到成功，只能等mhy放宽 ~~（我觉得只会更严，米游币 危）~~

**Comment by ljx-code** [comment]
哦哦 谢谢大大指教

**Comment by ljx-code** [comment]
大大晚安 这条我关了啦
