### ISSUE TITLE
无法正常运行

### ISSUE THREAD

**Issue by awsl0293** [CMHopeSunshine/LittlePaimon#21]
[WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:6660/ws/ 时出现错误: dial tcp 127.0.0.1:6660: connectex: No connection could be made because the target machine actively refused it.
这是啥情况，求教

**Comment by CMHopeSunshine** [comment]
gocq启动了但hoshino没有启动就是这样的

**Comment by awsl0293** [comment]
该怎么解决呀，试了半天了，还是不行

**Comment by shi-g-c** [comment]
[WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:6660/ws/ 时出现错误: dial tcp 127.0.0.1:6660: connectex: No connection could be made because the target machine actively refused it.
我也遇到了这样的问题，请问该怎么解决呢？

**Comment by CMHopeSunshine** [comment]
问题就是hoshino没启动，只启动了gocq。你得看hoshino启动时遇到了什么问题。还有，别用一键脚本

**Comment by shi-g-c** [comment]
我刚刚用了一键安装，没有出现问题，已经扫码登录，但是现在那个powershell停留在“[2022-05-01 12:49:54] [INFO]: 网络诊断完成. 未发现问题”这一步，光标在下一行闪烁但是一直没有新的变化。这又是什么问题呢？

**Comment by CMHopeSunshine** [comment]
> 我刚刚用了一键安装，没有出现问题，已经扫码登录，但是现在那个powershell停留在“[2022-05-01 12:49:54] [INFO]: 网络诊断完成. 未发现问题”这一步，光标在下一行闪烁但是一直没有新的变化。这又是什么问题呢？

powershell快速编辑模式的问题，自己百度解决。
而且这个窗口只是gocq的窗口，还要hoshino的窗口，2个窗口才是正常运行，只有单一个gocq窗口就会出现上述连接问题

**Comment by shi-g-c** [comment]
我超，在windows上弄好了，谢谢大佬！不过我想问一下这个必须把电脑开着才能用吗？可以挂到服务器上吗？

**Comment by CMHopeSunshine** [comment]
> 我超，在windows上弄好了，谢谢大佬！不过我想问一下这个必须把电脑开着才能用吗？可以挂到服务器上吗？

本地电脑要一直开着，可以挂服务器上，操作是一样的
