### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by boli-zhazi** [CMHopeSunshine/LittlePaimon#210]
请问这个怎么解决，可以不换系统吗
![91CCD652-6489-49F0-93C3-A2F6D5FCCC3B](https://user-images.githubusercontent.com/65220310/187088829-525fe6d5-12c8-4311-80c8-20e4418c4e9f.jpeg)

**Comment by ljx-code** [comment]
手动安装一下chromium就行了我也遇到过这个问题，另外如果你使用的是默认分支的建议切换bot分支，默认分支已经不再支持须弥的更新，查询须弥角色会有bug

**Comment by ljx-code** [comment]
切换到虚拟环境poetry shell然后yum install chromium，如果你失败了在网上查一下你对应的系统怎么安装的
