### ISSUE TITLE
myb兑换不能记录上次的cookie和uid吗

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#212]
每次都要重新输入uid和cookie比较麻烦，还有就是在myb对话过程中能否随时取消该次操作

**Comment by forchannot** [comment]
> 每次都要重新输入uid和cookie比较麻烦，还有就是在myb对话过程中能否随时取消该次操作

大佬神速啊，才发完就改好了（

**Comment by CMHopeSunshine** [comment]
额额..米游社签到和米游币获取加了，但是米游币兑换没加，因为这个是插件形式，独立于bot

**Comment by forchannot** [comment]
> 额额..米游社签到和米游币获取加了，但是米游币兑换没加，因为这个是插件形式，独立于bot
😂😂😂
