### ISSUE TITLE
大大，“抽卡记录新UI，无法抽卡链接，通过Stoken更新”，这个已经变成了“绑定stoken后，发送链接才能获取抽卡记录”

### ISSUE THREAD

**Issue by ljx-code** [CMHopeSunshine/LittlePaimon#214]
如题

**Comment by ljx-code** [comment]
而且我通过绑定页面给群友绑定的stoken，然后获取抽卡记录，小派蒙还是提示去获取cookie

**Comment by CMHopeSunshine** [comment]
现在只要绑定了stoken，就可以直接获取抽卡记录了，因此也不再需要抽卡记录链接，也没做对链接的支持

**Comment by CMHopeSunshine** [comment]
在绑定stoken后，先使用`更新抽卡记录`指令，然后`查看抽卡记录`即可，第一次绘图会下载角色头像，会比较慢

**Comment by ljx-code** [comment]
> 在绑定stoken后，先使用`更新抽卡记录`指令，然后`查看抽卡记录`即可，第一次绘图会下载角色头像，会比较慢

哦哦 谢谢大大
