### ISSUE TITLE
stoken如何获取，会和cookie冲突吗

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#217]
还有就是自动同意好友请求的功能没有了吗
![image](https://user-images.githubusercontent.com/100580891/187657245-cf2332bb-9f6a-4a27-b270-09cb79c1a56a.png)

**Comment by CMHopeSunshine** [comment]
不会冲突，先在米游社登录，然后去通行证登录获取ck就行。这个功能正在移植

**Comment by forchannot** [comment]
> 不会冲突，先在米游社登录，然后去通行证登录获取ck就行。这个功能正在移植

也就是说两个网页同时打开并登录，然后在通行证页面正常获取ck就包含了stoken是吧

**Comment by CMHopeSunshine** [comment]
是的

**Comment by forchannot** [comment]
> 是的

请问下这个是bug还是正常，已经绑定了完整ck了，ysa所有角色都这样
![image](https://user-images.githubusercontent.com/100580891/187662435-fa0e73db-bc52-4810-8d68-abc1c598f66a.png)

**Comment by CMHopeSunshine** [comment]
`ys`、`ysa`和`ysc`指令都不再实时更新，需要先使用`更新角色信息`指令，如果要获取天赋等级，则使用`更新角色信息all`指令

**Comment by forchannot** [comment]
> 

好的
