### ISSUE TITLE
新分支 `bot`：米游社签到失败

### ISSUE THREAD

**Issue by Amireon** [CMHopeSunshine/LittlePaimon#221]
于两日前迁移到新版本，目前测试除此功能均正常
![image](https://user-images.githubusercontent.com/80996151/187898460-fb5fe4c9-f203-406d-99ce-09d5dbdfe980.png)

由于此功能使用的人数甚少(指算我三个 。。。)，三人两日均签到失败，不清楚是否具有普遍性

**Comment by CMHopeSunshine** [comment]
现在签到已被mhy封禁，相关项目都不能稳定签到成功
