### ISSUE TITLE
云原神签到功能缺失？

### ISSUE THREAD

**Issue by meatjam** [CMHopeSunshine/LittlePaimon#223]
我看Bot分支的LittlePaimon/plugins下并没有云原神相关模块，help指令生成的图片里也没有，但nonebot2分支是有的。
请问下这个模块现在是作为第三方插件需要自行加入了吗？

**Comment by CMHopeSunshine** [comment]
云原神稍后移植

**Comment by meatjam** [comment]
> 云原神稍后移植

好的，感谢
