### ISSUE TITLE
资源更新错误

### ISSUE THREAD

**Issue by SZhongS** [CMHopeSunshine/LittlePaimon#228]
使用ysd指令后后台能获取数据，但是无法制图。重下资源包也不能解决问题
![O8M35 A77VDE{Z2417}XIEI](https://user-images.githubusercontent.com/107989741/188263184-fd64a374-6875-4a4c-860a-dd32dbec4560.png)
![YLXM)GRQ@B5_BGV(RA5({%T](https://user-images.githubusercontent.com/107989741/188263185-67e25ed1-a4b7-4eb5-98ca-cad0e14a72e2.jpg)

**Comment by CMHopeSunshine** [comment]
是否开了代理，试下能否正常访问`https://enka.network/ui/Skill_E_Zhongli_01.png`

**Comment by SZhongS** [comment]
可以访问

**Comment by SZhongS** [comment]
出来是个大招的图

**Comment by CMHopeSunshine** [comment]
那说明只是偶现网络问题

**Comment by SZhongS** [comment]
没有啊，每次都是这样，很久了都用不了

**Comment by SZhongS** [comment]
我发现关闭了decsidecar之后上面的网站就无法访问了，可能是机器人没用到代理，请问怎么设置？

**Comment by CMHopeSunshine** [comment]
这个是外网网站，但正常来说不需要代理就能访问，是不是你的服务器进行了拦截，~~或者你的ip被它封禁了~~

**Comment by SZhongS** [comment]
我用的是校园网，不知道有什么问题

**Comment by CMHopeSunshine** [comment]
把这个api换成`https://file.minigg.icu/genshin/ui/`试试，小灰灰佬提供的镜像api
