### ISSUE TITLE
能否查看角色技能伤害

### ISSUE THREAD

**Issue by mengxinyizhui** [CMHopeSunshine/LittlePaimon#23]
这个能支持吗

**Comment by mengxinyizhui** [comment]
还想问下，如果我设置了自动开启签到，断开重新链接之后，还会自动签到吗

**Comment by CMHopeSunshine** [comment]
> 还想问下，如果我设置了自动开启签到，断开重新链接之后，还会自动签到吗

重新链接是指？？？
要程序一直在运行才行，linux的话可以用`nohup`命令让它后台运行。
计算技能伤害的话，得用户自己输入面板...再看看吧

**Comment by CMHopeSunshine** [comment]
预计6月末做伤害计算#40
