### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by dengma0** [CMHopeSunshine/LittlePaimon#231]
更新项目是重新pull代码来更新吗？

**Comment by zuixiaoxiao** [comment]
在这里打开Git Bash
![image](https://user-images.githubusercontent.com/108536651/188789092-68e77ef6-e303-4b58-ab62-eccd9315bce5.png)
输git pull
![image](https://user-images.githubusercontent.com/108536651/188789246-da814a59-eda7-4670-9eb6-6e895679d827.png)

**Comment by Chinzicam** [comment]
> 更新项目是重新pull代码来更新吗？
你更新到最新的话，之后的更新就可以直接指令更新了，很省事
![image](https://user-images.githubusercontent.com/108013361/188803105-18d0802c-7352-440f-8a55-371c2328527a.png)
