### ISSUE TITLE
派蒙好像出了点问题，'100557'

### ISSUE THREAD

**Issue by czh3141** [CMHopeSunshine/LittlePaimon#233]
这个是什么原因,之前还是好好的突然就这样了
还有这个派蒙好像出了点问题，'313300315'

**Comment by czh3141** [comment]
就一个人是这样..其他人是好的

**Comment by CMHopeSunshine** [comment]
能提供下日志吗

**Comment by czh3141** [comment]
> 能提供下日志吗

发完这个命令后nohup.out里是下面这些内容:
09-09 08:35:49 [SUCCESS] nonebot | ONEBOT V11 3090151646 | [message.private.friend]: Message 660424114 from 2477004584 "更新角色信息198544535"
09-09 08:35:49 [INFO] nonebot | Event will be handled by <Matcher from LittlePaimon.Paimon_Info, type=message, priority=6, temp=False>
09-09 08:35:49 [INFO] nonebot_plugin_gocqhttp | [3090151646] 发送好友 2477004584(2477004584)  的消息: [{"type":  ... (1416378453)
09-09 08:35:50 [INFO] nonebot_plugin_gocqhttp | [3090151646] 发送好友 2477004584(2477004584)  的消息: [{"type":  ... (-905400842)
09-09 08:35:50 [INFO] nonebot | Matcher <Matcher from LittlePaimon.Paimon_Info, type=message, priority=6, temp=False> running complete

**Comment by czh3141** [comment]
我之前用的还是nonebot2这个分支,,,现在我准备重新安装,用Bot这个,python不是很懂,有些命令按照文档上的会时不时出现,问题,可能是按网上这些方法解决这个问题的时候什么东西冲突导致的

**Comment by CMHopeSunshine** [comment]
日志看起来还是nonebot2分支的，不适配须弥角色了，有须弥角色会报错

**Comment by czh3141** [comment]
> 日志看起来还是nonebot2分支的，不适配须弥角色了，有须弥角色会报错

谢谢,现在已经改到bot分支了,目前没有问题
