### ISSUE TITLE
如何自动通过好友请求？

### ISSUE THREAD

**Issue by nimeng1299** [CMHopeSunshine/LittlePaimon#235]
我只知道nonebot分支是用`paimon_add_friend = true`
现在在bot分支用这个好像不管用了，还是要自己同意
难道要在paimon_greet.yml这里写吗

**Comment by CMHopeSunshine** [comment]
paimon_config.yml

**Comment by CMHopeSunshine** [comment]
也可以发命令`pm set 自动接受好友请求 on`
