### ISSUE TITLE
抽卡记录和UID不匹配

### ISSUE THREAD

**Issue by FBIOpentheDoor26** [CMHopeSunshine/LittlePaimon#236]
![image](https://user-images.githubusercontent.com/59684700/189287326-f8241325-c346-4d77-a397-bb11a799b072.png)

**Comment by CMHopeSunshine** [comment]
抽卡记录链接里面有个9位数数字被识别为了uid，而且当前版本没有做对抽卡记录链接的支持，仅支持通过stoken来获取抽卡记录

**Comment by FBIOpentheDoor26** [comment]
那stoken怎么获取呢)))

**Comment by CMHopeSunshine** [comment]
先在米游社登录，然后去米哈游通行证页面登录和获取cookie，这样cookie中就会有stoken相关字段。同样是`ysb`命令绑定

**Comment by FBIOpentheDoor26** [comment]
没有啊

**Comment by CMHopeSunshine** [comment]
有login_ticket字段就行，会自动通过login_ticket来获取stoken

**Comment by FBIOpentheDoor26** [comment]
好使了,谢谢
现在只需要用cookie就可以查看抽卡记录了吗?
 原来是用这种方式解决的吗 ... 太厉害了！

**Comment by CMHopeSunshine** [comment]
是的，绑定之后，只要cookie不过期，就可以一直获取抽卡记录

**Comment by FBIOpentheDoor26** [comment]
谢谢!
