### ISSUE TITLE
pyproject.toml 更新冲突问题

### ISSUE THREAD

**Issue by qjksxy** [CMHopeSunshine/LittlePaimon#240]
我添加了一些 Nonebot 插件，这些插件保存在了 `pyproject.toml` 文件中。现在更新时此文件会报冲突，请问是否有好的解决办法？
此文件仅修改了 `plugins = []` 一行

**Comment by forchannot** [comment]
> 我添加了一些 Nonebot 插件，这些插件保存在了 `pyproject.toml` 文件中。现在更新时此文件会报冲突，请问是否有好的解决办法？ 此文件仅修改了 `plugins = []` 一行

先git stash，然后git pull ，最后git stash pop
