### ISSUE TITLE
想问问现在的安装

### ISSUE THREAD

**Issue by fangyuanshisan** [CMHopeSunshine/LittlePaimon#241]
我是老版本升级上来的,按方法二.但是每次更新我都得重新挪动文件,我看现在支持给bot发送更新命令.我需要怎么全新安装一下

**Comment by zuixiaoxiao** [comment]
> 我是老版本升级上来的,按方法二.但是每次更新我都得重新挪动文件,我看现在支持给bot发送更新命令.我需要怎么全新安装一下
 
你下载要通过git bash(在你要装机器人的地方右键)下载小派蒙只是powershell或者cmd下载的没法正常更新（应该是反正我当时是没法更新）然后就通过方法1来移植

**Comment by CMHopeSunshine** [comment]
建议用方法一，重新部署一个，将原来的数据放到新bot中

**Comment by ljx-code** [comment]
老版本迁移新版本直接git clone，cd LittlePaimon ，poetry install，poetry shell，poetry run nb plugin install nonebot-plugin-gocqhttp,vim .end.prod, i , :wq, nohup nb run

**Comment by ljx-code** [comment]
跟我一样用的二，派蒙的更新指令调用的是git pull指令你当前分支和远程分支的根不一样当然拉不下来的，按照我上面的重新拉一下 使用mv xx /xx/xx/LittlePaimon迁移数据类的文件
