### ISSUE TITLE
可以用PyCharm调试这个项目吗

### ISSUE THREAD

**Issue by IceCapriccio** [CMHopeSunshine/LittlePaimon#242]
想问下项目的开发者，可以用PyCharm调试这个项目吗？
想给项目的学习聊天加一些功能，因为不熟悉NoneBot和作者自定义的一些类，所以如果能调试一下会更方便熟悉里面的一些对象。
如果可以的话求指导~

**Comment by IceCapriccio** [comment]
或者想问下作者在开发时是怎么调试的？

**Comment by CMHopeSunshine** [comment]
可以参考[nb论坛该问题](https://github.com/nonebot/discussions/discussions/164)

**Comment by IceCapriccio** [comment]
> 可以参考[nb论坛该问题](https://github.com/nonebot/discussions/discussions/164)

非常感谢！
