### ISSUE TITLE
安装完首次使用报错

### ISSUE THREAD

**Issue by mxyooR** [CMHopeSunshine/LittlePaimon#244]
![QQ截图20220911094254](https://user-images.githubusercontent.com/88259089/189508099-6075d1cc-9c0b-49c5-a331-55af2adbcabf.png)

**Comment by CMHopeSunshine** [comment]
这不是报错吧

**Comment by zuixiaoxiao** [comment]
> ![QQ截图20220911094254](https://user-images.githubusercontent.com/88259089/189508099-6075d1cc-9c0b-49c5-a331-55af2adbcabf.png)

你应该是有装“nonebot_plugin_docs”这个插件并且网页打开了
![image](https://user-images.githubusercontent.com/108536651/189574476-5184f801-f151-4e17-a0fc-77cf260588d6.png)
![image](https://user-images.githubusercontent.com/108536651/189574681-c01949be-51c6-4157-9e38-beac390cf2eb.png)
这个对吧，他不是报错只是你使用NoneBot的提示而已
