### ISSUE TITLE
emm，群友使用ys指令报错

### ISSUE THREAD

**Issue by zuixiaoxiao** [CMHopeSunshine/LittlePaimon#245]
Event will be handled by <Matcher from LittlePaimon.plugins.Paimon_Info, type=message, priority=10, temp=False>
09-11 15:29:34 [INFO] LittlePaimon | [原神信息查询]开始执行
09-11 15:29:34 [INFO] LittlePaimon | [原神信息查询]➤ 用户2135690544 UID188350087
09-11 15:29:34 [INFO] LittlePaimon | [原神信息查询]➤➤数据获取成功
09-11 15:29:34 [INFO] LittlePaimon | [原神信息查询]➤➤➤制图出错:'NoneType' object has no attribute 'level'

**Comment by CMHopeSunshine** [comment]
3.0更新后需要发一次`更新角色信息`命令

**Comment by zuixiaoxiao** [comment]
> 3.0更新后需要发一次`更新角色信息`命令

啊对，忘了他好像没更新，打扰了，谢谢作者解疑
