### ISSUE TITLE
tortoise.exceptions.CnofiguratioError

### ISSUE THREAD

**Issue by zhulinyv** [CMHopeSunshine/LittlePaimon#247]
我使用方法二配置好后，所有插件成功加载完毕出现如下报错：
![image](https://user-images.githubusercontent.com/66541860/189522110-be4a0ccf-f7ae-4562-9fea-1e58c02693bb.png)
实在是不清楚问题出在哪了，希望大佬解答QAQ

**Comment by CMHopeSunshine** [comment]
这是haruka_bot插件的报错，和派蒙无关

**Comment by zhulinyv** [comment]
> 这是haruka_bot插件的报错，和派蒙无关

删除haruka_bot之后问题解决，谢谢大佬o(〃＾▽＾〃)o
