### ISSUE TITLE
多个群同时发消息，群聊学习功能会报错，求大佬解答

### ISSUE THREAD

**Issue by hyysys** [CMHopeSunshine/LittlePaimon#248]
![CloudShell 和另外 1 个页面 - 个人 - Microsoft​ Edge 2022_9_11 21_55_15](https://user-images.githubusercontent.com/110589577/189531743-fb576cf4-9bac-4a75-b579-03e2673878f9.png)

**Comment by CMHopeSunshine** [comment]
群聊学习还在优化中，问题可能会比较多。这个问题暂时可以通过重启解决。

**Comment by hyysys** [comment]
> 群聊学习还在优化中，问题可能会比较多。这个问题暂时可以通过重启解决。

OK，感谢大佬
