### ISSUE TITLE
入群欢迎无法正常使用，聊天学习功能边报错边跑

### ISSUE THREAD

**Issue by zhulinyv** [CMHopeSunshine/LittlePaimon#250]
![image](https://user-images.githubusercontent.com/66541860/189571149-9a32c24f-f075-4b3e-91e9-6ff44b19c608.png)
新人进群欢迎报错。可以相应部分指令，比如 “入群欢迎启用全部”，但如果把 “全部” 换成 群号会出现如下报错：
![image](https://user-images.githubusercontent.com/66541860/189571314-9292c54e-b09f-4b5a-93c4-c9b712e73a31.png)
可能是我哪里弄错了，希望大佬解答，十分感谢！

聊天学习功能边报错边跑，KeyError 各不相同😭，我可以换回旧版本的Paimon_Chat嘛T_T.

**Comment by CMHopeSunshine** [comment]
问题已修。你要是想换成旧的也行，但是需要动手改一改。

**Comment by zhulinyv** [comment]
> 问题已修。你要是想换成旧的也行，但是需要动手改一改。

谢谢大佬，可以点拨一下怎么改嘛，，直接把插件和utils搬过去可以嘛？

**Comment by zhulinyv** [comment]
> 问题已修。你要是想换成旧的也行，但是需要动手改一改。

入群欢迎启用+群号 不会报错了，但是可怜的群员被我踢了十几次没有一次被欢迎。😂

**Comment by zhulinyv** [comment]
> > 问题已修。你要是想换成旧的也行，但是需要动手改一改。
> 
> 入群欢迎启用+群号 不会报错了，但是可怜的群员被我踢了十几次没有一次被欢迎。😂

![image](https://user-images.githubusercontent.com/66541860/189584147-8819f2b5-e046-443d-9e09-76afba995a40.png)

**Comment by CMHopeSunshine** [comment]
> > > 问题已修。你要是想换成旧的也行，但是需要动手改一改。
> > 
> > 
> > 入群欢迎启用+群号 不会报错了，但是可怜的群员被我踢了十几次没有一次被欢迎。😂
> 
> ![image](https://user-images.githubusercontent.com/66541860/189584147-8819f2b5-e046-443d-9e09-76afba995a40.png)

再更新试试

**Comment by CMHopeSunshine** [comment]
> > 问题已修。你要是想换成旧的也行，但是需要动手改一改。
> 
> 谢谢大佬，可以点拨一下怎么改嘛，，直接把插件和utils搬过去可以嘛？

把老的Paimon_Chat里的`Learning_repeate`文件夹放到`LittlePaimon/Plugins`里，启动如果缺依赖就用`poetry run pip install xxxxxxxx`装

**Comment by zhulinyv** [comment]
> > > > 问题已修。你要是想换成旧的也行，但是需要动手改一改。
> > > 
> > > 
> > > 入群欢迎启用+群号 不会报错了，但是可怜的群员被我踢了十几次没有一次被欢迎。😂
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/66541860/189584147-8819f2b5-e046-443d-9e09-76afba995a40.png)
> 
> 再更新试试

已经没问题啦

**Comment by zhulinyv** [comment]
> > > 问题已修。你要是想换成旧的也行，但是需要动手改一改。
> > 
> > 
> > 谢谢大佬，可以点拨一下怎么改嘛，，直接把插件和utils搬过去可以嘛？
> 
> 把老的Paimon_Chat里的`Learning_repeate`文件夹放到`LittlePaimon/Plugins`里，启动如果缺依赖就用`poetry run pip install xxxxxxxx`装

好的，已经还原，谢谢大佬
