### ISSUE TITLE
能否在git页面也上传一个resource包，合成图片都会缺少一个就会失败

### ISSUE THREAD

**Issue by AllGone2Silence** [CMHopeSunshine/LittlePaimon#251]
比如我要绘制抽卡分析纪录，快完成的时候总会报错缺少图片之类的。或者是ysd查看角色装备和数据，也是缺少某一个图片。上一个resource包资源不能用了，求一个

**Comment by CMHopeSunshine** [comment]
那些图片都是角色的头像、天赋、命座或者武器的头像等图标，数量太多了，我也没有完整的图包。一般失败的时候等一小会重新发就行了，网络问题而已。
