### ISSUE TITLE
关于启动后报 Failed to import "Paimon_Wiki"  Failed to import "Learning_Chat" Failed to import "Genshin_Voice" 以及数据库断开

### ISSUE THREAD

**Issue by GuiltyKirito** [CMHopeSunshine/LittlePaimon#252]
前三张图，影响正常启动吗?以及数据库断开是我需要配置什么吗？
![image](https://user-images.githubusercontent.com/13746290/190168144-253c8f4c-1fc4-4df8-9a9b-cbbf0d133807.png)
![image](https://user-images.githubusercontent.com/13746290/190168187-7d289a13-d112-4197-ace9-626032b5b22c.png)
![image](https://user-images.githubusercontent.com/13746290/190168246-e3f31d56-7422-4f8c-9761-ae73d152245f.png)

![image](https://user-images.githubusercontent.com/13746290/190167085-db9c9a2e-5797-4512-b468-eadec453d591.png)

**Comment by CMHopeSunshine** [comment]
运行`poetry run pip install nonebot-adapter-onebot -U`和`poetry run pip install jieba`

**Comment by GuiltyKirito** [comment]
> 运行`poetry run pip install nonebot-adapter-onebot -U`和`poetry run pip install jieba`

不愧是大佬，其他的报错没了，这个数据库连接会断开 请问是什么原因导致的呢？

**Comment by GuiltyKirito** [comment]
> 运行`poetry run pip install nonebot-adapter-onebot -U`和`poetry run pip install jieba`

哦 无视我的下一条，断开应该是端口被占用导致的 我清理掉看看
