### ISSUE TITLE
派蒙机器人更新重启问题

### ISSUE THREAD

**Issue by ljx-code** [CMHopeSunshine/LittlePaimon#254]
![image](https://user-images.githubusercontent.com/75619188/190940047-e4ca1b9c-dc0c-4605-b619-0d383916366a.png)
1.重启信息有时候发给我有时候不发给我...我一查日志他发给了自己...
2.现在版本到3.0.0beta7了派蒙发给我重启成功的版本信息还是5...

**Comment by CMHopeSunshine** [comment]
- 重启信息只发给第一个超级用户 ~~你把机器人自己设成超级用户了吧~~
- 没更新成功

**Comment by ljx-code** [comment]
![image](https://user-images.githubusercontent.com/75619188/190940508-20c5d83a-6608-4ef0-9d56-62cc8dc39483.png)
确实卡在了这里

**Comment by CMHopeSunshine** [comment]
建议去命令行`git pull`看具体执行信息

**Comment by ljx-code** [comment]
![image](https://user-images.githubusercontent.com/75619188/190940705-12e33b60-d862-4900-a28a-fbeff6f4a216.png)
啊这

**Comment by ljx-code** [comment]
破案了，我用pm指令修改了pyproject.toml

**Comment by CMHopeSunshine** [comment]
https://docs.paimon.cherishmoon.fun/question.html#%E6%9B%B4%E6%96%B0%E6%97%B6%E6%8F%90%E7%A4%BApyproject-toml%E6%9C%89%E5%86%B2%E7%AA%81

**Comment by ljx-code** [comment]
好吧是"nonebot_plugin_gocqhttp"...的锅
