### ISSUE TITLE
大大这是怎么回事啊

### ISSUE THREAD

**Issue by ljx-code** [CMHopeSunshine/LittlePaimon#255]
![image](https://user-images.githubusercontent.com/75619188/190965102-edac6785-4431-4d38-b707-f34ef46fd505.png)
我按照你说的解决了安装问题后，wiki不能使用了，然后我就重装了项目，结果项目卡死在这里动不了，断开xshell得重启服务器才能进行操作，不断开它就一直卡在这里....

**Comment by CMHopeSunshine** [comment]
这也没看出来卡了啊...发消息没反应么

**Comment by ljx-code** [comment]
> 这也没看出来卡了啊...发消息没反应么

是的 就卡死在那不动了...

**Comment by ljx-code** [comment]
> 这也没看出来卡了啊...发消息没反应么

我以为是小号的问题但是换了号还是不行

**Comment by CMHopeSunshine** [comment]
也许是内存不够，无法生成原神地图，把`LittlePaimon/plugins/Paimon_Wiki/__init__.py`的第52-63行和第109-169行的代码注释掉吧（或者稍等一会，我改成不自动生成地图）

**Comment by ljx-code** [comment]
> 也许是内存不够，无法生成原神地图，把`LittlePaimon/plugins/Paimon_Wiki/__init__.py`的第52-63行和第109-169行的代码注释掉吧（或者稍等一会，我改成不自动生成地图）

还真是，我的服务器太小了....谢谢哒
