### ISSUE TITLE
有没有帮忙看看，我在服务器部署后没有啥报错，却把进程杀了

### ISSUE THREAD

**Issue by w65467991** [CMHopeSunshine/LittlePaimon#257]
<img width="513" alt="image" src="https://user-images.githubusercontent.com/17965429/190996869-35b843ad-ebc4-4fae-8b95-202b7604f6df.png">

**Comment by w65467991** [comment]
自动杀的，我没动过

**Comment by CMHopeSunshine** [comment]
更新一下

**Comment by w65467991** [comment]
好了 谢谢~
