### ISSUE TITLE
bot反馈回来的更新时间好像不对？

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#258]
![image](https://user-images.githubusercontent.com/100580891/191040605-5df1e8c0-b20d-43e6-bd45-1a1967cfaa46.png)
如图，比真正更新的时间早了8小时，<del> 怎么评论区不支持md格式的，改成html吧（ </del>

**Comment by CMHopeSunshine** [comment]
美国时间(

**Comment by forchannot** [comment]
> 美国时间(

不知道有没有办法直接给时间加个8，好像不是美国时间，<del>美国应该是差10-12小时 </del>

**Comment by Chinzicam** [comment]
> > 美国时间(
> 
> 不知道有没有办法直接给时间加个8，好像不是美国时间，~美国应该是差10-12小时 ~

格林威治时间，我们东八区

**Comment by CMHopeSunshine** [comment]
刚刚commit对时间进行纠正了
