### ISSUE TITLE
生成地图出错

### ISSUE THREAD

**Issue by w65467991** [CMHopeSunshine/LittlePaimon#259]
<img width="569" alt="image" src="https://user-images.githubusercontent.com/17965429/191225170-826bbeb3-b96b-4459-b1f1-0bf123b9aab2.png">
直接killed

**Comment by w65467991** [comment]
是我配置不够吗？

**Comment by CMHopeSunshine** [comment]
> 是我配置不够吗？

是的，地图需要较大的内存，内存爆了就被杀了

**Comment by w65467991** [comment]
好的好的 了解
