### ISSUE TITLE
角色攻略的图片可以更新

### ISSUE THREAD

**Issue by yaojia25** [CMHopeSunshine/LittlePaimon#261]
大佬你好，我发现西风驿站的一些角色攻略图片有更新，但是大佬服务器上还是用的以前的版本，比如刻晴现在新的攻略有推荐四如雷，打激化等。其他角色攻略不知道有没有更新，可以都同步一下。
下面是新版的攻略
![刻晴](https://user-images.githubusercontent.com/31342892/191303405-f341eb59-2cf7-4b94-b018-56f10f58bc6a.jpg)

**Comment by CMHopeSunshine** [comment]
ok，稍后更新一下

**Comment by CMHopeSunshine** [comment]
已经更新
