### ISSUE TITLE
绘制实时便签出错  embedded null byte

### ISSUE THREAD

**Issue by QAQQL** [CMHopeSunshine/LittlePaimon#262]
出错环境:
Windows2012R2
Py3.8

在如下文件添加如下代码解决,暂不清楚错误原因
LittlePaimon\LittlePaimon\plugins\Paimon_DailyNote\draw.py

import locale
async def draw_daily_note_card(data, uid):
  locale.setlocale(locale.LC_ALL,'en') 
  locale.setlocale(locale.LC_CTYPE,'chinese')

**Comment by CMHopeSunshine** [comment]
应该是设备时区问题
