### ISSUE TITLE
老是学人说话，关了也没用

### ISSUE THREAD

**Issue by Omoinemie** [CMHopeSunshine/LittlePaimon#263]
![Screenshot_2022-09-21-08-00-33-926_com tencent mobileqq](https://user-images.githubusercontent.com/31991443/191385611-9471efeb-c8ee-43a6-a015-77a192ce81ca.jpg)
关了还是会发

**Comment by CMHopeSunshine** [comment]
可以把相关代码删除（`bot目录/LittlePaimon/plugins/learning_chat`)
