### ISSUE TITLE
拿到的ysd人物 面板没有激化蒸发等反应的伤害数值

### ISSUE THREAD

**Issue by YvetteVv** [CMHopeSunshine/LittlePaimon#265]
![image](https://user-images.githubusercontent.com/45150983/191413131-9ae8fff8-f115-4cc5-8520-5792ab80390b.png)
是因为不是最新版吗？我重新pull过

**Comment by CMHopeSunshine** [comment]
[#6838a0b](https://github.com/CMHopeSunshine/LittlePaimon/commit/6838a0b903e132e55ae82af65daaed35903e160c)

**Comment by YvetteVv** [comment]
那我为什么pull不到呢？
remote是这个git clone --depth=1 https://gitee.com/CherishMoon/LittlePaimon

**Comment by YvetteVv** [comment]
是这个源没更新

**Comment by CMHopeSunshine** [comment]
是...刚刚同步了一下，可以更了

**Comment by YvetteVv** [comment]
**请问jieba-fast安装的时候报错是什么原因？run的时候显示缺少这个module. go-cqhttp/显示404**
`lighthouse@VM-4-2-ubuntu:~/LittlePaimon$ poetry run pip install jieba-fast
Collecting jieba-fast
  Using cached jieba_fast-0.53.tar.gz (7.5 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: jieba-fast
  Building wheel for jieba-fast (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [63 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/jieba_fast
      copying jieba_fast/jieba_fast_functions_py3.py -> build/lib.linux-x86_64-cpython-38/jieba_fast
      copying jieba_fast/jieba_fast_functions_py2.py -> build/lib.linux-x86_64-cpython-38/jieba_fast
      copying jieba_fast/__main__.py -> build/lib.linux-x86_64-cpython-38/jieba_fast
      copying jieba_fast/_compat.py -> build/lib.linux-x86_64-cpython-38/jieba_fast
      copying jieba_fast/__init__.py -> build/lib.linux-x86_64-cpython-38/jieba_fast
      copying jieba_fast/__init__.pyc -> build/lib.linux-x86_64-cpython-38/jieba_fast
      copying jieba_fast/dict.txt -> build/lib.linux-x86_64-cpython-38/jieba_fast
      copying jieba_fast/_compat.pyc -> build/lib.linux-x86_64-cpython-38/jieba_fast
      creating build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/prob_start.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/jieba_fast_functions_py3.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/prob_emit.pyc -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/prob_trans.p -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/jieba_fast_functions_py2.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/prob_trans.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/__init__.pyc -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/prob_start.p -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/prob_start.pyc -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/prob_trans.pyc -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/prob_emit.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/prob_emit.p -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/__init__.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      creating build/lib.linux-x86_64-cpython-38/jieba_fast/analyse
      copying jieba_fast/analyse/textrank.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/analyse
      copying jieba_fast/analyse/idf.txt -> build/lib.linux-x86_64-cpython-38/jieba_fast/analyse
      copying jieba_fast/analyse/tfidf.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/analyse
      copying jieba_fast/analyse/__init__.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/analyse
      copying jieba_fast/analyse/analyzer.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/analyse
      creating build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      copying jieba_fast/posseg/prob_start.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      copying jieba_fast/posseg/prob_trans.p -> build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      copying jieba_fast/posseg/char_state_tab.p -> build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      copying jieba_fast/posseg/prob_trans.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      copying jieba_fast/posseg/char_state_tab.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      copying jieba_fast/posseg/prob_start.p -> build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      copying jieba_fast/posseg/prob_emit.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      copying jieba_fast/posseg/prob_emit.p -> build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      copying jieba_fast/posseg/viterbi.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      copying jieba_fast/posseg/__init__.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      creating build/lib.linux-x86_64-cpython-38/jieba_fast/source
      copying jieba_fast/source/jieba_fast_functions_wrap_py2.i -> build/lib.linux-x86_64-cpython-38/jieba_fast/source
      copying jieba_fast/source/jieba_fast_functions_wrap_py2_wrap.c -> build/lib.linux-x86_64-cpython-38/jieba_fast/source
      copying jieba_fast/source/jieba_fast_functions_py3.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/source
      copying jieba_fast/source/jieba_fast_functions_py2.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/source
      copying jieba_fast/source/jieba_fast_functions_wrap_py3_wrap.c -> build/lib.linux-x86_64-cpython-38/jieba_fast/source
      copying jieba_fast/source/jieba_fast_functions_wrap_py3.i -> build/lib.linux-x86_64-cpython-38/jieba_fast/source
      running build_ext
      building '_jieba_fast_functions_py3' extension
      creating build/temp.linux-x86_64-cpython-38
      creating build/temp.linux-x86_64-cpython-38/jieba_fast
      creating build/temp.linux-x86_64-cpython-38/jieba_fast/source
      x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/lighthouse/.cache/pypoetry/virtualenvs/littlepaimon-_aQo9zau-py3.8/include -I/usr/include/python3.8 -c jieba_fast/source/jieba_fast_functions_wrap_py3_wrap.c -o build/temp.linux-x86_64-cpython-38/jieba_fast/source/jieba_fast_functions_wrap_py3_wrap.o
      jieba_fast/source/jieba_fast_functions_wrap_py3_wrap.c:149:11: fatal error: Python.h: No such file or directory
        149 | # include <Python.h>
            |           ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for jieba-fast
  Running setup.py clean for jieba-fast
Failed to build jieba-fast
Installing collected packages: jieba-fast
  Running setup.py install for jieba-fast ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for jieba-fast did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      running install
      /home/lighthouse/.cache/pypoetry/virtualenvs/littlepaimon-_aQo9zau-py3.8/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/jieba_fast
      copying jieba_fast/jieba_fast_functions_py3.py -> build/lib.linux-x86_64-cpython-38/jieba_fast
      copying jieba_fast/jieba_fast_functions_py2.py -> build/lib.linux-x86_64-cpython-38/jieba_fast
      copying jieba_fast/__main__.py -> build/lib.linux-x86_64-cpython-38/jieba_fast
      copying jieba_fast/_compat.py -> build/lib.linux-x86_64-cpython-38/jieba_fast
      copying jieba_fast/__init__.py -> build/lib.linux-x86_64-cpython-38/jieba_fast
      copying jieba_fast/__init__.pyc -> build/lib.linux-x86_64-cpython-38/jieba_fast
      copying jieba_fast/dict.txt -> build/lib.linux-x86_64-cpython-38/jieba_fast
      copying jieba_fast/_compat.pyc -> build/lib.linux-x86_64-cpython-38/jieba_fast
      creating build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/prob_start.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/jieba_fast_functions_py3.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/prob_emit.pyc -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/prob_trans.p -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/jieba_fast_functions_py2.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/prob_trans.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/__init__.pyc -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/prob_start.p -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/prob_start.pyc -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/prob_trans.pyc -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/prob_emit.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/prob_emit.p -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      copying jieba_fast/finalseg/__init__.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/finalseg
      creating build/lib.linux-x86_64-cpython-38/jieba_fast/analyse
      copying jieba_fast/analyse/textrank.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/analyse
      copying jieba_fast/analyse/idf.txt -> build/lib.linux-x86_64-cpython-38/jieba_fast/analyse
      copying jieba_fast/analyse/tfidf.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/analyse
      copying jieba_fast/analyse/__init__.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/analyse
      copying jieba_fast/analyse/analyzer.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/analyse
      creating build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      copying jieba_fast/posseg/prob_start.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      copying jieba_fast/posseg/prob_trans.p -> build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      copying jieba_fast/posseg/char_state_tab.p -> build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      copying jieba_fast/posseg/prob_trans.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      copying jieba_fast/posseg/char_state_tab.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      copying jieba_fast/posseg/prob_start.p -> build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      copying jieba_fast/posseg/prob_emit.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      copying jieba_fast/posseg/prob_emit.p -> build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      copying jieba_fast/posseg/viterbi.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      copying jieba_fast/posseg/__init__.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/posseg
      creating build/lib.linux-x86_64-cpython-38/jieba_fast/source
      copying jieba_fast/source/jieba_fast_functions_wrap_py2.i -> build/lib.linux-x86_64-cpython-38/jieba_fast/source
      copying jieba_fast/source/jieba_fast_functions_wrap_py2_wrap.c -> build/lib.linux-x86_64-cpython-38/jieba_fast/source
      copying jieba_fast/source/jieba_fast_functions_py3.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/source
      copying jieba_fast/source/jieba_fast_functions_py2.py -> build/lib.linux-x86_64-cpython-38/jieba_fast/source
      copying jieba_fast/source/jieba_fast_functions_wrap_py3_wrap.c -> build/lib.linux-x86_64-cpython-38/jieba_fast/source
      copying jieba_fast/source/jieba_fast_functions_wrap_py3.i -> build/lib.linux-x86_64-cpython-38/jieba_fast/source
      running build_ext
      building '_jieba_fast_functions_py3' extension
      creating build/temp.linux-x86_64-cpython-38
      creating build/temp.linux-x86_64-cpython-38/jieba_fast
      creating build/temp.linux-x86_64-cpython-38/jieba_fast/source
      x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/lighthouse/.cache/pypoetry/virtualenvs/littlepaimon-_aQo9zau-py3.8/include -I/usr/include/python3.8 -c jieba_fast/source/jieba_fast_functions_wrap_py3_wrap.c -o build/temp.linux-x86_64-cpython-38/jieba_fast/source/jieba_fast_functions_wrap_py3_wrap.o
      jieba_fast/source/jieba_fast_functions_wrap_py3_wrap.c:149:11: fatal error: Python.h: No such file or directory
        149 | # include <Python.h>
            |           ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> jieba-fast

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`

**Comment by CMHopeSunshine** [comment]
jieba_fast要vs C++编译器，装jieba吧。`poetry run pip install jieba`

**Comment by YvetteVv** [comment]
**运行全部成功了为什么go-cqhttp会404**
`lighthouse@VM-4-2-ubuntu:~/LittlePaimon$ poetry run nb run
09-21 13:11:34 [SUCCESS] nonebot | NoneBot is initializing...
09-21 13:11:34 [INFO] nonebot | Current Env: prod
09-21 13:11:34 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
09-21 13:11:34 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_myb_exchange"
09-21 13:11:34 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_couplets"
09-21 13:11:35 [SUCCESS] nonebot | Succeeded to import "LittlePaimon.manager.bot_manager"
09-21 13:11:35 [SUCCESS] nonebot | Succeeded to import "LittlePaimon.manager.plugin_manager"
09-21 13:11:35 [SUCCESS] nonebot | Succeeded to import "LittlePaimon.manager.database_manager"
09-21 13:11:36 [SUCCESS] nonebot | Succeeded to import "LittlePaimon.manager.alias_manager"
09-21 13:11:36 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha_Log"
09-21 13:11:36 [SUCCESS] nonebot | Succeeded to import "Paimon_Info"
09-21 13:11:36 [SUCCESS] nonebot | Succeeded to import "Paimon_MonthInfo"
09-21 13:11:36 [SUCCESS] nonebot | Succeeded to import "Paimon_CloudGenshin"
09-21 13:11:37 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_htmlrender"
09-21 13:11:37 [SUCCESS] nonebot | Succeeded to import "Genshin_Calendar"
09-21 13:11:37 [SUCCESS] nonebot | Succeeded to import "Genshin_Voice"
09-21 13:11:37 [SUCCESS] nonebot | Succeeded to import "Genshin_AIVoice"
09-21 13:11:37 [SUCCESS] nonebot | Succeeded to import "Paimon_DailyNote"
09-21 13:11:38 [SUCCESS] nonebot | Succeeded to import "Learning_Chat"
09-21 13:11:40 [SUCCESS] nonebot | Succeeded to import "Paimon_Wiki"
09-21 13:11:40 [SUCCESS] nonebot | Succeeded to import "news60s"
09-21 13:11:41 [SUCCESS] nonebot | Succeeded to import "Paimon_Autobbs"
09-21 13:11:41 [SUCCESS] nonebot | Succeeded to import "Paimon_Bind"
09-21 13:11:41 [SUCCESS] nonebot | Succeeded to import "Paimon_Gacha"
09-21 13:11:41 [SUCCESS] nonebot | Succeeded to import "NoticeAndRequest"
09-21 13:11:41 [SUCCESS] nonebot | Succeeded to import "LittlePaimon"
09-21 13:11:41 [SUCCESS] nonebot | Running NoneBot...
09-21 13:11:41 [INFO] uvicorn | Started server process [37733]
09-21 13:11:41 [INFO] uvicorn | Waiting for application startup.
09-21 13:11:41 [INFO] nonebot_plugin_apscheduler | Scheduler Started
09-21 13:11:41 [INFO] LittlePaimon | 
██╗     ██╗████████╗████████╗██╗     ███████╗  ██████╗  █████╗ ██╗███╗   ███╗ ██████╗ ███╗   ██╗
██║     ██║╚══██╔══╝╚══██╔══╝██║     ██╔════╝  ██╔══██╗██╔══██╗██║████╗ ████║██╔═══██╗████╗  ██║
██║     ██║   ██║      ██║   ██║     █████╗    ██████╔╝███████║██║██╔████╔██║██║   ██║██╔██╗ ██║
██║     ██║   ██║      ██║   ██║     ██╔══╝    ██╔═══╝ ██╔══██║██║██║╚██╔╝██║██║   ██║██║╚██╗██║
███████╗██║   ██║      ██║   ███████╗███████╗  ██║     ██║  ██║██║██║ ╚═╝ ██║╚██████╔╝██║ ╚████║
╚══════╝╚═╝   ╚═╝      ╚═╝   ╚══════╝╚══════╝  ╚═╝     ╚═╝  ╚═╝╚═╝╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═══╝
09-21 13:11:41 [SUCCESS] LittlePaimon | [数据库]连接成功
09-21 13:11:42 [INFO] LittlePaimon | [原神Cookie]启用CookieWeb成功，地址http://127.0.0.1:13579/LittlePaimon/cookie
09-21 13:11:42 [INFO] LittlePaimon | [资源检查]开始检查资源
09-21 13:11:42 [INFO] LittlePaimon | [资源检查]资源完好，无需下载
09-21 13:11:43 [INFO] nonebot_plugin_htmlrender | 使用 chromium 启动
09-21 13:11:43 [INFO] nonebot_plugin_htmlrender | Browser Started.
09-21 13:11:43 [INFO] uvicorn | Application startup complete.
09-21 13:11:43 [INFO] uvicorn | Uvicorn running on http://0.0.0.0:13579 (Press CTRL+C to quit)
09-21 13:11:48 [INFO] uvicorn | 72.74.66.235:63917 - "GET /go-cqhttp/ HTTP/1.1" 404
`

**Comment by YvetteVv** [comment]
: )
