### ISSUE TITLE
希望大佬可以出一个插件的合集

### ISSUE THREAD

**Issue by Aries277** [CMHopeSunshine/LittlePaimon#266]

**Comment by ljx-code** [comment]
你不说具体一点，作者大大也不清楚你这个合集的概念到底是个啥。

**Comment by Aries277** [comment]
就是一些娱乐功能的插件还有圣遗物、抽签解签之类的

**Comment by Chinzicam** [comment]
> 就是一些娱乐功能的插件还有圣遗物、抽签解签之类的

有没有可能，你找的东西是这个https://v2.nonebot.dev/store

**Comment by Aries277** [comment]
> > 就是一些娱乐功能的插件还有圣遗物、抽签解签之类的
> 
> 没有可能，你找的东西就是这个https://v2.nonebot.dev/store

这些插件怎么安装

**Comment by zuixiaoxiao** [comment]
> > > 就是一些娱乐功能的插件还有圣遗物、抽签解签之类的
> > 
> > 
> > 没有可能，你找的东西就是这个https://v2.nonebot.dev/store
> 
> 这些插件怎么安装

点右上角的白色猫

**Comment by 1103859909** [comment]
直接装就行了吗  不用适配什么的吗

**Comment by CMHopeSunshine** [comment]
复制对应的安装指令，前面再加个poetry run，运行就能安装
