### ISSUE TITLE
私聊导入抽卡记录发送文件后无反应

### ISSUE THREAD

**Issue by Mr233sir** [CMHopeSunshine/LittlePaimon#267]
![QQ图片20220921171040](https://user-images.githubusercontent.com/30330282/191464947-b749723a-f248-4c1c-9457-0cfbb95d4c89.png)
![QQ图片20220921171236](https://user-images.githubusercontent.com/30330282/191465155-18a33cb4-3d86-43f9-9f67-a16531c3af1a.png)
机器人账号持续处于风控状态，群聊里用不了，然后私聊也用不了

**Comment by linword** [comment]
虽然但是，账号被风控难道不是腾讯的锅嘛

**Comment by CMHopeSunshine** [comment]
命令被`nonebot_plugin_addFriend`插件给拦截了，不是派蒙自己的问题

**Comment by Mr233sir** [comment]
> 虽然但是，账号被风控难道不是腾讯的锅嘛

所以我想私聊用，但是私聊发文件过去没反应

**Comment by Mr233sir** [comment]
> 命令被`nonebot_plugin_addFriend`插件给拦截了，不是派蒙自己的问题

意思是删掉这个插件就能私聊发文件也可以了？

**Comment by CMHopeSunshine** [comment]
应该，而且派蒙本身也有相关的远程处理好友请求的功能，和这个插件的功能重复了

**Comment by Mr233sir** [comment]
> 

谢谢，解决了
