### ISSUE TITLE
运行poetry run nb run时遇到了奇怪的问题

### ISSUE THREAD

**Issue by MotocoZg** [CMHopeSunshine/LittlePaimon#270]
如图
![U 5I %N80 5$Z)%SGWQW 6E](https://user-images.githubusercontent.com/111079540/192135936-487f2b5f-438d-4336-9239-61d0fe534cca.png)

**Comment by CMHopeSunshine** [comment]
目录不能有中文路径

**Comment by MotocoZg** [comment]
![image](https://user-images.githubusercontent.com/111079540/192136149-030eb70a-97d3-41e8-936b-8725f494aac7.png)
![image](https://user-images.githubusercontent.com/111079540/192136158-b38483f4-bc55-461e-b907-26dd8c21f566.png)
改名后run了但是没有成功启动...

**Comment by CMHopeSunshine** [comment]
依赖没装，`poetry install`

**Comment by MotocoZg** [comment]
已运行....应该是因为之前中文路径没装上...打扰了..
