### ISSUE TITLE
centos启动失败

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#273]
centos在启动到加载cookieweb时候就会这样，我在paimonconfigyml中关闭了cookieweb还是会这样，图片有点小，不知道能不能看清。请问大佬怎么解决
![Screenshot_2022-09-28-09-55-43-936_com termux](https://user-images.githubusercontent.com/100580891/192670750-c64d4a18-a293-4631-828e-9cdd0f30d7ab.jpg)

**Comment by CMHopeSunshine** [comment]
这是playwright启动不成功，尝试运行一下`poetry run playwright install`

**Comment by forchannot** [comment]
> 这是playwright启动不成功，尝试运行一下`poetry run playwright install`

运行过了还是这样，playwright已经安装上了，再次运行提示我这个BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
![Screenshot_2022-09-28-15-09-01-390_com termux](https://user-images.githubusercontent.com/100580891/192711954-992a3845-4ad2-4aa7-8656-965179881271.jpg)

**Comment by forchannot** [comment]
百度了下好像是这东西不支持centos？

**Comment by CMHopeSunshine** [comment]
https://github.com/kexue-z/nonebot-plugin-htmlrender#centos-%E4%BD%BF%E7%94%A8-yum
参考这里安装一下依赖试试，playwright对centos的支持确实一般

**Comment by CMHopeSunshine** [comment]
https://github.com/kexue-z/nonebot-plugin-htmlrender#centos-%E4%BD%BF%E7%94%A8-yum
参考这里安装一下依赖试试，playwright✓centos的支持确实一般
