### ISSUE TITLE
查看抽卡记录时报错

### ISSUE THREAD

**Issue by GuiltyKirito** [CMHopeSunshine/LittlePaimon#274]
查看抽卡记录时报错，大佬帮忙看看~

```
➤绘制抽卡记录图片时出现错误：1 validation error for FourStarItem
```

![image](https://user-images.githubusercontent.com/13746290/192695637-8a899b4b-7cf6-4bb5-bdb8-33c30e8689fc.png)

**Comment by GuiltyKirito** [comment]
盲猜是因为抽中了坎蒂丝 而坎蒂丝还没落库？

**Comment by CMHopeSunshine** [comment]
新角色还没适配，稍等

**Comment by GuiltyKirito** [comment]
> 新角色还没适配，稍等

```
➤➤绘制抽卡记录图片时出现错误：UI_AvatarIcon_Candace.png.png下载失败，请检查网络
```

提示图片下载失败，是不是图片格式问题？
