### ISSUE TITLE
关于website，需要怎么配置呢？

### ISSUE THREAD

**Issue by GuiltyKirito** [CMHopeSunshine/LittlePaimon#276]
亲亲，我配置了地址，但是 web地址还是不能访问，咋整啊？

![image](https://user-images.githubusercontent.com/13746290/192735764-04dee589-cebc-42f8-92d3-692727e04b58.png)
![image](https://user-images.githubusercontent.com/13746290/192735799-efdcf1a3-4b88-4f5d-a688-0167058e4ae2.png)
![image](https://user-images.githubusercontent.com/13746290/192736062-666f4ffb-d920-4d96-aab7-f25981e8195f.png)
![image](https://user-images.githubusercontent.com/13746290/192736146-413d3a89-e1c5-4507-b297-b58d2fefe651.png)
![image](https://user-images.githubusercontent.com/13746290/192736415-62f4a141-ac56-49ff-ad02-450dfe59104f.png)

**Comment by CMHopeSunshine** [comment]
你指的是CookieWeb还是go-cqhttp的web ui不能访问

**Comment by GuiltyKirito** [comment]
> 你指的是CookieWeb还是go-cqhttp的web ui不能访问

是CookieWeb的页面，我想见识下~但是不知道怎么配置 滑鸡~

**Comment by CMHopeSunshine** [comment]
端口开放了没，在防火墙中把18900端口开放

**Comment by GuiltyKirito** [comment]
> 端口开放了没，在防火墙中把18900端口开放

嗯嗯，端口开放了的，并重启过服务器的
![image](https://user-images.githubusercontent.com/13746290/192737891-a2b6dcfc-001a-4de2-8798-9cf4956c7d7a.png)

**Comment by CMHopeSunshine** [comment]
linux自带的防火墙也要开放，另外地址前面的http:也不能漏

**Comment by GuiltyKirito** [comment]
> linux自带的防火墙也要开放，另外地址前面的http:也不能漏

那我可以用域名吗？我可以直接https://xxx:18900/xxx吗？

**Comment by CMHopeSunshine** [comment]
可以，不过用反向代理的话要额外配置静态文件托管，参考[pywebio文档](https://pywebio.readthedocs.io/zh_CN/latest/misc.html?highlight=nginx#nginx-websocket-config-example)

**Comment by GuiltyKirito** [comment]
> 可以，不过用反向代理的话要额外配置静态文件托管，参考[pywebio文档](https://pywebio.readthedocs.io/zh_CN/latest/misc.html?highlight=nginx#nginx-websocket-config-example)

got it , love you!

**Comment by GuiltyKirito** [comment]
> linux自带的防火墙也要开放，另外地址前面的http:也不能漏

之前没有防火墙，我刚刚装了并关闭了，http也加了，还是不行，不知道是不是漏了什么配置。

**Comment by forchannot** [comment]
> > linux自带的防火墙也要开放，另外地址前面的http:也不能漏
> 
> 之前没有防火墙，我刚刚装了并关闭了，http也加了，还是不行，不知道是不是漏了什么配置。

你也是腾讯云嘛，我腾讯云也是不行，端口都开放了
