### ISSUE TITLE
现在的小派蒙怎么配置智障说话呀

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#281]
我把sqlite3加入了环境变量，就可以了吗

**Comment by Chinzicam** [comment]
新版小派蒙群聊学习默认开启
![image](https://user-images.githubusercontent.com/108013361/193191589-af02cadd-d07d-4982-b853-9b30d22cece1.png)
具体使用方法和关闭可以去看看文档咋写的

> 我把sqlite3加入了环境变量，就可以了吗

**Comment by forchannot** [comment]
> 新版小派蒙群聊学习默认开启 ![image](https://user-images.githubusercontent.com/108013361/193191589-af02cadd-d07d-4982-b853-9b30d22cece1.png) 具体使用方法和关闭可以去看看文档咋写的
> 
> > 我把sqlite3加入了环境变量，就可以了吗

文档里面群聊学习和其他功能都点不了
![image](https://user-images.githubusercontent.com/100580891/193196727-2c935cf7-bc64-474a-95e1-6c98c9925316.png)

**Comment by Chinzicam** [comment]
> > 新版小派蒙群聊学习默认开启 ![image](https://user-images.githubusercontent.com/108013361/193191589-af02cadd-d07d-4982-b853-9b30d22cece1.png) 具体使用方法和关闭可以去看看文档咋写的
> > > 我把sqlite3加入了环境变量，就可以了吗
> 
> 文档里面群聊学习和其他功能都点不了 ![image](https://user-images.githubusercontent.com/100580891/193196727-2c935cf7-bc64-474a-95e1-6c98c9925316.png)

啊这，我指的是开启和关闭插件。其实你啥都不做，群聊学习在每次重启派蒙时，都会自动开启的。或者你艾特机器人发个开启学习或者关闭学习看看回复。前期数据库没啥东西，多挂会估计就会聊天了，嫌学习慢我记得config里面专门有个派蒙聊天的learnchat配置文件

**Comment by CMHopeSunshine** [comment]
文档这部分还没完善，不过群聊学习现在是默认开启的，无需其他配置

**Comment by forchannot** [comment]
> 文档这部分还没完善，不过群聊学习现在是默认开启的，无需其他配置

好的谢谢

**Comment by forchannot** [comment]
> > > 新版小派蒙群聊学习默认开启 ![image](https://user-images.githubusercontent.com/108013361/193191589-af02cadd-d07d-4982-b853-9b30d22cece1.png) 具体使用方法和关闭可以去看看文档咋写的
> > > > 我把sqlite3加入了环境变量，就可以了吗
> > 
> > 
> > 文档里面群聊学习和其他功能都点不了 ![image](https://user-images.githubusercontent.com/100580891/193196727-2c935cf7-bc64-474a-95e1-6c98c9925316.png)
> 
> 啊这，我指的是开启和关闭插件。其实你啥都不做，群聊学习在每次重启派蒙时，都会自动开启的。或者你艾特机器人发个开启学习或者关闭学习看看回复。前期数据库没啥东西，多挂会估计就会聊天了，嫌学习慢我记得config里面专门有个派蒙聊天的learnchat配置文件

嗯，谢谢
