### ISSUE TITLE
3.1更新，无法pull

### ISSUE THREAD

**Issue by YvetteVv** [CMHopeSunshine/LittlePaimon#284]
lighthouse@VM-4-2-ubuntu:~/LittlePaimon$ git pull origin Bot
From https://github.com/CMHopeSunshine/LittlePaimon
 * branch            Bot        -> FETCH_HEAD
fatal: refusing to merge unrelated histories

**Comment by YvetteVv** [comment]
另外pull的时候经常很慢但好像gitee更新的不及时，有办法将解决吗，我换源不能access这个repo
lighthouse@VM-4-2-ubuntu:~/LittlePaimon$ git pull
fatal: unable to access 'https://github.com/CMHopeSunshine/LittlePaimon/': Failed to connect to github.com port 443: Connection timed out

**Comment by CMHopeSunshine** [comment]
gitee源无法同步，还是换成github源吧，timed out网络问题而已，多试几次
