### ISSUE TITLE
ck error

### ISSUE THREAD

**Issue by Mohammed0821** [CMHopeSunshine/LittlePaimon#286]
#268 
接上回issues 
我用了miria去测试是否是风控问题，实际上是不存在，也就是根本没有风控问题
如果绑定了私人ck就会查询成功，但是一旦发送ssbq就会导致ck失效直接被删除（机器人回复：cookie疑似失效了），再然后我使用了一个米游社账号去当公共ck池，结果会报错

如果使用未登录的账号获取ck机器人会报错：这个cookie无效哦，请确认是否正确
go-cqhttp和本项目我都重新clone搭建了一遍
仍然会出现这个问题

ck获取方法我都用F12的开发者工具和JavaScript都测试了一遍，均会失效

以下是一小段错误报告
10-02 02:39:41 [INFO] LittlePaimon | [原神实时便签]开始执行查询
10-02 02:39:41 [INFO] LittlePaimon | [原神Cookie]用户180952XXXX的私人cookie101598XXX连续失效，已删除
10-02 02:39:41 [INFO] LittlePaimon | [原神实时便签]➤用户1809521264 UID101598211获取数据失败, 你的UID10159XXX的cookie疑
似失效了
10-02 02:39:41 [INFO] nonebot | Matcher <Matcher from LittlePaimon.plugins.Paimon_DailyNote, type=message, priority=9, t
emp=False> running complete
10-02 02:39:44 [SUCCESS] nonebot | ONEBOT V11 763865695 | [message.group.normal]: Message 1813408XXX from 3285494XXX@[群
:875090502] "ys"
10-02 02:39:44 [INFO] nonebot | Event will be handled by <Matcher from LittlePaimon.plugins.Paimon_Info, type=message, p
riority=10, temp=False>
10-02 02:39:44 [INFO] LittlePaimon | [原神信息查询]开始执行
10-02 02:39:44 [INFO] LittlePaimon | [原神信息查询]➤ 用户3285494XXX UID109445XXX
10-02 02:39:44 [INFO] LittlePaimon | [原神信息]更新109445XXX的玩家数据时出错，消息为       #这块地方机器人会重复发送查询者的uid:@XXX UID1094XXXXX
10-02 02:39:44 [INFO] LittlePaimon | [原神信息查询]➤➤
10-02 02:39:45 [INFO] nonebot | Matcher <Matcher from LittlePaimon.plugins.Paimon_Info, type=message, priority=10, temp=
False> running complete

**Comment by kongxiangyi88** [comment]
之前我群友因为用米哈游通行证的cookie来查，ssbq是一用就掉，米游社绑上后就好了，不知道是不是同样问题

**Comment by CMHopeSunshine** [comment]
账号问题，有的账号部分功能有时会用不了

**Comment by Mohammed0821** [comment]
> 之前我群友因为用米哈游通行证的cookie来查，ssbq是一用就掉，米游社绑上后就好了，不知道是不是同样问题

米游社的我一开始就是用那个，后面也会直接失效。

**Comment by Mohammed0821** [comment]
> 账号问题，有的账号部分功能有时会用不了

其实我感觉不是账号问题，如果发送签到的话，也会导致ck被删除，但是我用miria的一个插件进行签到是能成功的，随后我又尝试了另一款原神的机器人，结果是除了本项目上面不能使用的功能全部可以正常使用，这也就排除了QQ/米游社账号问题了

**Comment by CMHopeSunshine** [comment]
这种问题几乎无法排查，米游社返回什么机器人就提示什么，我只能建议换个号试试

**Comment by Mohammed0821** [comment]
> 这种问题几乎无法排查，米游社返回什么机器人就提示什么，我只能建议换个号试试

巧合的是，我甚至用了新的QQ号去做了测试，一样的问题

**Comment by CMHopeSunshine** [comment]
我指的是米游社账号...是米游社那边返回状态码说ck无效的

**Comment by Mohammed0821** [comment]
> 我指的是米游社账号...是米游社那边返回状态码说ck无效的

可......我用别的机器人是可以返回正常的，也就是ck没有问题，查询体力什么的也是一切正常

**Comment by zhulinyv** [comment]
I have the same problem.
