### ISSUE TITLE
ysb提示cookie中没有login_ticket

### ISSUE THREAD

**Issue by ALEXsun0** [CMHopeSunshine/LittlePaimon#288]
每个人绑定都会提示
实际上是有`login_ticket=`这一字段的
使用不影响

**Comment by zuixiaoxiao** [comment]
> 每个人绑定都会提示 实际上是有`login_ticket=`这一字段的 使用不影响

你绑的是米游社的还是米哈游通行证的

**Comment by ALEXsun0** [comment]
两个同时开着获取的，f12开在通行证那边

**Comment by ALEXsun0** [comment]
UM_distinctid=00000; _ga=11111; _gid=000; _gat=111; DEVICEFP_SEED_ID=000; DEVICEFP_SEED_TIME=111; DEVICEFP=000; login_uid=1111111; login_ticket=11111111; ltoken=00000; ltuid=111111; cookie_token=000000; account_id=#####
大概长这个样子

**Comment by zuixiaoxiao** [comment]
> 两个同时开着获取的，f12开在通行证那边

那就是账号登入问题，退出米游社登入后重新登入获取
