### ISSUE TITLE
新功能提议

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#290]
管理员群主或者超级管理员可以使用艾特别人命令来直接查询或者对该对象执行命令，如更新抽卡记录，ysa等后接艾特可以直接作用于目标对象

**Comment by zuixiaoxiao** [comment]
> 管理员群主或者超级管理员可以使用艾特别人命令来直接查询或者对该对象执行命令，如更新抽卡记录，ysa等后接艾特可以直接作用于目标对象

emm，我记得你可以先去试试

**Comment by zuixiaoxiao** [comment]
> 管理员群主或者超级管理员可以使用艾特别人命令来直接查询或者对该对象执行命令，如更新抽卡记录，ysa等后接艾特可以直接作用于目标对象

emm，我觉得你可以先去试试

**Comment by Chinzicam** [comment]
> 管理员群主或者超级管理员可以使用艾特别人命令来直接查询或者对该对象执行命令，如更新抽卡记录，ysa等后接艾特可以直接作用于目标对象

有没有可能，该功能早就有了
