### ISSUE TITLE
在新服务器全新安装

### ISSUE THREAD

**Issue by fangyuanshisan** [CMHopeSunshine/LittlePaimon#293]
全新安装bot分支,但是运行后不能访问网页管理端,  没搞清楚 Bot和nonebot2分支的区别, bot 分支是只有机器人吗

**Comment by CMHopeSunshine** [comment]
是gocq的管理端还是绑cookie的管理端打不开？
nonebot2分支是个nb插件，bot分支就是一个完整的nb

**Comment by fangyuanshisan** [comment]
bot分支完整的nb, 管理端打不开,绑cookie的管理端可以打开的,我一度怀疑是我进错文件夹启动了

**Comment by CMHopeSunshine** [comment]
nonebot-plugin-gocqhttp这个插件装了吗，云服务器的话还要开放端口

**Comment by fangyuanshisan** [comment]
装了的,能看到访问,但是是404

**Comment by fangyuanshisan** [comment]
好像重启后可以了

**Comment by fangyuanshisan** [comment]
<img width="843" alt="image" src="https://user-images.githubusercontent.com/3401189/194335374-10ef39d1-46b7-4a80-ba86-7ab4f7c69a76.png">

**Comment by fangyuanshisan** [comment]
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/3401189/194336389-29d5a863-9a3e-4926-b6fe-01e5347d97f5.png">

**Comment by fangyuanshisan** [comment]
10-06 22:19:50 [INFO] uvicorn | Waiting for application startup.
10-06 22:19:57 [INFO] nonebot_plugin_gocqhttp | Begin to Download binary from https://download.fastgit.org/Mrs4s/go-cqhttp/releases/latest/download/go-cqhttp_linux_amd64.tar.gz
10-06 22:19:59 [INFO] nonebot_plugin_gocqhttp | Startup complete, Web UI has served to http://0.0.0.0:13579/go-cqhttp/ 


重新进入了一下 poetry shell  有个下载日志 之后就可以打开管理面板了
