### ISSUE TITLE
请问这是什么情况

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#295]
![image](https://user-images.githubusercontent.com/100580891/194881976-707c6be3-3022-4266-a5e1-0f29f1221257.png)

**Comment by forchannot** [comment]
好像我不能编辑toml文件，我想增加加载插件就会这样

**Comment by CMHopeSunshine** [comment]
提示toml语法错误...把pyproject.toml打开看看什么情况吧

**Comment by forchannot** [comment]
> 提示toml语法错误...把pyproject.toml打开看看什么情况吧

我重新克隆了一份把toml覆盖了下就可以了，之前啥也没干，就nb安装了一个插件就成这样了
