### ISSUE TITLE
cookie web无法访问

### ISSUE THREAD

**Issue by HMScygnet** [CMHopeSunshine/LittlePaimon#296]
![W7J1~`A`8%W)3M8)7)5%9}U](https://user-images.githubusercontent.com/65561426/195321212-c1427371-1285-4802-b5b3-c2b6e21b8979.png)
![6GW S1 VWCP_C6PWOK~55Z4](https://user-images.githubusercontent.com/65561426/195321240-0feab219-8320-4dcc-ac9b-51188b92ba03.png)
![3MYN}YVDQIW0LV33)PK~08P](https://user-images.githubusercontent.com/65561426/195321262-aae3ab1c-d86d-4fb7-a575-e005a65f3095.png)
腾讯云服务器
在ip为localhost时访问显示拒绝请求，更改为服务器公网ip通过ip访问时依旧为拒绝请求，端口确认已开启

**Comment by CMHopeSunshine** [comment]
你用的端口是9000，所以应该是9000而不是13579

**Comment by HMScygnet** [comment]
> 你用的端口是9000，所以应该是9000而不是13579

已解决，感谢解答
