### ISSUE TITLE
请问下nonebot_plugin_myb_exchange插件能否更新呢

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#298]
如题，第一是添加麻烦，不能记录上次的添加信息
第二是能否将兑换时间延长，服务器的时间和北京标准时间会差个几秒，可否将兑换时间设置成±15s左右开启兑换，最近兑换全都是不在商品兑换时间内，已经对服务器进行了时间矫正，还是会这样
几个小请求

**Comment by CMHopeSunshine** [comment]
收到！后续会更新
