### ISSUE TITLE
提示了个 1034的错误 是不是 token失效了？

### ISSUE THREAD

**Issue by GuiltyKirito** [CMHopeSunshine/LittlePaimon#299]
![image](https://user-images.githubusercontent.com/13746290/195476648-567c1d66-31f0-403d-b42e-da3a626ba909.png)

亲亲大大，请问有类似的错误码表咩？

**Comment by meatjam** [comment]
是因为签到增加了验证
![}N3$V1EVFF)V@ZGIIGPT43I](https://user-images.githubusercontent.com/43535074/195483422-27163a39-69d1-4b55-a2e2-5a650594da88.jpg)
