### ISSUE TITLE
期待出插件版本

### ISSUE THREAD

**Issue by Kimiato** [CMHopeSunshine/LittlePaimon#3]
希望有插件版本，能够直接接入使用~

**Comment by CMHopeSunshine** [comment]
主要功能在modules内的Genshin_Paimon文件夹，它就是插件版本，丢进Hoshino的modules就行；模拟抽卡的冷却时间用了个人改的PriFreqLimiter，在本项目util内找到copy到Hoshino的util就能使用了

**Comment by CMHopeSunshine** [comment]
后续考虑开一个分支，去掉hoshino本体，只保留插件版本

**Comment by synodriver** [comment]
可以支持nonebot2吗（

**Comment by CMHopeSunshine** [comment]
> 

最近比较忙，闲下来了会考虑迁移nb2

**Comment by synodriver** [comment]
好像改起来比较容易，我try try(

**Comment by CMHopeSunshine** [comment]
> 好像改起来比较容易，我try try(

基本事件逻辑改改就能用了(

**Comment by synodriver** [comment]
进行了[大刀阔斧的改革](https://github.com/synodriver/LittlePaimon/tree/nb2) ，基本上有nb2的味了，主要是Service变MatcherGroup， 不能直接发CQ码~~nb2为了安全全部转义~~ ， 以及一些依赖注入， aiorequests变aiohttp，on_notice和on_request的改动，等下还得跑一次试试

**Comment by CMHopeSunshine** [comment]
> 进行了[大刀阔斧的改革](https://github.com/synodriver/LittlePaimon/tree/nb2) ，基本上有nb2的味了，主要是Service变MatcherGroup， 不能直接发CQ码~nb2为了安全全部转义~ ， 以及一些依赖注入，aps插件独立了，on_regex从state找东西， aiorequests变aiohttp，on_notice和on_request的改动，等下还得跑一次试试

感谢大佬！！！正式迁移的时候会参考

**Comment by synodriver** [comment]
> > 进行了[大刀阔斧的改革](https://github.com/synodriver/LittlePaimon/tree/nb2) ，基本上有nb2的味了，主要是Service变MatcherGroup， 不能直接发CQ码~nb2为了安全全部转义~ ， 以及一些依赖注入，aps插件独立了，on_regex从state找东西， aiorequests变aiohttp，on_notice和on_request的改动，等下还得跑一次试试
> 
> 感谢大佬！！！正式迁移的时候会参考

[这个](https://github.com/CMHopeSunshine/LittlePaimon/blob/c3599c5c02d7d22ac938191b6a1961d7b37881d9/hoshino/modules/myb_exchange/__init__.py#L153) info是？

**Comment by synodriver** [comment]
[这个应该是w in msg吧](https://github.com/CMHopeSunshine/LittlePaimon/blob/4bbc07e52fd1e38e187e5a4cc7c983738e6c6bef/hoshino/modules/Paimonchat/Paimonchat.py#L65)

**Comment by CMHopeSunshine** [comment]
> > > 进行了[大刀阔斧的改革](https://github.com/synodriver/LittlePaimon/tree/nb2) ，基本上有nb2的味了，主要是Service变MatcherGroup， 不能直接发CQ码~nb2为了安全全部转义~ ， 以及一些依赖注入，aps插件独立了，on_regex从state找东西， aiorequests变aiohttp，on_notice和on_request的改动，等下还得跑一次试试
> > 
> > 
> > 感谢大佬！！！正式迁移的时候会参考
> 
> [这个](https://github.com/CMHopeSunshine/LittlePaimon/blob/c3599c5c02d7d22ac938191b6a1961d7b37881d9/hoshino/modules/myb_exchange/__init__.py#L153) info是？

啊这...这远古代码了我都忘了干嘛的...

**Comment by CMHopeSunshine** [comment]
> [这个应该是w in msg吧](https://github.com/CMHopeSunshine/LittlePaimon/blob/4bbc07e52fd1e38e187e5a4cc7c983738e6c6bef/hoshino/modules/Paimonchat/Paimonchat.py#L65)

嗯..也可以（

**Comment by synodriver** [comment]
感觉像是bug, 那个info则是孤零零的，上下文没定义，pycharm自动报错了……

**Comment by synodriver** [comment]
nonebot2分支的help命令无效 ……可以多加几个matcher用作help吗？

**Comment by CMHopeSunshine** [comment]
> nonebot2分支的help命令无效 ……可以多加几个matcher用作help吗？

除了几个`对联、点餐`的小功能，其他功能适配了`nonebot-plugin-help`插件，所以就没自己做help
