### ISSUE TITLE
参量质变仪时间错误

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#30]
nonebot版本
![Screenshot_2022-05-22-21-01-33-284_com mihoyo hyperion](https://user-images.githubusercontent.com/100580891/169696449-68d9e62a-c53a-43eb-9c38-5384e0d39142.png)
这是mys的显示还有13小时没问题，游戏里面显示也是这么多
![37`NA48$7LOOX46TVOCY0ZV](https://user-images.githubusercontent.com/100580891/169696474-064d3650-4439-4538-b051-96b49235c6aa.PNG)
这是机器人的，却显示可使用

**Comment by CMHopeSunshine** [comment]
这个是因为代码里按天来计算了，即将可用时间剩余不足一天的话会直接算可使用...稍候会优化一下
