### ISSUE TITLE
大大，有两个问题

### ISSUE THREAD

**Issue by ljx-code** [CMHopeSunshine/LittlePaimon#301]
1.现在使用via浏览器绑定米游社通行证ck，上午刚获取，几个小时后就过期了，明明开了无痕模式来着
2.help菜单里的别名命令还是“xx是我xx”来着，可否修正。

**Comment by CMHopeSunshine** [comment]
1.cookie这个东西是看米游社的，米游社说过期了就是过期了
2.help菜单的信息都是首次生成之后就固定的，可以删除掉`bot目录/config/plugins/Paimon_Info.yml`让它重新生成，这样就修正了

**Comment by ljx-code** [comment]
好的，大大明白了
