### ISSUE TITLE
更新失败，错误信息：Cmd('git') failed due to: exit code(128)

### ISSUE THREAD

**Issue by MotocoZg** [CMHopeSunshine/LittlePaimon#303]
更新失败，错误信息：Cmd('git') failed due to: exit code(128)
  cmdline: git pull -v origin
  stderr: 'error: Pulling is not possible because you have unmerged files.
fatal: Exiting because of an unresolved conflict.'，请手动进行更新

有什么解决手段吗。没有的话要怎么手动更新，整个bot重新下载一次么

**Comment by CMHopeSunshine** [comment]
你本地有修改过代码导致冲突，要到命令行运行git pull试试看哪些冲突了，解决冲突

**Comment by MotocoZg** [comment]
> 你本地有修改过代码导致冲突，要到命令行运行git pull试试看哪些冲突了，解决冲突

本地删过一个chat，一直复读一句话，别的没改过。git pull输出如下
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Comment by CMHopeSunshine** [comment]
试试在命令行依次运行以下三个命令
```
git stash
git pull
git stash pop
```

**Comment by MotocoZg** [comment]
PS D:\qq bot\py\Motoco\LittlePaimon> git stash
LittlePaimon/plugins/Learning_Chat/__init__.py: needs merge
LittlePaimon/plugins/Learning_Chat/config.py: needs merge
LittlePaimon/plugins/Learning_Chat/models.py: needs merge

PS D:\qq bot\py\Motoco\LittlePaimon> git pull
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

PS D:\qq bot\py\Motoco\LittlePaimon> git stash pop
LittlePaimon/plugins/Learning_Chat/__init__.py: needs merge
LittlePaimon/plugins/Learning_Chat/config.py: needs merge
LittlePaimon/plugins/Learning_Chat/models.py: needs merge
The stash entry is kept in case you need it again.

**Comment by CMHopeSunshine** [comment]
那试试
```
git add *
git commit -m "commit"
```
之后再git pull

**Comment by MotocoZg** [comment]
PS D:\qq bot\py\Motoco\LittlePaimon> git add *
PS D:\qq bot\py\Motoco\LittlePaimon> git commit -m "commit"
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'Administrator@pnldHD1004136.(none)')
PS D:\qq bot\py\Motoco\LittlePaimon> git pull
remote: Enumerating objects: 103, done.
remote: Counting objects: 100% (103/103), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 78 (delta 59), reused 65 (delta 46), pack-reused 0
Unpacking objects: 100% (78/78), 13.09 KiB | 124.00 KiB/s, done.
From https://github.com/CMHopeSunshine/LittlePaimon
   cedd736..b1c574d  Bot        -> origin/Bot
Updating cedd736..b1c574d
Fast-forward
 LittlePaimon/config/data/alias.json                |  22 +-
 LittlePaimon/config/data/genshin_info.json         |  63 +++
 LittlePaimon/config/data/roles_data.json           | 422 +++++++++++++++++++++
 LittlePaimon/config/data/score.json                |  12 +
 LittlePaimon/config/data/weapon.json               |   1 +
 LittlePaimon/plugins/Mihoyo_bbs/__init__.py        |   4 +-
 LittlePaimon/plugins/Paimon_Autobbs/__init__.py    |  18 +-
 LittlePaimon/plugins/Paimon_Autobbs/coin_handle.py |  25 +-
 LittlePaimon/plugins/Paimon_Autobbs/sign_handle.py |  32 +-
 LittlePaimon/plugins/Paimon_Gacha_Log/draw.py      |  18 +-
 LittlePaimon/plugins/Paimon_Gacha_Log/models.py    |   6 +-
 LittlePaimon/utils/alias.py                        |   6 -
 LittlePaimon/utils/brower.py                       |   8 +-
 LittlePaimon/utils/requests.py                     |   2 +-
 LittlePaimon/utils/typing.py                       |   4 +-
 README.md                                          |  32 +-
 requirements.txt                                   |  13 +-
 17 files changed, 608 insertions(+), 80 deletions(-)

**Comment by CMHopeSunshine** [comment]
这是更新好了

**Comment by MotocoZg** [comment]
运行后提示这个
制图时出错：unsupported operand type(s) for *: 'NoneType' and 'int'
是不是还是没能获取新角色的信息。

**Comment by CMHopeSunshine** [comment]
要先更新一下角色信息，`更新角色信息`

**Comment by MotocoZg** [comment]
已成功。感谢！
