### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by youyouhanshuang** [CMHopeSunshine/LittlePaimon#304]
![图片](https://user-images.githubusercontent.com/88363279/196081671-aa87a21b-f634-4787-a206-3c547fb0f6a8.png)

**Comment by youyouhanshuang** [comment]
![图片](https://user-images.githubusercontent.com/88363279/196081717-e96125aa-d9fd-40df-b1cf-c0adf4f1d813.png)

**Comment by CMHopeSunshine** [comment]
你的`.env.prod`文件中的超级用户配置不合法

**Comment by youyouhanshuang** [comment]
感谢 问题解决了 回想了一下应该是因为新开的win虚拟机没装文本编辑器 修改.env.prod的时候用的自带文本编辑器 导致编码出了问题 重新拉取一份.env.prod 使用notepad修改后就可以了
