### ISSUE TITLE
关于提示 `NoneType is not iterable` 怎么解决？

### ISSUE THREAD

**Issue by GuiltyKirito** [CMHopeSunshine/LittlePaimon#306]
![faf9e3b322b6e7a6f648a3c9456b340](https://user-images.githubusercontent.com/13746290/196095447-2ac0ccff-6c57-448c-b7f7-1fa1263d1828.jpg)

执行 `更新抽卡记录` 提示 `NoneType is not iterable`  请问会是什么原因导致的呢？刚刚pull的代码

**Comment by CMHopeSunshine** [comment]
stoken失效了，重新绑定
