### ISSUE TITLE
获取深渊或每月礼记等指令时，提示完成，但并没有发送群消息

### ISSUE THREAD

**Issue by zhulinyv** [CMHopeSunshine/LittlePaimon#309]
![image](https://user-images.githubusercontent.com/66541860/196896685-e7ede0ad-b38f-4f3d-a1ae-a4a56f57be86.png)
![image](https://user-images.githubusercontent.com/66541860/196896738-ff97d2f5-2afb-46b8-9e29-a1c01437021f.png)
如图 running complete 后，并没有发送群信息

**Comment by CMHopeSunshine** [comment]
具体是哪个指令呢

**Comment by CMHopeSunshine** [comment]
可以看看gocq那边的日志输出结果

**Comment by zhulinyv** [comment]
> 

![image](https://user-images.githubusercontent.com/66541860/196899954-ea2a4a05-8b2f-4de3-8c21-faae47128cf1.png)

**Comment by zhulinyv** [comment]
> 具体是哪个指令呢

myzj
sy
ssbq

**Comment by CMHopeSunshine** [comment]
奇怪...在`.env.prod`文件中将`INFO`改成`DEBUG`，重启一下试试

**Comment by zhulinyv** [comment]
> 奇怪...在`.env.prod`文件中将`INFO`改成`DEBUG`，重启一下试试

![image](https://user-images.githubusercontent.com/66541860/196902389-69c9eccc-b2bc-49b2-a9f1-1dd3e4163eb3.png)
提示以上信息，但问题依旧。。。

**Comment by CMHopeSunshine** [comment]
请问nonebot版本是多少，日志和我的日志有些许出入

**Comment by zhulinyv** [comment]
> 请问nonebot版本是多少，日志和我的日志有些许出入

2.0.0rc1

**Comment by CMHopeSunshine** [comment]
~~似乎`myzj_handler`没有正确运行依赖注入，被跳过了处理，请问是否有修改过代码，能截一下`LittlePaimon\plugins\Paimon_MonthInfo\__init__.py`文件看看嘛~~ ，已找到原因，是rc1版本变动，请先暂时回退beta5版本吧，稍候修复

**Comment by zhulinyv** [comment]
> 

了解了，谢谢( •̀ ω •́ )✧
