### ISSUE TITLE
nonebot版本无法触发派蒙语音

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#31]
无论我怎么发都不会给我回语音，后台也没有任何反馈，这个有概率概率是多高呢
![image](https://user-images.githubusercontent.com/100580891/169750464-798c28e8-4ed0-4eb5-96b8-d0e12d44f26f.png)
执行更新派蒙语音没问题
![image](https://user-images.githubusercontent.com/100580891/169750496-c5f57057-8b33-4cc7-9f4c-09058d1c248c.png)
ffmpeg没问题，角色的语音能发送

**Comment by CMHopeSunshine** [comment]
因为有人嫌烦，所以改成了默认关闭的，需要在开启的.env.*文件里配置paimon_chat_group=[开启的群号]

**Comment by forchannot** [comment]
> 

OK
