### ISSUE TITLE
机器人不回复

### ISSUE THREAD

**Issue by HTTE-lx** [CMHopeSunshine/LittlePaimon#311]
跟教程安装完之后私聊机器人不回复
![image](https://user-images.githubusercontent.com/65992830/197378219-9c77ff4d-cc51-48e4-8336-f17fa7d7b785.png)

**Comment by HTTE-lx** [comment]
启动过程中有一个报错：
ModuleNotFoundError: No module named 'tortoise'

**Comment by HTTE-lx** [comment]
启动过程中（执行poetry run nb run后）报的错误： 
[ERROR] nonebot | Failed to import "nonebot_plugin_apscheduler"
ModuleNotFoundError: No module named 'nonebot_plugin_apscheduler'
 [ERROR] nonebot | Failed to import "nonebot_plugin_myb_exchange"
RuntimeError: Cannot load plugin "nonebot_plugin_apscheduler"!
[ERROR] nonebot | Failed to import "LittlePaimon"
ModuleNotFoundError: No module named 'tortoise'

**Comment by forchannot** [comment]
自己先poetry install检查下依赖安装完没有

**Comment by HTTE-lx** [comment]
> 自己先poetry install检查下依赖安装完没有

![image](https://user-images.githubusercontent.com/65992830/197378920-537ea0c0-61e5-4b18-ace4-735df362cbb4.png)
我使用这个指令会报错，所以我用的poetry run pip install -r requirements.txt安装依赖

**Comment by forchannot** [comment]
> > 自己先poetry install检查下依赖安装完没有
> 
> ![image](https://user-images.githubusercontent.com/65992830/197378920-537ea0c0-61e5-4b18-ace4-735df362cbb4.png) 我使用这个指令会报错，所以我用的poetry run pip install -r requirements.txt安装依赖

这个的依赖不全

**Comment by HTTE-lx** [comment]
> > > 自己先poetry install检查下依赖安装完没有
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/65992830/197378920-537ea0c0-61e5-4b18-ace4-735df362cbb4.png) 我使用这个指令会报错，所以我用的poetry run pip install -r requirements.txt安装依赖
> 
> 这个的依赖不全

那。。那怎么办

**Comment by forchannot** [comment]
提示你缺啥补啥，https://github.com/CMHopeSunshine/LittlePaimon/issues/310

**Comment by HTTE-lx** [comment]
执行
poetry run pip install nonebot_plugin_apscheduler
poetry run pip install nonebot_plugin_myb_exchange
poetry run pip install LittlePaimon
poetry run pip install tortoise
四条语句后还是提示缺少这几个插件

**Comment by CMHopeSunshine** [comment]
```
poetry run pip install tortoise-orm
poetry run pip install nonebot_plugin_apscheduler==0.2.0
```

**Comment by HTTE-lx** [comment]
> ```
> poetry run pip install tortoise-orm
> poetry run pip install nonebot_plugin_apscheduler==0.2.0
> ```
现在还是会报这两个错误：

 [ERROR] nonebot | Failed to import "LittlePaimon"

ModuleNotFoundError: No module named 'tortoise'

**Comment by CMHopeSunshine** [comment]
把之前装错的tortoise卸载掉：
```
poetry run pip uninstall tortoise
poetry run pip install tortoise-orm
```

**Comment by HTTE-lx** [comment]
还是会报这俩错误......

**Comment by CMHopeSunshine** [comment]
那估计环境是搞乱了，建议把现在的虚拟环境删掉重新装

**Comment by HTTE-lx** [comment]
python，poetry，git和ffmpeg全部重装吗？

**Comment by CMHopeSunshine** [comment]
> > 自己先poetry install检查下依赖安装完没有
> 
> ![image](https://user-images.githubusercontent.com/65992830/197378920-537ea0c0-61e5-4b18-ace4-735df362cbb4.png) 我使用这个指令会报错，所以我用的poetry run pip install -r requirements.txt安装依赖

看这个，感觉你的python不完整，重装一下python

**Comment by CMHopeSunshine** [comment]
> python，poetry，git和ffmpeg全部重装吗？

git和ffmpeg不用

**Comment by HTTE-lx** [comment]
好的我现在就卸载重装

**Comment by HTTE-lx** [comment]
![image](https://user-images.githubusercontent.com/65992830/197381426-358dbb28-f148-48be-910a-1c07278116ca.png)
我重新安装了python3.9.10和python3.10.8并都在cmd中使用“pip install poetry”安装了poetry，两个版本执行poetry install都会报错

**Comment by forchannot** [comment]
你用的好像是git bash吧，换成powershell试试。
如果还是这样的话建议用miniconda搭配全局的poetry，去poetry官网找全局安装命令，不使用pip安装poetry，随后用poetry config virtualenvs.create false关闭poetry创建虚拟环境使用conda来管理虚拟环境避免冲突
我自己写了篇教程，虽然是ubuntu的，但是windwos流程基本是一样的，只是命令和安装方法不同https://github.com/forchannot/selfmarkdown/blob/main/ubuntu安装LittlePaimon.md
