### ISSUE TITLE
超级用户失效

### ISSUE THREAD

**Issue by 1103859909** [CMHopeSunshine/LittlePaimon#312]
![image](https://user-images.githubusercontent.com/107859647/197379853-a102f4a5-769e-4220-97fb-3761ad041e4c.png)
![image](https://user-images.githubusercontent.com/107859647/197379878-27928cd2-282e-42db-b64e-6867aced43e0.png)

**Comment by 1103859909** [comment]
![image](https://user-images.githubusercontent.com/107859647/197379909-0ca22a38-67b0-4b62-aa34-1ce62ac898b3.png)

**Comment by CMHopeSunshine** [comment]
重启试试

**Comment by 1103859909** [comment]
没用

**Comment by CMHopeSunshine** [comment]
看下日志

**Comment by 1103859909** [comment]
![I 0%UAAOTMR~2F~$ ~R}B9J](https://user-images.githubusercontent.com/107859647/197526013-8fd15073-46d5-4caa-a4b0-6e979faaf6d3.png)

**Comment by CMHopeSunshine** [comment]
那就奇怪了，`.env`的environment写的是`prod`吗

**Comment by 1103859909** [comment]
是的
