### ISSUE TITLE
检查资源报错

### ISSUE THREAD

**Issue by youyouhanshuang** [CMHopeSunshine/LittlePaimon#318]
原目录停止一次服务,再开启的时候出现这个报错 后再也没开启过 
换了一个目录重新clone了一个最新版的启动也是这个报错
![屏幕截图 2022-10-31 130416](https://user-images.githubusercontent.com/88363279/198935968-b58ecede-5498-42d9-b657-985d09808206.jpg)
![屏幕截图 2022-10-31 130826](https://user-images.githubusercontent.com/88363279/198935971-5b4111a4-4a6b-4b39-a9da-45cd49b21db8.jpg)

**Comment by youyouhanshuang** [comment]
git下来的时候用了代理 ,运行服务的时候开代理和不开代理都会出现类似错误 
accounts目录下的log文件
![屏幕截图 2022-10-31 131424](https://user-images.githubusercontent.com/88363279/198936160-9ffd7814-f060-4ada-b3a1-0db842189945.jpg)

**Comment by CMHopeSunshine** [comment]
把accounts文件夹删了，彻底重启一下服务器，再等账号试试
