### ISSUE TITLE
nonebot2部分的源码克隆错误

### ISSUE THREAD

**Issue by TGLDZA** [CMHopeSunshine/LittlePaimon#32]
在windows上部署小派蒙的时候克隆nonebot2的源码总是说找不到路径，求大佬指个明路

**Comment by CMHopeSunshine** [comment]
有没有报错信息

**Comment by CMHopeSunshine** [comment]
是啊，`git clone https://github.com/CMHopeSunshine/LittlePaimon.git`

**Comment by TGLDZA** [comment]
错误信息是这个：
Cloning into 'LittlePaimon'...
fatal: unable to access 'https://github.com/CMHopeSunshine/LittlePaimon.git/': SSL certificate problem: unable to get local issuer certificate




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月24日(星期二) 晚上8:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CMHopeSunshine/LittlePaimon] nonebot2部分的源码克隆错误 (Issue #32)





 
是啊，git clone https://github.com/CMHopeSunshine/LittlePaimon.git

**Comment by CMHopeSunshine** [comment]
来自百度：
> 这个问题是由于没有配置信任的服务器HTTPS验证。默认，cURL被设为不信任任何CAs，就是说，它不信任任何服务器验证。
在网上查了很多方法，最终使用如下方法解决的
只需要执行下面命令就可以解决：
`git config --global http.sslVerify false`

**Comment by TGLDZA** [comment]
好了，克隆好了，谢谢大佬
另外问一下配置nonebot2时的那个bash可以直接用powershell执行嘛




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月24日(星期二) 晚上9:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CMHopeSunshine/LittlePaimon] nonebot2部分的源码克隆错误 (Issue #32)





 
来自百度：
  
这个问题是由于没有配置信任的服务器HTTPS验证。默认，cURL被设为不信任任何CAs，就是说，它不信任任何服务器验证。
 在网上查了很多方法，最终使用如下方法解决的
 只需要执行下面命令就可以解决：
 git config --global http.sslVerify false
