### ISSUE TITLE
模拟抽卡出错

### ISSUE THREAD

**Issue by Cvandia** [CMHopeSunshine/LittlePaimon#320]
![image](https://user-images.githubusercontent.com/106718176/199216333-09824650-0bf2-43d6-b45d-5cf1ab2bb005.png)
提示：list index out of range

**Comment by CMHopeSunshine** [comment]
因为官方卡池已经关闭了，明天卡池开放就正常了

**Comment by soulrewrite** [comment]
模拟抽卡还跟紧版本 T T 提前体验都不行
![image](https://user-images.githubusercontent.com/105762209/199380065-5b1fd8ec-78fd-46cd-a268-75d3578c9d89.png)
