### ISSUE TITLE
使用gocqhttp出错

### ISSUE THREAD

**Issue by youyouhanshuang** [CMHopeSunshine/LittlePaimon#321]
执行poetry run nb plugin install nonebot-plugin-gocqhttp后运行小派蒙
remove nonebot-plugin-gocqhttp后又可以正常启动 但是没有它又绑定不了
![图片](https://user-images.githubusercontent.com/88363279/199233802-cdc1e55b-0f89-4190-91ca-e4034bcb5f53.png)

**Comment by youyouhanshuang** [comment]
环境在阿里云下,centos8

**Comment by CMHopeSunshine** [comment]
gocq插件用的镜像地址有问题，建议自行下载独立gocq来使用，如有后续问题请向该插件仓库反馈：https://github.com/mnixry/nonebot-plugin-gocqhttp
