### ISSUE TITLE
添加权限验证

### ISSUE THREAD

**Issue by youyouhanshuang** [CMHopeSunshine/LittlePaimon#322]
可否将:13579/go-cqhttp/合并在管理后台内 或者有什么办法可以对这个页面添加一个鉴权吗 这个后台暴露在公网上貌似也不是很安全

**Comment by CMHopeSunshine** [comment]
gocq插件本来也能设置身份验证，详见https://github.com/mnixry/nonebot-plugin-gocqhttp#%E5%85%B6%E4%BB%96%E9%85%8D%E7%BD%AE
