### ISSUE TITLE
websocket连接错误

### ISSUE THREAD

**Issue by youyouhanshuang** [CMHopeSunshine/LittlePaimon#326]
更新版本后 让小派蒙重启后出现
管理后台not found
功能无法正常使用
![图片](https://user-images.githubusercontent.com/88363279/201594351-ea401536-012e-4e44-bbcf-732dd2cfafbd.png)
![图片](https://user-images.githubusercontent.com/88363279/201594414-f287f3e0-48b4-49df-b804-7cd94d11ce46.png)

**Comment by CMHopeSunshine** [comment]
`poetry run pip install amis-python --upgrade`后重启

**Comment by youyouhanshuang** [comment]
在这里停住了 管理后台出现了 但是密码被重置回admin  群里消息也无响应

![图片](https://user-images.githubusercontent.com/88363279/201601709-7a190e22-c7d6-4d53-8251-89ac961619c6.png)

**Comment by CMHopeSunshine** [comment]
这个和上面截图的那个不是同一个bot吧，我发的这条命令只是升级了一个库，不会对你的配置和gocq进行任何操作

**Comment by youyouhanshuang** [comment]
恢复正常了 是同一个bot  之前尝试回退了上一个版本 就导致之前gocq的配置消失了

**Comment by youyouhanshuang** [comment]
重新执行了一下安装gocp 再运行bot就会带起gocq了
