### ISSUE TITLE
大大有两个问题

### ISSUE THREAD

**Issue by ljx-code** [CMHopeSunshine/LittlePaimon#327]
1.在已经绑定cookie的情况下,使用米游币的米游币商品自动兑换插件依旧提示需要米游币cookie...
2.myzj功能好像出了问题，在cookie有效的时候发送myzj，然后cookie就失效了...

**Comment by CMHopeSunshine** [comment]
米游币兑换插件是个独立的插件，不使用派蒙内置的数据库，札记失效是缺字段，要米游社退出重新登录获取ck，不过即使这样还是有可能看不了，不明原因。

**Comment by ljx-code** [comment]
> 米游币兑换插件是个独立的插件，不使用派蒙内置的数据库，札记失效是缺字段，要米游社退出重新登录获取ck，不过即使这样还是有可能看不了，不明原因。

按照cookie的获取方法再次获取cookie小派蒙依旧提示“请把米游币cookie给我，cookie获取方式详见：
docs.qq.com/doc/DQ3JLWk1vQVllZ2Z1”....

**Comment by ljx-code** [comment]
> 米游币兑换插件是个独立的插件，不使用派蒙内置的数据库，札记失效是缺字段，要米游社退出重新登录获取ck，不过即使这样还是有可能看不了，不明原因。

按照cookie获取文档获取cookie，小派蒙依旧提示“这个cookie无效，请检查是否以按照正常方法获取”....

**Comment by CMHopeSunshine** [comment]
米游社接口返回说的失效

**Comment by ljx-code** [comment]
> 米游社接口返回说的失效

同样的cookie，我使用ysb指令绑定小派蒙提示“成功绑定cookieXXXXXX，开始愉快地享用派蒙吧！”
