### ISSUE TITLE
TypeError: Subscripted generics cannot be used...报错

### ISSUE THREAD

**Issue by HorizonWHY** [CMHopeSunshine/LittlePaimon#33]
go-cqhttp 启动时会有一个 error：[ERROR]: Protocol -> get self guild profile error: decode packet error: oidb result unsuccessful: 36012 msg: no guild tab

nb run 之后第一次会显示 [ERROR] utils | ---派蒙初始化数据库失败，请检查user_cookies.json文件是否存在---
调用抽卡功能会出现报错：[ERROR] nonebot | Running matcher <Matcher from LittlePaimon.Paimon_Gacha, type=message, priority=5, temp=False> failed.

**Comment by CMHopeSunshine** [comment]
gocq的问题去gocq仓库那看看，我也不知道，
初始化数据库失败可以不管，
抽卡功能有无详细报错提示，单这一条handle failed看不出什么来

**Comment by HorizonWHY** [comment]
附件有调用抽卡功能时候的报错截图，现在还出现了一个错误：派蒙好像出了点问题，'NoneType'&nbsp;object&nbsp;has&nbsp;no&nbsp;attribute&nbsp;'size'


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CMHopeSunshine/LittlePaimon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月25日(星期三) 凌晨1:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CMHopeSunshine/LittlePaimon] 使用中的部分问题 (Issue #33)





 
gocq的问题去gocq仓库那看看，我也不知道，
 初始化数据库失败可以不管，
 抽卡功能有无详细报错提示，单这一条handle failed看不出什么来

**Comment by HorizonWHY** [comment]
![123](https://user-images.githubusercontent.com/41848992/170100872-a31cffea-296e-4162-94ea-9b2ab054320d.png)

**Comment by HorizonWHY** [comment]
似乎是 nonebot 方面的bug，可以看看这个 https://github.com/nonebot/nonebot2/issues/998

**Comment by CMHopeSunshine** [comment]
有关这个问题的，目前解决方案是nonebot2降级beta2及以下或升级到Python3.10，等nb官方更新修复
