### ISSUE TITLE
流量转发问题

### ISSUE THREAD

**Issue by youyouhanshuang** [CMHopeSunshine/LittlePaimon#330]
因为配置依赖等问题 我把小派蒙装在一台国外服务器上,但是可能因为这样导致签到经常失败
如果我想将流量转发到国内的服务上 想问下可以添加个代理功能吗

**Comment by zuixiaoxiao** [comment]
> 因为配置依赖等问题 我把小派蒙装在一台国外服务器上,但是可能因为这样导致签到经常失败 如果我想将流量转发到国内的服务上 想问下可以添加个代理功能吗

签到现在是看脸，老米给签到加了验证码，小派蒙只能过滑块的，对图案和文字没办法，所以经常失败
