### ISSUE TITLE
抽卡记录较多时4星部分绘制不全

### ISSUE THREAD

**Issue by lxy7065809** [CMHopeSunshine/LittlePaimon#333]
在使用 抽卡记录 功能时，记录较多会导致4星部分绘制不全。
看起来像是有总高度限制，边框高度是正确的但内容没有绘制完整，如图所示
![1](https://user-images.githubusercontent.com/20908419/203234416-21043702-cec5-4d43-8594-aec22cbd2851.jpg)
![2](https://user-images.githubusercontent.com/20908419/203234439-e267981a-2c3a-4760-a9c1-971636bac98b.jpg)

**Comment by CMHopeSunshine** [comment]
可以更新后试试，不知道够不够长😥

**Comment by lxy7065809** [comment]
问题解决了~多谢多谢
