### ISSUE TITLE
60秒读世界疑似接口无反应

### ISSUE THREAD

**Issue by Cvandia** [CMHopeSunshine/LittlePaimon#335]
![image](https://user-images.githubusercontent.com/106718176/205272186-34270a96-706e-442c-bc66-04882030f2cf.png)

**Comment by zhulinyv** [comment]
新的 API `https://api.vvhan.com/api/60s`。
接口来自 [韩小韩](https://api.vvhan.com/) ，不确定以后会不会寄。

**Comment by CMHopeSunshine** [comment]
a4cb84e1df0d1552ef96d31f320e74bb58c8b15f
