### ISSUE TITLE
bot启动时报错

### ISSUE THREAD

**Issue by MotocoZg** [CMHopeSunshine/LittlePaimon#336]
![B0K(IGA _SQUWBS0{SEL%C1](https://user-images.githubusercontent.com/111079540/205424541-7c4d471e-99cb-49ba-bb92-e52194907f14.png)

**Comment by CMHopeSunshine** [comment]
感觉是偶现的网络问题，再启动一下试试？

**Comment by MotocoZg** [comment]
多次启动均出现相同报错...重新启动电脑后恢复正常...奇怪..
