### ISSUE TITLE
网络正常的情况下，资源下载失败

### ISSUE THREAD

**Issue by aqiMMM** [CMHopeSunshine/LittlePaimon#341]
![image](https://user-images.githubusercontent.com/29270606/206338037-a8463155-5175-4a0d-924d-f56f33c79af9.png)
一直下载失败，用日志把url输出后去访问，URL是可以访问到的
![image](https://user-images.githubusercontent.com/29270606/206338158-ac9aef28-bd60-4470-a0f5-4fbababf6021.png)
也可以用wget下载下来
![image](https://user-images.githubusercontent.com/29270606/206338302-fbb7b800-bcbd-4e36-a690-e61076845634.png)

**Comment by yangy666** [comment]
12-08 11:29:51 [INFO] LittlePaimon | [原神实时便签]开始执行查询
12-08 11:29:51 [INFO] LittlePaimon | [原神实时便签]➤用户1414**** UID11***021获取数据成功
12-08 11:29:53 [INFO] LittlePaimon | [资源检查]图标资源UI_AvatarIcon_Side_Sucrose.png下载失败
12-08 11:29:53 [INFO] LittlePaimon | [资源检查]图标资源UI_AvatarIcon_Side_Chongyun.png下载失败
12-08 11:29:53 [INFO] LittlePaimon | [资源检查]图标资源UI_AvatarIcon_Side_Bennett.png下载失败
12-08 11:29:53 [INFO] LittlePaimon | [资源检查]图标资源UI_AvatarIcon_Side_Fischl.png下载失败
12-08 11:29:54 [INFO] LittlePaimon | [资源检查]图标资源UI_AvatarIcon_Side_Keqing.png下载失败
12-08 11:29:54 [INFO] LittlePaimon | [原神实时便签]➤➤用户ssd*** UID11***1绘制图片成功
12-08 11:29:55 [INFO] nonebot | Matcher(type='message', module=LittlePaimon.plugins.Paimon_DailyNote) running complete

**Comment by CMHopeSunshine** [comment]
已修复，更新后试试 1b625dcdeff49f6c67dab64d169658ad8e5831ab
