### ISSUE TITLE
启动报错了，大佬

### ISSUE THREAD

**Issue by dengma0** [CMHopeSunshine/LittlePaimon#343]
playwright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
<launching> /root/.cache/ms-playwright/chromium-1028/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-o2Gj16 --remote-debugging-pipe --no-startup-window
<launched> pid=7110
[pid=7110][err] /root/.cache/ms-playwright/chromium-1028/chrome-linux/chrome: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /root/.cache/ms-playwright/chromium-1028/chrome-linux/chrome)
[pid=7110][err] /root/.cache/ms-playwright/chromium-1028/chrome-linux/chrome: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /root/.cache/ms-playwright/chromium-1028/chrome-linux/chrome)
=========================== logs ===========================
<launching> /root/.cache/ms-playwright/chromium-1028/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-o2Gj16 --remote-debugging-pipe --no-startup-window
<launched> pid=7110
[pid=7110][err] /root/.cache/ms-playwright/chromium-1028/chrome-linux/chrome: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /root/.cache/ms-playwright/chromium-1028/chrome-linux/chrome)
[pid=7110][err] /root/.cache/ms-playwright/chromium-1028/chrome-linux/chrome: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /root/.cache/ms-playwright/chromium-1028/chrome-linux/chrome)
============================================================

**Comment by CMHopeSunshine** [comment]
系统缺库，参考https://www.codenong.com/cs110277422/
