### ISSUE TITLE
深渊战报，抽卡记录绘图出错怎么解决

### ISSUE THREAD

**Issue by YouYouLip** [CMHopeSunshine/LittlePaimon#346]
求大佬解决办法 我用的是python3.10.8版本 依赖已都安装，imageutils也载入了 但是会显示绘图失败
![HHJ0S8K9SL8MQH9APE2H67C](https://user-images.githubusercontent.com/119958263/206906718-00b1d828-f928-4c63-aa05-e24488d6ca99.png)

12-11 21:12:12 [INFO] LittlePaimon | [原神深渊战报]➤➤数据获取成功
12-11 21:12:12 [INFO] LittlePaimon | [原神深渊战报]➤➤➤制图出错:cannot identify image file 'E:\\Nonebot2\\LittlePaimon\\resources\\LittlePaimon\\general\\line.png'
12-11 21:12:12 [INFO] nonebot | Matcher(type='message', module=LittlePaimon.plugins.Paimon_Abyss) running complete

**Comment by CMHopeSunshine** [comment]
对应的这个图片文件疑似损坏，把这个文件删掉让bot重新下载吧

**Comment by YouYouLip** [comment]
> 对应的这个图片文件疑似损坏，把这个文件删掉让bot重新下载吧

感谢大佬 貌似雀食是文件损坏 我通过github仓库重新安装了一个新的 一开始显示不存在字体文件 重启bot后就可以制图出来了 我现在尝试把图片文件移到损坏的里面的 问题可以解决 打不了就是插件重新安装~ 感谢大佬
