### ISSUE TITLE
有docker的搭建方向吗？

### ISSUE THREAD

**Issue by yiyule10** [CMHopeSunshine/LittlePaimon#347]
比较想用一下docker搭建，不会影响到系统的原本环境。
所以来问一下，有没有这方面的教程和支持。

**Comment by leafqycc** [comment]
> 比较想用一下docker搭建，不会影响到系统的原本环境。
> 所以来问一下，有没有这方面的教程和支持。

FROM ubuntu
RUN sed -i 's#http://archive.ubuntu.com/#http://mirrors.tuna.tsinghua.edu.cn/#' /etc/apt/sources.list \
        && apt update \
        && apt -y upgrade \
        && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
        && apt -y install git python3 python3-pip tzdata \
        && pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple \
        && pip install poetry \
        && cd /root \
        && git init \
        && git clone --depth=1 https://github.com/CMHopeSunshine/LittlePaimon \
        && cd LittlePaimon \
        && sed -i '4c SUPERUSERS=["123456"] #修改123456为你bot管理者的qq号' .env.prod \
        && poetry install \
        && poetry run nb plugin install nonebot-plugin-gocqhttp \

**Comment by leafqycc** [comment]
> > 比较想用一下docker搭建，不会影响到系统的原本环境。
> > 所以来问一下，有没有这方面的教程和支持。
> 
> FROM ubuntu
> RUN sed -i 's#http://archive.ubuntu.com/#http://mirrors.tuna.tsinghua.edu.cn/#' /etc/apt/sources.list \
>         && apt update \
>         && apt -y upgrade \
>         && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
>         && apt -y install git python3 python3-pip tzdata \
>         && pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple \
>         && pip install poetry \
>         && cd /root \
>         && git init \
>         && git clone --depth=1 https://github.com/CMHopeSunshine/LittlePaimon \
>         && cd LittlePaimon \
>         && sed -i '4c SUPERUSERS=["123456"] #修改123456为你bot管理者的qq号' .env.prod \
>         && poetry install \
>         && poetry run nb plugin install nonebot-plugin-gocqhttp \

进入容器后:
cd /root/LittlePaimon
poetry run nb run
等待剩下的依赖安装然后ctrl+c退出一次再输入
poetry run nb run
等待图文资源下载后就可以直接使用了
剩下的看文档吧()

**Comment by leafqycc** [comment]
> 比较想用一下docker搭建，不会影响到系统的原本环境。
> 所以来问一下，有没有这方面的教程和支持。

或者明天我再把镜像传到云上)

**Comment by yiyule10** [comment]
> > 比较想用一下docker搭建，不会影响到系统的原本环境。
> > 所以来问一下，有没有这方面的教程和支持。
> 
> 或者明天我再把镜像传到云上)

感谢您的答复，我选择等明天，在软路由上面直接拉取镜像比较方便

**Comment by leafqycc** [comment]
> > > 比较想用一下docker搭建，不会影响到系统的原本环境。
> > > 所以来问一下，有没有这方面的教程和支持。
> > 
> > 或者明天我再把镜像传到云上)
> 
> 感谢您的答复，我选择等明天，在软路由上面直接拉取镜像比较方便


教程(镜像链接也在里面):
https://qun.qq.com/qqweb/qunpro/share?_wv=3&_wwv=128&appChannel=share&inviteCode=1XKMkeAxGXt&contentID=bT2qY&businessType=2&from=181074&biz=ka&mainSourceId=share&subSourceId=others&jumpsource=shorturl

**Comment by Mmx233** [comment]
我可以提个 pr 把 dockerfile 写进项目再加个 ci 吗。我已经离了集群活不了了

**Comment by CMHopeSunshine** [comment]
可以的，十分欢迎和感谢！

**Comment by CMHopeSunshine** [comment]
docker镜像已上传至https://hub.docker.com/repository/docker/cherishmoon/littlepaimon
