### ISSUE TITLE
关于材料图标缺失以及原魔图鉴版本

### ISSUE THREAD

**Issue by YouYouLip** [CMHopeSunshine/LittlePaimon#349]
![MKRYJ0%HPPPK8{ 3TW`WH{Q](https://user-images.githubusercontent.com/119958263/208023554-f658df9d-977a-4c00-b39b-2dd969aa1863.png)

我的材料天赋图标会正常显示 但是突破材料不会显示也是缺少图像么... 但是我观察了一下 在我没有这些本地文件的时候触发材料指令是自行下载的 但是我并没有看见突破材料的图像在下载中  还有就是原魔图鉴没有散兵 掣电树 无相之草和鸡哥这些须弥怪物图鉴 但是有须弥地图 深渊配队也目前在3.2 
会考虑更新一下么

**Comment by CMHopeSunshine** [comment]
深渊配队和图标问题已修 72dbeb79cfd0a0bce943e95fd62485dd7e00e3c0 ，原魔图鉴现在暂时没有时间做，请谅解

**Comment by YouYouLip** [comment]
> 深渊配队和图标问题已修 [72dbeb7](https://github.com/CMHopeSunshine/LittlePaimon/commit/72dbeb79cfd0a0bce943e95fd62485dd7e00e3c0) ，原魔图鉴现在暂时没有时间做，请谅解

感谢修复 覆盖过去已经可以显示武器突破材料以及深渊配队3.3的了 原魔图鉴其实也不是一个很要紧的  只是很好奇须弥地图有了为什么须弥怪图鉴没有  我还以为我版本不对呢哈哈哈...

**Comment by CMHopeSunshine** [comment]
> > 深渊配队和图标问题已修 [72dbeb7](https://github.com/CMHopeSunshine/LittlePaimon/commit/72dbeb79cfd0a0bce943e95fd62485dd7e00e3c0) ，原魔图鉴现在暂时没有时间做，请谅解
> 
> 感谢修复 覆盖过去已经可以显示武器突破材料以及深渊配队3.3的了 原魔图鉴其实也不是一个很要紧的 只是很好奇须弥地图有了为什么须弥怪图鉴没有 我还以为我版本不对呢哈哈哈...

和美工大大沟通了，近期会翻新一下原魔图鉴

**Comment by YouYouLip** [comment]
> > > 深渊配队和图标问题已修 [72dbeb7](https://github.com/CMHopeSunshine/LittlePaimon/commit/72dbeb79cfd0a0bce943e95fd62485dd7e00e3c0) ，原魔图鉴现在暂时没有时间做，请谅解
> > 
> > 
> > 感谢修复 覆盖过去已经可以显示武器突破材料以及深渊配队3.3的了 原魔图鉴其实也不是一个很要紧的 只是很好奇须弥地图有了为什么须弥怪图鉴没有 我还以为我版本不对呢哈哈哈...
> 
> 和美工大大沟通了，近期会翻新一下原魔图鉴

哇哦 那挺期待的 说到这个我就想到了七圣召唤那个卡牌图鉴 吐槽一下 有种三国杀的感觉（doge）

主要是我一开始没这么感觉 我朋友直接说“这什么 三国杀么？”我突然看着也好像 我感觉可以把天赋牌还有 特殊产物合进一张图里 这样也方便直接查看 而不是先去看角色图鉴 再去看天赋牌图鉴
![QQ图片20221216205145](https://user-images.githubusercontent.com/119958263/208102104-19f36139-ec2b-46df-ada4-3c89b97417e9.png)
