### ISSUE TITLE
更新之后就这样了，开始检查资源就报错，ctrl+c还没反应卡死

### ISSUE THREAD

**Issue by Mr233sir** [CMHopeSunshine/LittlePaimon#353]
![QQ图片20221223102428](https://user-images.githubusercontent.com/30330282/209259207-775194c4-08c7-48b8-88cf-daa54fda72c8.png)

**Comment by CMHopeSunshine** [comment]
你这并不是最新版本，看代码还是3周前

**Comment by Mr233sir** [comment]
> 你这并不是最新版本，看代码还是3周前

好吧我用了git pull之后就这样了，原来是没更新上
