### ISSUE TITLE
材料地图功能命令被材料图鉴占用

### ISSUE THREAD

**Issue by lingyu-or2** [CMHopeSunshine/LittlePaimon#354]
![1 YQ~P@ 4MAA9YKR1A%V%2WE](https://user-images.githubusercontent.com/78100656/209438162-e3d9198a-e4ba-45f3-a9eb-8a8207035a1f.png)
![$DH 3LU}UAG%X1}9J57~POI](https://user-images.githubusercontent.com/78100656/209438164-4abc185c-5975-425f-bf53-63bf455ab4a6.png)

**Comment by CMHopeSunshine** [comment]
已修 ccbe26e5deab1cfd3d03bb69dcd61e523fc866d1
