### ISSUE TITLE
开启了CookieWeb之后，服务器的地址会暴露出来，是否存在安全隐患

### ISSUE THREAD

**Issue by qq237465059** [CMHopeSunshine/LittlePaimon#357]
开启了CookieWeb之后，服务器的地址会暴露出来，是否存在安全隐患，如果通过该端口对服务器进行攻击，或者代码在某种情况下出现漏洞，是否会导致服务器变成肉鸡或者数据泄露，这方面是否也需要考虑一下

**Comment by CMHopeSunshine** [comment]
开不开是由你决定的，你觉得不安全可以不开，而且并不是说在机器人里开启了CookieWeb之后就马上暴露出来，你还得自己开放防火墙和端口，别人才能外部访问，安全这方面是由你自己来做的，例如使用反向代理服务器，买高防、套域名等，机器人只是通过fastapi提供了一个web程序而已。
