### ISSUE TITLE
[问题]已使用poetry install，仍无法加载扫码绑定

### ISSUE THREAD

**Issue by Mr233sir** [CMHopeSunshine/LittlePaimon#364]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`poetry install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows10
- Python版本: 3.8.6
- Nonebot2版本: 2.0.0rc2

### 问题描述

已使用poetry install，仍无法加载扫码绑定，在此之前也用过poetry update，可以直接poetry run pip install安装对应依赖吗，如果可以的话这个依赖名字是什么，我这看不到

### 问题截图

![QQ图片20230111140144](https://user-images.githubusercontent.com/30330282/211732262-29860e4e-ccf2-48db-a98f-c486f5550cec.png)

### 复现步骤[可选]

git stash
git pull
把env.prod和pyproject.toml备份复制回去
poetry update
poetry install
poetry run nb run

**Comment by CMHopeSunshine** [comment]
`poetry run pip install qrcode`

**Comment by Mr233sir** [comment]
> `poetry run pip install qrcode`

谢谢大佬，解决了

**Comment by CMHopeSunshine** [comment]
其实日志里写了，只不过powershell的配色导致看不清）`请检查是否已安装qrcode库`，qrcode的文字颜色应该是品红色的，到powershell里就离奇的变成蓝色
