### ISSUE TITLE
[建议]作者大佬能否将角色攻略的后台查询方式回退

### ISSUE THREAD

**Issue by huahuahuage** [CMHopeSunshine/LittlePaimon#365]
### 当前不足

我目前更新了最新版本的小派蒙。
之前版本的角色攻略是可以查询的，更新后就查询不了了，估计是更改了查询的方式。
因为国内网络的原因，小派蒙查询不出东西了。后台报错

- 报错信息：
换CQ码 ({"type": "image", "data": {"file": "https://github.cherishmoon.fun/https://raw.githubusercontent.com/CMHopeSunshine/LittlePaimonRes/main/genshin_guide/guide/\u8352\u6cf7\u4e00\u6597.jpg", "type": null, "cache": "true", "proxy": "true", "timeout": null}}) 到MiraiGo Element时出现错误: Get "https://github.cherishmoon.fun/https://raw.githubusercontent.com/CMHopeSunshine/LittlePaimonRes/main/genshin_guide/guide/%E8%8D%92%E6%B3%B7%E4%B8%80%E6%96%97.jpg": read tcp 192.168.124.16:46134->104.21.93.194:443: read: connection reset by peer 将忽略本段CQ码.

- 以及派蒙刚启动时无法获取github资源：
[INFO] LittlePaimon | [资源检查]读取资源列表失败，请尝试更换github资源地址

### 建议内容

作者大大是否能够将原来的资源查询方式加入下个新版本，依据网络情况进行选择哪种查询方式。

谢谢！

**Comment by CMHopeSunshine** [comment]
原来的对象存储已不再使用，现在是使用github+代理的方式，暂时不会考虑回退，试试更换资源地址，关闭系统全局代理
