### ISSUE TITLE
[问题]重启后机器人群名片没有更改

### ISSUE THREAD

**Issue by Tosd0** [CMHopeSunshine/LittlePaimon#371]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`poetry install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows10
- Python版本: 3.10
- Nonebot2版本: 2.0.0rc2

### 问题描述

通过@机器人 重启 的方式重启机器人，重启后，所有机器人在群里的头衔后的（重启中）都没有消失。甚至达到了两个（重启中）之多（我重启了两次，以为能消除掉）

### 问题截图

![image](https://user-images.githubusercontent.com/65720409/213243984-312afb3d-610b-4990-93e7-ee27c85cf57c.png)

### 复现步骤[可选]

艾特机器人 重启

**Comment by CMHopeSunshine** [comment]
执行重启命令后，bot目录有新建一个叫`robooting.json`的文件吗，这个文件是保存原群名片名的

**Comment by Tosd0** [comment]
> 执行重启命令后，bot目录有新建一个叫`robooting.json`的文件吗，这个文件是保存原群名片名的

并没有（rebooting.json吧，没有的）

**Comment by CMHopeSunshine** [comment]
不知道什么原因文件没有创建成功，那只好禁用这个修改群名片的功能了，我稍候修改一下把黑名单改成白名单

**Comment by CMHopeSunshine** [comment]
88fc4c042e3f94f82716690fb1950230b8cf51ad 已修改
