### ISSUE TITLE
[问题]国外服务器无法连接上资源列表

### ISSUE THREAD

**Issue by xmsama** [CMHopeSunshine/LittlePaimon#372]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`poetry install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows10
- Python版本: 3.9.10
- Nonebot2版本: 2.0.0rc2

### 问题描述
手动下载的资源包里面缺资源
[Errno 2] No such file or directory: 'resources/LittlePaimon/emoticons'
### 问题截图
![image](https://user-images.githubusercontent.com/36942744/213453811-086cbc8c-64b6-4f09-bffa-8d43a5d254f1.png)

**Comment by CMHopeSunshine** [comment]
网问题，如果开了代理请关闭代理

**Comment by xmsama** [comment]
这台主机是国外服务器 
然后我手动下载了文档中的资源包 但是看起来还是少了东西

**Comment by CMHopeSunshine** [comment]
文档中提供的资源包是旧资源，有一部分新资源需要启动时下载

**Comment by xmsama** [comment]
那我这个访问不到资源服务器的问题有没有什么其他方案解决 或者能否提供一个新版本资源包

**Comment by CMHopeSunshine** [comment]
国外服务器如果不能连上这个资源列表，那Wiki功能也用不了了

**Comment by CMHopeSunshine** [comment]
在`Web UI`里机器人配置-配置项管理-其他配置，试试换成github原地址，然后重启

**Comment by CMHopeSunshine** [comment]
![image](https://user-images.githubusercontent.com/63870437/213455213-5c129eae-8f28-458c-82bb-dd4d6fb1b5cc.png)

**Comment by xmsama** [comment]
我的docker没有映射web端口 有没有文件修改的方法

**Comment by CMHopeSunshine** [comment]
> 我的docker没有映射web端口 有没有文件修改的方法

`bot目录/config/paimon_config.yml`，把`github资源地址`置空
![image](https://user-images.githubusercontent.com/63870437/213455570-99836a4f-8e23-4b27-860d-955bb71a0351.png)

**Comment by xmsama** [comment]
![image](https://user-images.githubusercontent.com/36942744/213456214-e4f443d7-4cbb-4713-b9db-d5e3c1149a6d.png)
置空报错了

**Comment by CMHopeSunshine** [comment]
az，说错了，应该是改为''

**Comment by xmsama** [comment]
看起来问题解决了 老板威武
