### ISSUE TITLE
[关于进程卡死的问题]进程卡死在socket

### ISSUE THREAD

**Issue by FairyReimu** [CMHopeSunshine/LittlePaimon#375]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`poetry install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Centos 7.9
- Python版本: 3.8.2
- Nonebot2版本: 2.0.0rc2

### 问题描述

运行一段时间后，进程会进入睡眠状态，经过排除发现卡在socket上

### 问题截图

目前pid为10172，此时状态处于睡眠
![image](https://user-images.githubusercontent.com/90098435/214497633-0b4d9227-a0da-426f-99e3-4fdfb0650e0a.png)
首先用ps查看信息
![image](https://user-images.githubusercontent.com/90098435/214497077-ce35d738-88f7-4b38-88ee-18fd31d72178.png)
使用strace看到死在了系统回调read这里，描述符为22
![image](https://user-images.githubusercontent.com/90098435/214497198-a2bcb29e-eea4-4eb9-aea8-fb3fe406eab3.png)
进一步发现22指向socket，死在了读socket上面
![image](https://user-images.githubusercontent.com/90098435/214497275-e9b580f3-25e2-4194-8389-096b41585f80.png)
查看连接情况如下
![image](https://user-images.githubusercontent.com/90098435/214499703-8cb2ec1d-835c-4f97-9651-47a731158e13.png)

### 复现步骤[可选]

启动后一段时间就莫名停止，不知道具体的

**Comment by CMHopeSunshine** [comment]
单看这些看不出问题，最好还是给日志，看看是不是什么功能指令导致崩溃卡死了（例如材料地图）

**Comment by FairyReimu** [comment]
> 单看这些看不出问题，最好还是给日志，看看是不是什么功能指令导致崩溃卡死了（例如材料地图）

日志没有任何异常，都是在正常聊天中结束了，未触发任何指令的情况下，所以就觉得奇怪

**Comment by FairyReimu** [comment]
> > 单看这些看不出问题，最好还是给日志，看看是不是什么功能指令导致崩溃卡死了（例如材料地图）
> 
> 日志没有任何异常，都是在正常聊天中结束了，未触发任何指令的情况下，所以就觉得奇怪

可能是其他问题，我再研究一段时间，这个问题可以关闭了，谢谢~
