### ISSUE TITLE
实时便签命令刚开始能用，一段时间后报遇到验证码阻拦

### ISSUE THREAD

**Issue by jiange555** [CMHopeSunshine/LittlePaimon#378]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`poetry install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows10
- Python版本: 3.9.10
- Nonebot2版本: 2.0.0rc2

### 问题描述

实时便签命令刚开始能用，一段时间后报遇到验证码阻拦

### 问题截图

![image](https://user-images.githubusercontent.com/109725719/215648277-b16dd490-f503-4fd8-9ca8-620c90dea419.png)

### 复现步骤[可选]

描述问题复现过程...

**Comment by CMHopeSunshine** [comment]
米游社风控策略，无法解决，如果你有能力，可以自行修改代码，接入打码平台
