### ISSUE TITLE
sy命令米游社有记录了，bot这边还是提示没打深渊

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#38]
好像刷新间隔有点久啊，必须sy-r才能看到，能否把刷新间隔设置短点呢

**Comment by CMHopeSunshine** [comment]
最新改成了10分钟的缓存

**Comment by forchannot** [comment]
> 最新改成了10分钟的缓存

好像缓存还是很长？没有改成功吗。上午11点打的深渊，米游社那边没注意是多久刷新的，但是刚才输sy还是提示我没有打，应该不会这么久。必须加-r。或者能不能让每次-r后直接刷新缓存，而不是仅仅一次性查看

**Comment by CMHopeSunshine** [comment]
> 

要不就不缓存了吧
