### ISSUE TITLE
[问题]为什么帮助图没有原神WIKI

### ISSUE THREAD

**Issue by dengma0** [CMHopeSunshine/LittlePaimon#381]
最新版本，不能使用WIKI
![C37YHOFS8(E8RB~EQB$SPYG](https://user-images.githubusercontent.com/18988625/216527374-55b0cdce-4a43-4d79-a60c-8f59b0210870.PNG)

**Comment by CMHopeSunshine** [comment]
请提供启动时的插件加载状况日志

**Comment by dengma0** [comment]
![image](https://user-images.githubusercontent.com/18988625/216549573-d3c183c2-6e02-4a24-9c7c-9a1a30c0000f.png)

**Comment by dengma0** [comment]
已解决

**Comment by dengma0** [comment]
已解决
