### ISSUE TITLE
[建议]出个删除绑定uid的指令

### ISSUE THREAD

**Issue by Tosd0** [CMHopeSunshine/LittlePaimon#383]
### 当前不足

有的人绑定了错误的uid之后 不知道绑定新的就可以覆盖原来的uid，因此出一个删除绑定uid 的指令可以防止这种特性影响使用（）

### 建议内容

删除uid指令，删除后即可清除该用户绑定的uid

### 参考示例[可选]

无

**Comment by CMHopeSunshine** [comment]
UID不会产生实际上的`绑定`，如果在查询时明确给出了UID，那就查询该UID的，如果没给出，那就用上一次查询的UID。

`绑定uid`这个指令实际上也是记录UID而已，你只要在查询时附带UID，例如`ys100123456`，那记录的UID就会变成`100123456`

**Comment by CMHopeSunshine** [comment]
如果你想删除cookie，可以用`删除ck uid`指令，该指令会删除这个uid所绑定的cookie以及签到、米游币获取订阅等信息

**Comment by Tosd0** [comment]
> UID不会产生实际上的`绑定`，如果在查询时明确给出了UID，那就查询该UID的，如果没给出，那就用上一次查询的UID。
> 
> `绑定uid`这个指令实际上也是记录UID而已，你只要在查询时附带UID，例如`ys100123456`，那记录的UID就会变成`100123456`

我可能忘说了 是通过#绑定uid 123456789 进行了绑定后，这个uid确实在你不指定uid的情况下是作为查询默认的uid的。他和你的qq号暂时绑定了，虽然可以通过重新绑定来替换新的uid，但用户大概率不会有这样的脑回路。可能会认为绑定了就需要解绑才能绑定新的

**Comment by CMHopeSunshine** [comment]
那怪用户去吧，UID是随时可以更换的，不像cookie，我觉得没必要再加一条指令来专门删除记录，用户不懂就教，不应该由开发者来改。

**Comment by Tosd0** [comment]
好（
