### ISSUE TITLE
更新角色信息出现问题

### ISSUE THREAD

**Issue by KomeijiRan** [CMHopeSunshine/LittlePaimon#384]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`poetry install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows10
- Python版本: 3.9.10
- Nonebot2版本: 2.0.0rc2

### 问题描述

使用“更新面板”命令或“更新角色信息天赋”命令时出现如下报错：
“更新失败，缺少'playerInfo'的数据，可能是Enka.Network接口出现问题”
但后台显示为更新成功

### 问题截图

![图片](https://user-images.githubusercontent.com/96311761/217719260-7a5c78cc-c970-478f-b81d-7a7e336c6519.png)
![图片](https://user-images.githubusercontent.com/96311761/217719649-cbab89ce-f7df-463e-9a5c-4afd479f066a.png)

**Comment by CMHopeSunshine** [comment]
enka接口问题，只能等接口维护者修复
