### ISSUE TITLE
[问题]poetry install依赖失败 numpy安装失败

### ISSUE THREAD

**Issue by YouYouLip** [CMHopeSunshine/LittlePaimon#386]
RuntimeError

  Hash for numpy (1.24.1) from archive numpy-1.24.1-cp310-cp310-win_amd64.whl not found in known hashes (was: sha256:f78328b9661f42097661c59c7d9ddd6f09a51da499c7882290951ab0ac58ac53)

  at ~\AppData\Roaming\Python\Python310\site-packages\poetry\installation\executor.py:673 in _validate_archive_hash
      669│         archive_hash: str = "sha256:" + get_file_hash(archive)
      670│         known_hashes = {f["hash"] for f in package.files}
      671│
      672│         if archive_hash not in known_hashes:
    → 673│             raise RuntimeError(
      674│                 f"Hash for {package} from archive {archive.name} not found in"
      675│                 f" known hashes (was: {archive_hash})"
      676│             )
      677│
在另一个电脑部署上的错误如上，我尝试去numpy官网下一个numpy-1.24.1-cp310-cp310-win_amd64.whl文件 用pip install+文件名安装后 继续使用poetry install还是会显示此错误 尝试通过安装有关numpy的matplotlib安装后使用poetry install也会这样

**Comment by CMHopeSunshine** [comment]
鉴于poetry又重又慢，所以新教程已经不再用poetry了，如果您是在新部署Bot，可以按新教程使用脚手架来部署。
如果仍想用poetry，可以用以下方法：
1.删除poetry.lock文件再`poetry install`，不过这样poetry会花很长时间去安装。
2.使用`poetry run pip install numpy`来单独安装numpy，其他单个依赖同理。
3.使用`poetry run pip install -r requirements.txt`来安装所有需要的依赖。

**Comment by YouYouLip** [comment]
> 

（悲）那还是去试试脚手架方式部署吧
