### ISSUE TITLE
[问题]流浪者和珐露珊角色头像缺失

### ISSUE THREAD

**Issue by RoundedOrange** [CMHopeSunshine/LittlePaimon#391]
群友在使用小派蒙抽卡分析等命令时，发现流浪者和珐露珊的头像变成的问号，
![image](https://user-images.githubusercontent.com/74751204/219288565-a90b617f-ac9b-488f-b53f-4587697c4e8d.png)
其他角色头像显示都正常。

**Comment by CMHopeSunshine** [comment]
到`bot目录/resources/LittlePaimon/avatar`文件夹，把`UI_AvatarIcon_Faruzan.png`和`UI_AvatarIcon_Wanderer.png`文件删掉即可
