### ISSUE TITLE
[问题]The _imagingft C module is not installed

### ISSUE THREAD

**Issue by youyouhanshuang** [CMHopeSunshine/LittlePaimon#395]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`poetry install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Centos7
- Python版本: 3.9.10
- Nonebot2版本: 2.0.0rc2

### 问题描述

The _imagingft C module is not installed

### 问题截图
![图片](https://user-images.githubusercontent.com/88363279/222060904-5bf25e05-2964-4e2e-9390-f31df8de9596.png)

![图片](https://user-images.githubusercontent.com/88363279/222060849-e09cc95c-567b-4211-a9e3-0c96efbde385.png)

![图片](https://user-images.githubusercontent.com/88363279/222060976-95564d16-c02c-48fb-9dd8-03998457fd46.png)

**Comment by CMHopeSunshine** [comment]
你的系统缺少相关依赖，请自己搜查解决，~~谨防CentOS~~
