### ISSUE TITLE
[问题]资源下载不到迪西亚的抽卡图片

### ISSUE THREAD

**Issue by dengma0** [CMHopeSunshine/LittlePaimon#397]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`poetry install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows10
- Python版本: 3.9.10
- Nonebot2版本: 2.0.0rc2

### 问题描述

简单的描述问题发生过程或表现...

### 问题截图

提供问题或日志截图...

### 复现步骤[可选]

描述问题复现过程...

**Comment by CMHopeSunshine** [comment]
昨天就解决了 cbc7b377b2f54a6f6ca128c032bb8985f3f2bac3 ，**请确定您已更新到最新版本**

**Comment by dengma0** [comment]
已经是最新的，通过poetry nb run nb运行后，提示所有资源为最新，无需下载，但是资源库里面没有迪西亚的图片

**Comment by CMHopeSunshine** [comment]
我自己的是有的
![image](https://user-images.githubusercontent.com/63870437/222315200-f0aa81c7-9b40-4604-9b9c-47a259fa76b6.png)

**Comment by CMHopeSunshine** [comment]
可以检查一下`Bot目录/resources/LittlePaimon/avatar/UI_AvatarIcon_Dehya.png`

**Comment by dengma0** [comment]
检查了没有哦，可以强制更新资源吗

**Comment by CMHopeSunshine** [comment]
图标资源理应在用到时自动下载，没有强制更新指令，可以手动下
![](https://api.ambr.top/assets/UI/UI_AvatarIcon_Dehya.png)
https://api.ambr.top/assets/UI/UI_AvatarIcon_Dehya.png

**Comment by dengma0** [comment]
抽卡发生错误:[Errno 2] No such file or directory: '/root/LittlePaimon/resources/LittlePaimon/gacha_res/角色/迪希雅.png'

**Comment by CMHopeSunshine** [comment]
> 抽卡发生错误:[Errno 2] No such file or directory: '/root/LittlePaimon/resources/LittlePaimon/gacha_res/角色/迪希雅.png'

这个晚上补充

**Comment by dengma0** [comment]
好的，大佬
