### ISSUE TITLE
[问题] webui配置的命令别名不生效

### ISSUE THREAD

**Issue by 43887016** [CMHopeSunshine/LittlePaimon#398]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`poetry install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows server 2016
- Python版本: 3.8
- Nonebot2版本: 2.0.0rc2

### 问题描述

在webui中尝试为ysd命令配置别名“面板”或yysd，保存且重启bot均不生效。
已进行的尝试如下：
1、尝试按照文档配置为
![image](https://user-images.githubusercontent.com/34833023/222352540-67230bf3-afbb-4d49-82ba-a02c9dc0acd7.png)
2、尝试添加命令触发符号“#”进行正则匹配
![image](https://user-images.githubusercontent.com/34833023/222352744-a2cf29c9-624e-4c47-b05c-7b17433900d7.png)

debug日志显示均未匹配到规则
![image](https://user-images.githubusercontent.com/34833023/222353053-8d8f97ce-623a-4016-9f63-161ddc458c64.png)
但webui测试显示命令正常
![image](https://user-images.githubusercontent.com/34833023/222353247-feac1928-9d5a-493f-a44d-43b4ff0fad31.png)

**Comment by CMHopeSunshine** [comment]
测试中有生效的话，qq里肯定也生效的。检查一下面板插件有无正常加载，试试原命令`ysd`能用不。

**Comment by 43887016** [comment]
测试ysd命令正常，请问命令别名的功能需要其他插件支持吗？
![image](https://user-images.githubusercontent.com/34833023/222355885-7561759e-0e55-4aad-889b-49c8a2b87755.png)

**Comment by CMHopeSunshine** [comment]
我自己的设置是这样的`^#?([\u4e00-\u9fa5]{1,5}(?<!参考))(面板|伤害)$` >> `ysd\1`，可以参考一下

**Comment by CMHopeSunshine** [comment]
> 测试ysd命令正常，请问命令别名的功能需要其他插件支持吗？ ![image](https://user-images.githubusercontent.com/34833023/222355885-7561759e-0e55-4aad-889b-49c8a2b87755.png)

您的命令前缀是#吗，那您设的第一个普通匹配要删掉，因为第一个已经把消息改为了ysd行秋，第二个别名就不会再运作

**Comment by 43887016** [comment]
> 您的命令前缀是#吗，那第一个普通匹配要删掉
 已删除，消息仍未生效，但是网页测试均通过。
 已尝试使用您的正则，网页测试正常，但消息仍未生效。

看上去像是消息没有触发别名相关的功能，原生命令都是正常的。尝试使用其他的关键字和设置其他命令的别名，也没有生效，但是网页测试均通过了。

**Comment by CMHopeSunshine** [comment]
测试结果有带#吗，因为您设的的命令前缀是#，所以经过别名修改后的命令也得#开头才能触发指令

**Comment by CMHopeSunshine** [comment]
试试 `#ysd\1`

**Comment by 43887016** [comment]
> 试试 `#ysd\1`

问题解决。。。原来是这样解决的么，太厉害了
这个命令替换之后居然还是需要加触发我是没想到的。。。

谢谢您的帮助~~打扰了~
