### ISSUE TITLE
角色面板的圣遗物评分和伤害计算说明

### ISSUE THREAD

**Issue by CMHopeSunshine** [CMHopeSunshine/LittlePaimon#40]
- [x] 漏了个神子的立绘
- [x] 莫娜和绫华的天赋显示bug
- [x] 套装显示bug
- [x] 天赋等级补上命座加成
- [x] 优化评分
- [x] 旅行者面板查看
- [ ] 伤害计算（~~预计6月末~~ 已完成`钟离、胡桃、雷神`）

圣遗物评级说明：
以有效词条数作为评级的标准，每个角色、不同流派玩法的有效词条数不尽相同。
以常见的攻双暴3种有效词条的角色为例，圣遗物有效词条数：
- 12以下为C级
- 12~18为B级
- 18~24为A级
- 24~28.8为S级
- 28.8~33.6为SS级
- 33.6以上为SSS级

这种按词条的评分方式参考了`ysin`，评级参考了`游创工坊`
不同角色之间就相对更公平，但是似乎有虚高的情况，~~怎么我230暴伤的胡桃有效词条比别人270暴伤的还高~~，个人感觉可能在词条权重上还得调整一下，但是`ysin`等评分程序没有针对角色权重来评，只能说先这样吧，等一个更好的方案，大家也可以提提意见。

**Comment by Chinzicam** [comment]
![image](https://user-images.githubusercontent.com/108013361/184653547-c3a178ff-6961-4345-a52f-89e70f80ed62.png)
草，群友的香菱评分38.9都没3S
