### ISSUE TITLE
[问题] web控制面板暗黑主题部分区域背景和文字对比度过低

### ISSUE THREAD

**Issue by shoucandanghehe** [CMHopeSunshine/LittlePaimon#400]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`poetry install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Ubuntu22.04
- Python版本: 3.10.8
- Nonebot2版本: 2.0.0rc3

### 问题描述

web控制面板暗黑主题部分区域背景和文字对比度过低

### 问题截图

![image](https://user-images.githubusercontent.com/51957264/222547667-5608120d-ea59-463a-a4be-bdf3d6b1d316.png)

### 复现步骤[可选]

描述问题复现过程...

**Comment by CMHopeSunshine** [comment]
这是上游amis框架的问题，下游没办法修改
