### ISSUE TITLE
[问题]时区问题导致原神猜语音功能无法正常使用

### ISSUE THREAD

**Issue by Kwisma** [CMHopeSunshine/LittlePaimon#409]
### 当前不足

只有猜语音，没有回答猜语音的指令

### 建议内容

完善一下猜语音功能的玩法

**Comment by CMHopeSunshine** [comment]
啥叫没有回答猜语音的指令啊，你直接回答角色名不就是了

**Comment by Kwisma** [comment]
> 啥叫没有回复猜语音的指令啊，你直接回复角色名不就是了

回复没反应，有这个回答功能吗？

**Comment by CMHopeSunshine** [comment]
![RE}FWX$I)49)E01FRF(W N](https://user-images.githubusercontent.com/63870437/226150261-33969574-ae06-4d8a-9b61-76fad4a35693.png)

**Comment by CMHopeSunshine** [comment]
猜对了会马上回复，都没猜到的话30秒后公布答案

**Comment by Kwisma** [comment]
> 猜对了会马上回复，都没有猜到的对话30秒后公开答案

好吧，可能我遇到bug了，既没有回复，30秒过后也没有公布答案
![Screenshot_20230319-102133_QQ](https://user-images.githubusercontent.com/77215384/226150362-4239b261-3303-4a36-8726-8fe81dcf6cd0.png)

**Comment by CMHopeSunshine** [comment]
看下日志

**Comment by Kwisma** [comment]
日志似乎没有报错
![Screenshot_20230319-102641_Termux](https://user-images.githubusercontent.com/77215384/226150416-b124631d-7f12-4719-a48a-36d6529720df.png)

**Comment by CMHopeSunshine** [comment]
重启下机器人试试，感觉是莫名阻塞了导致上一个游戏没结束

**Comment by Kwisma** [comment]
不知道为什么就是用不了

![Screenshot_20230319-104943_Termux](https://user-images.githubusercontent.com/77215384/226150959-72824515-3d4e-421d-b7ac-e9f6219ea1c0.png)

**Comment by CMHopeSunshine** [comment]
时区不一致导致定时任务结束异常，检查一下时区设置吧
![image](https://user-images.githubusercontent.com/63870437/226151060-d89f0cfa-5f16-4d85-acc9-0835a3ab285d.png)
