### ISSUE TITLE
[问题]help指令使内存占用剧增导致bot被杀掉

### ISSUE THREAD

**Issue by Kwisma** [CMHopeSunshine/LittlePaimon#411]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`poetry install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: debian11
- Python版本: 3.9.10
- Nonebot2版本: 2.0.0rc2

### 问题描述

发送菜单获取帮助时，前台/后台就会自动退出，无法稳定运行

### 问题截图

![Screenshot_20230321-153906_Termux](https://user-images.githubusercontent.com/77215384/226543478-ba5937b8-48ca-4270-8b42-04254f0ec05a.png)

**Comment by CMHopeSunshine** [comment]
help帮助图在插件多的情况下，发送时需要很大内存，内存不够会被系统kill掉

**Comment by CMHopeSunshine** [comment]
可以在web ui中隐藏部分不必要的插件展示

**Comment by qjksxy** [comment]
有没有试过加点虚拟内存呢。

[参考文章-添加虚拟内存](http://www.lining0806.com/linux%E4%B8%8B%E5%A6%82%E4%BD%95%E6%B7%BB%E5%8A%A0%E8%99%9A%E6%8B%9F%E5%86%85%E5%AD%98/)

**Comment by Kwisma** [comment]
> 

我这个是固定机，加不了任何配置的

**Comment by qjksxy** [comment]
> 
> 我这个是固定机，加不了任何配置的

虚拟内存，不需要加配置。
