### ISSUE TITLE
[建议]出个bot账号管理吧

### ISSUE THREAD

**Issue by QAQQL** [CMHopeSunshine/LittlePaimon#412]
### 当前不足

无法控制由哪个bot机器人发出消息
由于最近gohttp协议爆炸的事，qq登陆账号的列表顺序变了，导致消息提醒使用了错误的账号发出

### 建议内容

出个bot账号管理，可以选定不作为小派蒙账号，或者不监听消息之类的
或者指定bot主账号之类的

**Comment by CMHopeSunshine** [comment]
这个版本没办法进行这种大调整了。
目前正在着手开发下一个大版本，将会支持多平台和多bot管理，~~敬请期待LittlePaimon 4.0~~

**Comment by QAQQL** [comment]
好的，期待
