### ISSUE TITLE
无法使用原神扫码绑定命令

### ISSUE THREAD

**Issue by arcanewing** [CMHopeSunshine/LittlePaimon#425]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

无法使用原神扫码绑定命令 后台报错
想要手动输入cookie，按文档在浏览器获取cookie后使用命令绑定，机器人回复
Cookie无效，缺少cookie_token或login_ticket字段

### 问题截图

![image](https://user-images.githubusercontent.com/28585632/232476125-f2dfd629-56dc-403a-aba2-72156ecf8f12.png)

### 复现步骤[可选]

描述问题复现过程...

**Comment by CMHopeSunshine** [comment]
`httpx.ConnectTimeout`，网络超时

**Comment by arcanewing** [comment]
> `httpx.ConnectTimeout`，网络超时

知道是网络超时..但是找不到原因，手动获取cookie机器人也不认

**Comment by Orangenwasser** [comment]
有没有挂梯子？挂梯子的最好关掉试试，尝试切换pip的源（阿里、清华、豆瓣），更换下DNS服务器，清空DNS缓存都试试
