### ISSUE TITLE
[问题]最近更新角色信息总是报错

### ISSUE THREAD

**Issue by FairyReimu** [CMHopeSunshine/LittlePaimon#428]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: centos7(example)
- Python版本: 3.9.10(example)
- Nonebot2版本: 2.0.0rc4(example)

### 问题描述

最近更新角色信息总是报错，猜测可能是角色带有新圣遗物引发，但是重启机器人时提示的是资源已是最新
报错语句如下：
更新失败，缺少'UI_RelicIcon_15030_4'的数据，可能是Enka.Network接口出现问题

### 问题截图

提供问题或日志截图...

### 复现步骤[可选]

描述问题复现过程...

**Comment by CMHopeSunshine** [comment]
请更新到最新版本
