### ISSUE TITLE
[问题]无法发送群消息

### ISSUE THREAD

**Issue by TakeNAKE** [CMHopeSunshine/LittlePaimon#435]
确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows10(example)
- Python版本: 3.9.10(example)
- Nonebot2版本: 2.0.0rc4(example)

### 问题描述

无法发送群消息

### 问题截图

![Screenshot_20230505_163849_com termux](https://user-images.githubusercontent.com/105784549/236414108-905c0182-3917-4fd0-b523-782c093f70b1.jpg)
![Screenshot_20230505_160520_com termux](https://user-images.githubusercontent.com/105784549/236414300-ceaaa664-31f3-4c6a-94b4-562b31b32949.png)
![Screenshot_20230505_160306_com termux](https://user-images.githubusercontent.com/105784549/236414339-04167219-1ff0-48ea-9542-e071d4ef69c8.png)
![Screenshot_20230505_160154_com termux](https://user-images.githubusercontent.com/105784549/236414365-cf5d2c00-d3c6-4854-b71d-93bf5af91078.png)

### 复现步骤[可选]

私聊没问题，群聊寄

**Comment by TakeNAKE** [comment]
我换号了也不行，第一张是换号之后的截图

**Comment by CMHopeSunshine** [comment]
gocq的问题

**Comment by CMHopeSunshine** [comment]
很可能是插件过多导致帮助图过长，gocq接收超时

**Comment by TakeNAKE** [comment]
私聊可以，群聊不行

**Comment by CMHopeSunshine** [comment]
风控或图片过大问题，有异议请去gocq提issue，收发消息由gocq负责而非本bot
