### ISSUE TITLE
[问题]请问怎么禁用小派蒙的帮助，或者关闭图中功能

### ISSUE THREAD

**Issue by motian16** [CMHopeSunshine/LittlePaimon#436]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows10(example)
- Python版本: 3.9.10(example)
- Nonebot2版本: 2.0.0rc4(example)

### 问题描述
群里已经有一个云崽Bot，在添加表情时两者会冲突，且已经做了一张小派蒙帮助图，原版的也用不上了
如果不能禁用帮助图，那有办法关闭小派蒙这个添加帮助关键词的功能吗
![Screenshot_2023-05-15-21-31-18-82](https://github.com/CMHopeSunshine/LittlePaimon/assets/89713447/bc7f69cf-51d2-4f43-835a-911375c446e2)

简单的描述问题发生过程或表现...

### 问题截图

提供问题或日志截图...

### 复现步骤[可选]

描述问题复现过程...

**Comment by CMHopeSunshine** [comment]
到`web ui`的插件管理中禁用

**Comment by motian16** [comment]
> 到的插件管理中禁用`web ui`

您好，我看了您的回复仔细看了一遍看了控制台，我是把所有关于帮助管理的功能，都在信息里禁用且关闭帮助菜单里显示
不过这个功能还是关不掉，还是会触发关键词
![Screenshot_2023-05-16-08-11-05-85_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/CMHopeSunshine/LittlePaimon/assets/89713447/1e9ca1d8-3502-4ff7-9c4b-15d92ce7bf75)

**Comment by CMHopeSunshine** [comment]
这个截图中的功能不是派蒙的
