### ISSUE TITLE
[问题]抽卡发生错误:'碧落之珑'

### ISSUE THREAD

**Issue by Tosd0** [CMHopeSunshine/LittlePaimon#437]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Ubuntu 20.04
- Python版本: 3.10.8
- Nonebot2版本: nb-cli 1.1.2（不知道咋看nb版本）

### 问题描述
抽武器池出现报错：抽卡发生错误:'碧落之珑'，更新资源文件也没用
![ADBB3B91-41B1-40A0-9360-F41D45479824](https://github.com/CMHopeSunshine/LittlePaimon/assets/65720409/97f5d883-85cd-4a34-a1d1-3139d3a60f49)

nb端日志：
```
05-21 16:39:10 [SUCCESS] nonebot | OneBot V11 
*** | [message.group.normal]: Message -266898138 from ***@[群:***] '抽6十连武器'
05-21 16:39:10 [INFO] nonebot | Event will be handled by Matcher(type='message', module=LittlePaimon.plugins.Paimon_Gacha)
05-21 16:39:12 [INFO] nonebot | Matcher(type='message', module=LittlePaimon.plugins.Paimon_Gacha) running complete
```
启动日志：

```
05-21 16:35:39 [SUCCESS] LittlePaimon | [数据库]连接成功
05-21 16:35:39 [SUCCESS] LittlePaimon | [插件管理器]初始化完成
05-21 16:35:39 [INFO] LittlePaimon | [资源检查]开始检查资源
05-21 16:35:40 [INFO] LittlePaimon | [资源检查]资源完好，无需下载
```

更新资源日志：
```
nb paimon res
[?] 你要下载(更新)哪些资源? 小派蒙基础必需资源, 原神图标资源
[?] 要使用的资源下载源? cherishmoon镜像源(国内推荐)
检测到已有部分基础资源，进行增量更新...
原神图标资源 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 102.3/102.3 MB • 3.7 MB/s • 0:00:00
资源更新完成
```

### 问题截图

如上

### 复现步骤[可选]

群内抽卡：`抽6十连武器`

**Comment by CMHopeSunshine** [comment]
最近较忙，没补充武器资源，过几天补充

**Comment by CMHopeSunshine** [comment]
已补充，重启小派蒙进行资源下载即可， https://github.com/CMHopeSunshine/LittlePaimonRes/commit/2259fc5952f2d7f89d64a1d5be717685700f4304
