### ISSUE TITLE
悲剧的踩坑：git clone此项目到nonebot2项目的./目录（根目录），而不是./src/plugin目录

### ISSUE THREAD

**Issue by FBIOpentheDoor26** [CMHopeSunshine/LittlePaimon#44]

**Comment by FBIOpentheDoor26** [comment]
怪没有逐行看文档

**Comment by CMHopeSunshine** [comment]
由于是多个插件集合的形式，所以放到`./src/plugin/`的话加载不了子插件..

**Comment by FBIOpentheDoor26** [comment]
谢谢

**Comment by Agnes4m** [comment]
同样中招+1，习惯性在src里加插件了

**Comment by CMHopeSunshine** [comment]
如果放src/plugin/里的话，加载插件时就写`nonebot.load_plugins("src/plugin/LittlePaimon")`，其他位置同理

**Comment by Agnes4m** [comment]
![image](https://user-images.githubusercontent.com/70925546/175203993-00040dcc-f260-4c2c-aa62-f3bc2f28069d.png)
那样似乎只能加载这样，并不能使用

**Comment by Z735803792** [comment]
![image](https://user-images.githubusercontent.com/70925546/175204075-eb33255b-555e-4120-a63e-1662a5cf01bd.png)

**Comment by CMHopeSunshine** [comment]
注意是`load_plugins`而不是`load_plugin`，`load_plugins`是可以把该目录下所有插件加载
