### ISSUE TITLE
[问题]绘制背包出错，提示某weapon的图片notfound

### ISSUE THREAD

**Issue by Cathgao** [CMHopeSunshine/LittlePaimon#440]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows10
- Python版本: 3.11.2

### 问题描述

ysa绘制背包提示出错，weapon某图片notfound
`制图时出错：resources\LittlePaimon\weapon\c917d80dfd8fd936525142e392b1f6b4.png not found`

### 问题截图

![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/21031564/d15a29f9-1a65-46f0-950e-2c79f9700e60)

**Comment by CMHopeSunshine** [comment]
昨天已经修复了，请更新到最新版本并`更新角色信息`
