### ISSUE TITLE
[问题] 重启时报错找不到文件

### ISSUE THREAD

**Issue by MoRanYue** [CMHopeSunshine/LittlePaimon#442]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows server 2022
- Python版本: 3.9.9
- Nonebot2版本: 2.0.0rc4

### 问题描述

可以正常用`nb paimon run`这样的命令打开。但是当使用“@bot 重启”命令时，控制台报错，找不到Python可执行文件。

可执行文件在C:/Program Files中，它似乎寻找的是bot.py所在目录的Files/Python39/python.exe

换了个路径重新配置，问题依旧。

### 问题截图

![7ef281c41844b473](https://github.com/CMHopeSunshine/LittlePaimon/assets/84905594/453c3bae-4e74-4938-b6fa-dd79c90ba866)

### 复现步骤[可选]

1. 用`nb paimon run`运行bot。
2. 使用“@bot 重启”命令。
3. bot正常关闭。
4. 控制台报错如上图。

**Comment by CMHopeSunshine** [comment]
解释器路径是由python标准库`sys`提供的，路径不对那是python自己的问题了，有没有考虑使用虚拟环境呢？

**Comment by MoRanYue** [comment]
康完相关源代码后，我觉得很奇怪。明明直接使用原来的启动命令来重启bot，都可以直接启动，却在它内部执行命令还会找成“CWD/Files/Python39”……

**Comment by MoRanYue** [comment]
可以了，在虚拟环境中重新配置了一遍
