### ISSUE TITLE
[问题]绮良良使用角色信息和角色背包相关功能报错

### ISSUE THREAD

**Issue by Noctulus** [CMHopeSunshine/LittlePaimon#443]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Ubuntu 22.04.2 LTS
- Python版本: 3.10.6
- Nonebot2版本: 2.0.0rc4

### 问题描述

如果角色背包和角色展柜里包含角色`绮良良`，会导致角色信息和角色背包功能出错；
角色信息相关错误为：`更新失败，缺少'绮良良'的数据，可能是Enka.Network接口出现问题`
角色背包相关错误为：`制图时出错：unsupported operand type(s) for *: 'NoneType' and 'int'`

### 问题截图

![1685237208110](https://github.com/CMHopeSunshine/LittlePaimon/assets/39023047/9d859104-bc44-4d88-b192-69de1743dc87)
终端日志内无更多有效信息

**Comment by CMHopeSunshine** [comment]
请确保你已经更新到最新版本

**Comment by Noctulus** [comment]
> 请确保你已经更新到最新版本

我已确认升级到最新版本，依然存在此问题。

**Comment by Noctulus** [comment]
![-10e5476d94f765f4](https://github.com/CMHopeSunshine/LittlePaimon/assets/39023047/6e62f86f-2c33-44b9-a61c-4721f3d23de2)
