### ISSUE TITLE
[问题]更新到最新版本依然存在绮良良面板更新的错误

### ISSUE THREAD

**Issue by Noctulus** [CMHopeSunshine/LittlePaimon#445]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Ubuntu22.04.2
- Python版本: 3.10.6
- Nonebot2版本: 2.0.0rc3

### 问题描述

使用更新面板功能报错`更新失败，缺少'绮良良'的数据，可能是Enka.Network接口出现问题`
### 问题截图

![2023-06-06 23-18-27屏幕截图_111938](https://github.com/CMHopeSunshine/LittlePaimon/assets/39023047/e79fb0b4-70de-4659-9c59-674b14310848)

### 复现步骤

其他UID有的可以正常更新；同时终端日志可以看到有提示更新玩家信息成功，但依然会发送如上提示信息；尝试ysd绮良良则会报错`获取角色信息失败，错误信息：resources/LittlePaimon/enka_card/背景_None.png not found`

**Comment by nicklly** [comment]
缺少图片资源 重启bot就会自动下载缺失的图片资源

**Comment by CMHopeSunshine** [comment]
确定真的更新到最新版本了吗，请看看`LittlePaimon/config/data/roles_data.json`中是否有绮良良的数据

**Comment by Noctulus** [comment]
> 确定真的更新到最新版本了吗，请看看`LittlePaimon/config/data/roles_data.json`中是否有绮良良的数据

确定已是最新版本，并且甚至其他部分人的账号是可以查看绮良良面板的，但是我的账号稳定触发错误

**Comment by CMHopeSunshine** [comment]
更新后试试还有没有问题

**Comment by Noctulus** [comment]
没问题了，谢谢作者
