### ISSUE TITLE
既然有了帮助菜单

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#45]
能否选择让别人第一次加机器人通过的时候自动发送帮助菜单或者发送欢迎提示让对方知道发送help来获取命令大全

**Comment by CMHopeSunshine** [comment]
~~其实是有这个功能，有自动通过好友请求和群邀请的配置，开了自动通过的话接受后会发提示~~，之后改成接受后（无论手动自动）就发提示

**Comment by forchannot** [comment]
> ~其实是有这个功能，有自动通过好友请求和群邀请的配置，开了自动通过的话接受后会发提示~，之后改成接受后（无论手动自动）就发提示

编辑了，找到了。不过博客貌似很久没更新了（
