### ISSUE TITLE
制图出错:resources\LittlePaimon\weapon\496e9d53e10e8313a6296ce1227ad12e.png not found

### ISSUE THREAD

**Issue by arbitraryGate** [CMHopeSunshine/LittlePaimon#454]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows10(example)
- Python版本: 3.9.10(example)
- Nonebot2版本: 2.0.0rc4(example)

### 问题描述

下载的资源包 还是里面没有这些文件 496e9d53e10e8313a6296ce1227ad12e.png 
![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/31301114/e23b6946-3e55-42f5-b82c-6a2d59fcf0a1)

制图出错:resources\LittlePaimon\weapon\496e9d53e10e8313a6296ce1227ad12e.png not found

### 问题截图

![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/31301114/952965fd-5e3f-4a67-924b-d930cd7ef872)

### 复现步骤[可选]

描述问题复现过程...

**Comment by CMHopeSunshine** [comment]
确认已经更新到最新版本了吗？
在Bot目录运行`git log`看看

**Comment by arbitraryGate** [comment]
![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/31301114/750bf2e5-f89d-44bc-99b2-1ff239430a70)

**Comment by CMHopeSunshine** [comment]
更新后重启了吗

**Comment by arbitraryGate** [comment]
是的

**Comment by CMHopeSunshine** [comment]
先`更新角色信息`试试

**Comment by arbitraryGate** [comment]
可以了 3q
