### ISSUE TITLE
[问题] 获取深渊战报时提示制图出错

### ISSUE THREAD

**Issue by lvwenzhuo2003** [CMHopeSunshine/LittlePaimon#457]
### 确认

[x] 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
[x] 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
[x] 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Ubuntu Server 22.04
- Python版本: 3.10.6
- Nonebot2版本: 2.0.0rc4(example)

### 问题描述

获取深渊战报时出现错误，找不到资源文件，但是资源检查显示没有问题

### 问题截图

<img width="991" alt="image" src="https://github.com/CMHopeSunshine/LittlePaimon/assets/51859807/cff22aa2-5011-4a88-954d-38f91a623372">

### 复现步骤[可选]

描述问题复现过程...

**Comment by CMHopeSunshine** [comment]
mhy改了api返回的icon内容，稍候修复

**Comment by CMHopeSunshine** [comment]
9ba266b0387d0ed42af47162f78660767efb1f64 已修复
