### ISSUE TITLE
[问题]无法获取米游社信息

### ISSUE THREAD

**Issue by Karmau-Git** [CMHopeSunshine/LittlePaimon#479]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows10(example)
- Python版本: 3.9.10(example)
- Nonebot2版本: 2.0.0rc4(example)

### 问题描述
提示遇到验证码阻拦,手动进入米游社后未看到验证码

### 问题截图
![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/118444525/39abf057-1d00-44d3-adbd-c6b46dba3e78)

**Comment by luluxiaoyu** [comment]
同样的问题，但是进去米游社并没有验证码出现

**Comment by xingkuangye** [comment]
有可能只是米哈游认为你的这台电脑访问次数太多了，试试直接在电脑上看有没有验证码？
