### ISSUE TITLE
安装报错无法找到可用的 Python 解释器

### ISSUE THREAD

**Issue by touchscale** [CMHopeSunshine/LittlePaimon#480]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Windows11(example)
- Python版本: 3.10.8(example)
- Nonebot2版本: 2.0.0rc3(example)

### 问题描述

安装报错无法找到可用的 Python 解释器

### 问题截图

![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/107158734/19bc4bfa-08ce-4f96-8e67-7a42f37f1242)

**Comment by CMHopeSunshine** [comment]
python没添加到环境变量？

**Comment by touchscale** [comment]
> python没添加到环境变量？

添加了
![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/107158734/1da8ae0e-55fa-4ef2-a4d3-21a58c17c5e8)

**Comment by CMHopeSunshine** [comment]
运行python -V或者python3 -V看看正常不，如果正常但nbcli依旧这样提示的话，重装一下nb-cli试试

**Comment by touchscale** [comment]
> 运行python -V或者python3 -V看看正常不，如果正常但nbcli依旧这样提示的话，重装一下nb-cli试试

将环境变量删除，重新添加后，已经可以正常安装依赖
