### ISSUE TITLE
更新角色信息指令运行时报错

### ISSUE THREAD

**Issue by LGoLang** [CMHopeSunshine/LittlePaimon#49]
**如图**
![f84ea979c38d8ae3ac4bb8e6e2029bb](https://user-images.githubusercontent.com/101858522/173347445-82a81d0e-0887-4463-b53b-361823c8c875.jpg)
![image](https://user-images.githubusercontent.com/101858522/173347539-50cf441f-3232-4090-a84a-7ff444771fd9.png)

**Comment by CMHopeSunshine** [comment]
enka-api那边获取不到你某个角色的某个圣遗物词条信息导致的。
到enka看了一下，是这个uid的刻晴带的冒险家沙漏导致
