### ISSUE TITLE
[问题]bot.py启动报错:Failed to import "LittlePaimon" login页面无法访问，页面提示："detail":"Not Found"

### ISSUE THREAD

**Issue by AndroidDreaming** [CMHopeSunshine/LittlePaimon#498]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: Centos
- Python版本: 3.8.10
- Nonebot2版本: lastet

### 问题描述

更新派蒙之后，通过nb paimon run启动程序之后有以下报错：ERROR] nonebot | Failed to import "LittlePaimon"
同时访问:13579/login提示：
{"detail":"Not Found"}

### 问题截图
![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/19986242/812ecddf-a351-4b5f-a6c3-f74c95a1a8cd)

![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/19986242/83253710-471e-4cb1-b0e6-28705e6b66ce)

提供问题或日志截图...

### 复现步骤[可选]

1.通过管理员发出指令进行更新-更新成功
2.通过管理员发出指令提示重启-无响应
3.访问服务器发现账号登录存在问题，在删除缓存后仍无法成功启动决定重装paimon，使用覆盖式安装：删除文件夹下的内容重新安装
4.依赖安装无报错，安装完成后，通过命令nb paimon run启动机器人和gocqhttp，其中gocqhttp启动成功，而bot3则有上述截图报错

**Comment by CMHopeSunshine** [comment]
需要更详细的日志

**Comment by AndroidDreaming** [comment]
> 需要更详细的日志

十分抱歉没有更详细的日志了，原文中已经截图了所有的报错日志信息，剩下的日志是正常输出。


不过问题目前在全部删除之后再进行重装之后已经解决了。

具体步骤是rm -rf LittlePaimon整个文件夹之后利用脚手架完全重装

**Comment by CMHopeSunshine** [comment]
"正常输出"也要，我需要知道您加载了哪些插件导致冲突

**Comment by AndroidDreaming** [comment]
> "正常输出"也要，我需要知道您加载了哪些插件导致冲突

未能保留原始日志信息，目前通过完全重装解决了这个问题，现在找不到最初的日志和截图了，十分抱歉。
