### ISSUE TITLE
为什么在Q群里有时候机器人会艾特不到我自己，自己看不到消息，别人可以看的到

### ISSUE THREAD

**Issue by seedsrt** [CMHopeSunshine/LittlePaimon#5]
![image](https://user-images.githubusercontent.com/91008160/161885414-975e4dae-4485-4490-b344-ccede54b1e6c.png)
![QQ图片20220406104839](https://user-images.githubusercontent.com/91008160/161885998-d7bb5b78-7b3b-4b20-8d02-824e26cc81fe.png)

**Comment by CMHopeSunshine** [comment]
这应该是消息收发端的[go-cqhttp](https://github.com/Mrs4s/go-cqhttp/issues)的问题，可以去那边发issue

**Comment by CMHopeSunshine** [comment]
也不排除可能是网络原因，看看其他端qq有没有聊天记录

**Comment by seedsrt** [comment]
其他端qq倒是能看得到，就只有那个群是看不见机器人艾特我的信息





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CMHopeSunshine/LittlePaimon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月6日(星期三) 上午10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CMHopeSunshine/LittlePaimon] 为什么在Q群里有时候机器人会艾特不到我自己，自己看不到消息，别人可以看的到 (Issue #5)





 
也不排除可能是网络原因，看看其他端qq有没有聊天记录
