### ISSUE TITLE
[问题]获取4.4之后的角色攻略失败，前台消息为：闲云的角色攻略发送失败，可能是网络问题或者不存在该资源；后台提示image type error

### ISSUE THREAD

**Issue by AndroidDreaming** [CMHopeSunshine/LittlePaimon#503]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: centos7
- Python版本: 3.9.10
- Nonebot2版本: 3.0.8（通过派蒙脚手架安装，已经使用过nb paimon isntall 以及相关更新功能）

### 问题描述

在群里/私聊中，获取原神4.3之后的角色攻略失败，后台日志中提示：警告: 私聊 xxxx 图片上传失败: image type error: application/octet-stream
但是4.3之前的角色，获取角色攻略时没有异常提示，可以正常展示。其中4.3之后的武器图鉴，角色材料等信息展示也正常。

4.3之前的角色攻略正常：
![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/19986242/e9e7afb5-81c3-4080-9e3d-e4793649084b)

4.3之后的角色攻略异常：
![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/19986242/3606d851-c36b-4266-ad9b-b44c51928add)

![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/19986242/ae3518e8-0939-4119-be62-eedc313cf7fc)

4.3之后的材料图鉴正常：
![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/19986242/330e5001-74dc-49a8-b1f1-a6c6fd825e09)

4.3之后的角色图鉴正常：
![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/19986242/e04c0082-f9dc-419a-974e-1973204bc18f)

### 问题截图

![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/19986242/b48d2a91-4922-40ca-9a62-375103248702)

提供问题或日志截图...

### 复现步骤[可选]

4.3之前的角色攻略都可以正常发送，4.3之后的角色提示发送失败，包括角色攻略，角色参考面板，收益曲线
但是相关武器图鉴可以正常发送：
![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/19986242/577ad66b-1d0c-4413-aa45-0f03a9a71d9a)

**Comment by AndroidDreaming** [comment]
为什么木有人回答呀.....

**Comment by CMHopeSunshine** [comment]
还没更新相关资源

**Comment by AndroidDreaming** [comment]
> 还没更新相关资源

你好，最近4.4之前的角色也不无法获取角色攻略了，别的接口都正常。图鉴，材料之类的。
![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/19986242/9220e8b6-e4b4-4ced-acd2-2417eadbc3b1)
![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/19986242/6732b24a-3c11-4976-99d5-249337a04194)

**Comment by AndroidDreaming** [comment]
![image](https://github.com/CMHopeSunshine/LittlePaimon/assets/19986242/e0491a08-e508-48fb-aaca-fa51fda9b6d3)
好像是这个原因......

**Comment by AndroidDreaming** [comment]
最近尝试4.4角色攻略发现已经更新，故关闭此单
