### ISSUE TITLE
资源无法下载

### ISSUE THREAD

**Issue by wei-la-ya** [CMHopeSunshine/LittlePaimon#508]
### 确认

- 我的Bot版本已更新到最新，且已尝试使用`nb paimon install`更新依赖库
- 我已查阅[文档-常见问题](https://docs.paimon.cherishmoon.fun/question.html)，无相关解决方案
- 我已确认[issue](https://github.com/CMHopeSunshine/LittlePaimon/issues)中没有类似的问题或仍然得不到解决

### 环境信息

- 系统版本: debian12(example)
- Python版本: 3.11.2(example)

### 问题描述

用命令下载资源跟启动后下载资源都出错，github代理也改了。
并且使用nb paimon res命令下载资源，没有可用代理的选择

### 问题截图
![68a740b9438b9014e947772c2c0fcec2](https://github.com/CMHopeSunshine/LittlePaimon/assets/142399519/6c69853b-6795-453c-9fdf-69408c95d4ff)
![d0a32b3b6d216162b53c7ad56f338730](https://github.com/CMHopeSunshine/LittlePaimon/assets/142399519/9b6822f1-1840-4337-bdfe-41b8c37d76bb)
![c5d62e816232c7c11bfedc950bc0a691](https://github.com/CMHopeSunshine/LittlePaimon/assets/142399519/b51dc7b1-c667-41c6-8f0b-e46e82a9270c)

提供问题或日志截图...

### 复现步骤[可选]

描述问题复现过程...

**Comment by forchannot** [comment]
谁让你这么改资源下载地址的（

**Comment by forchannot** [comment]
改成`https://github代理/`，如`https://mirror.ghproxy.com/`,`https://github.moeyy.xyz/`,`https://github.cherishmoon.top/`

**Comment by wei-la-ya** [comment]
> 改成`https://github代理/`，如`https://mirror.ghproxy.com/`,`https://github.moeyy.xyz/`,`https://github.cherishmoon.top/`

我用webui改的，webui上的选择就是域名啊

**Comment by forchannot** [comment]
https://github.com/CMHopeSunshine/LittlePaimon/blob/512707d58bfba3313aff615a098ffd4fbe97bbfb/LittlePaimon/web/pages/config_manage.py#L368-L393
webui里也是链接啊，而且webui现在都没有mirror的，你哪里改出来的

**Comment by wei-la-ya** [comment]
> https://mirror.ghproxy.com/

理解错了，我看web上显示的就是域名，就只填了域名，抱歉

**Comment by wei-la-ya** [comment]
> 改成，如,,`https://github代理/``https://mirror.ghproxy.com/``https://github.moeyy.xyz/``https://github.cherishmoon.top/`

修改代理成功后，资源下载依旧错误
![a3faac12f6c075f630ff320939b7e74f](https://github.com/CMHopeSunshine/LittlePaimon/assets/142399519/0fac36c1-e7f6-43b3-95f2-b3d0a0311943)
![c5addd141a66cf5201ac94266d5f61ae](https://github.com/CMHopeSunshine/LittlePaimon/assets/142399519/cc44ae66-df1c-43fd-bd74-41f219c53aa8)

**Comment by forchannot** [comment]
多试几个就行了
