### ISSUE TITLE
好像plugins中的init.py哪怕都注释掉了插件也会启动

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#51]
![image](https://user-images.githubusercontent.com/100580891/173395408-e4354269-8934-42c5-b116-394f2be974dc.png)
![image](https://user-images.githubusercontent.com/100580891/173395574-2fd921d7-3dbc-4977-bbec-37f14b9f96ac.png)
![image](https://user-images.githubusercontent.com/100580891/173395597-e0eb98e8-d973-42c7-a826-5cbf25dd78ff.png)

**Comment by CMHopeSunshine** [comment]
现在使用load_plugins的方式了，不想加载的插件，在对应的py文件名最前面加个_，或者直接删掉文件就行

**Comment by forchannot** [comment]
> 现在使用load_plugins的方式了，不想加载的插件，在对应的py文件名最前面加个_，或者直接删掉文件就行

这样啊，好的
