### ISSUE TITLE
[建议]兼容NoneBot Adapter QQ（官方机器人）

### ISSUE THREAD

**Issue by mumingluan** [CMHopeSunshine/LittlePaimon#512]
### 当前不足

仅能通过OneBot协议的适配器使用小派蒙（包括但不限于go-cqhttp和一众基于NTQQ的适配器均可使用），无法通过NoneBot官方插件nonebot-adapter-qq对接腾讯开放平台官方机器人（频道和群均无响应）

### 建议内容

支持跨平台应用（这也是nonebot2的优点），如腾讯QQ官方机器人/telegram机器人/discord机器人/kook机器人等。

### 参考示例

[TRSS-Yunzai](https://github.com/TimeStarRainSky/Yunzai)
[Koishi](https://koishi.chat)

**Comment by mumingluan** [comment]
> ### 当前不足
> 仅能通过OneBot协议的适配器使用小派蒙（包括但不限于go-cqhttp和一众基于NTQQ的适配器均可使用），无法通过NoneBot官方插件nonebot-adapter-qq对接腾讯开放平台官方机器人（频道和群均无响应）
> 
> ### 建议内容
> 支持跨平台应用（这也是nonebot2的优点），如腾讯QQ官方机器人/telegram机器人/discord机器人/kook机器人等。
> 
> ### 参考示例
> [TRSS-Yunzai](https://github.com/TimeRainStarSky/Yunzai) 
[Koishi](https://koishi.chat)

**Comment by nicklly** [comment]
可以支持，但没必要，作者学业繁忙，已无更多精力兼顾小派蒙的开发

**Comment by mumingluan** [comment]
已经寻找到替代解决方案。使用Gensokyo中间件，可以将QQBot API转接为OneBotv11，正常接入小派蒙使用。
