### ISSUE TITLE
启动成功了，但是没有任何反应

### ISSUE THREAD

**Issue by titanlpy** [CMHopeSunshine/LittlePaimon#53]
![Z`R}U{17ES1N374(GC$149N](https://user-images.githubusercontent.com/20349929/173755785-5043451d-2469-4a3b-a468-0d37bc6557d5.png)

**Comment by titanlpy** [comment]
然后开启auto_handle模块的时候会报错，跟这个有关系吗？
![image](https://user-images.githubusercontent.com/20349929/173760678-40de0725-945b-497a-80c2-e4b481255f84.png)

**Comment by CMHopeSunshine** [comment]
截报错信息最后一句看看

**Comment by titanlpy** [comment]
![image](https://user-images.githubusercontent.com/20349929/173761102-aef23cd7-8092-4fa6-ab3b-41c9ea25f63b.png)

**Comment by CMHopeSunshine** [comment]
没有在`.env.prod`文件中配置超级管理员账号，配置了再重启试试

**Comment by titanlpy** [comment]
谢谢大佬，脑子抽了。。。模式换成prod后，环境配置忘记一起改了
