### ISSUE TITLE
云原神代码内类型注解的bug

### ISSUE THREAD

**Issue by meatjam** [CMHopeSunshine/LittlePaimon#57]
我无法使用云原神功能，无论是发送“云原神 绑定 XXX”或“云原神 解绑” 均报如下错误：
![image](https://user-images.githubusercontent.com/43535074/174073951-351b75a2-321a-4477-9ede-15ef3577744c.png)
经初步排查，发现是因LittlePaimon/Paimon_CloudGenshin/__init__.py中消息处理回调函数的参数类型注解，Union中的两个父子类被错误的当作类与实例导致的。
![image](https://user-images.githubusercontent.com/43535074/174074411-adea9e9b-c29a-439c-8ec3-0ef7f00d3eee.png)
假如将上述event的类型注解固定为一种，如`event: GroupMessageEvent`则可正常运行。

不知道这种情况是为什么会出现呢？

**Comment by nicklly** [comment]
经测试 功能正常 请检查你的nonebot以及python版本

![34X{87SP3AL@ 1 WZFCR 28](https://user-images.githubusercontent.com/17716585/174077859-ec6b7173-45ab-49a8-a9d0-4d0e3cf39781.png)
![)ERIGSKVSFI6@@N5%_$8665](https://user-images.githubusercontent.com/17716585/174078044-282c00e4-69ed-4c8b-819d-dc712baf0e79.png)

**Comment by meatjam** [comment]
> 经测试 功能正常 请检查你的nonebot以及python版本
> 
> ![34X{87SP3AL@ 1 WZFCR 28](https://user-images.githubusercontent.com/17716585/174077859-ec6b7173-45ab-49a8-a9d0-4d0e3cf39781.png) ![)ERIGSKVSFI6@@N5%_$8665](https://user-images.githubusercontent.com/17716585/174078044-282c00e4-69ed-4c8b-819d-dc712baf0e79.png)


我的python版本为3.8.10，nonebot cli版本为 0.6.7，nonebot版本为2.0.0b3。

**Comment by CMHopeSunshine** [comment]
这是nonebot2 beta3的一个bug，nonebot2那边已经在master分支修复，但未发布到pypi，详见[#998](https://github.com/nonebot/nonebot2/issues/998)

**Comment by meatjam** [comment]
> 这是nonebot2 beta3的一个bug，nonebot2那边已经在master分支修复，但未发布到pypi，详见[#998](https://github.com/nonebot/nonebot2/issues/998)

好的，感谢指路
