### ISSUE TITLE
【建议】nonebot加载插件机制导致重复加载

### ISSUE THREAD

**Issue by meatjam** [CMHopeSunshine/LittlePaimon#58]
运行时包含"Paimon_CloudGenshin"在内的多个功能加载失败：
![image](https://user-images.githubusercontent.com/43535074/174076140-f5191624-6e39-4c35-bb90-a4b879da5361.png)
![image](https://user-images.githubusercontent.com/43535074/174076067-5d417c65-9c96-4db7-9896-4f2997ad16d5.png)
![image](https://user-images.githubusercontent.com/43535074/174076227-c773dbe3-f12b-4681-af05-3981d5c4ee2b.png)

经调试排查发现，当运行根目录下的boy.py中的`nonebot.load_plugins("LittlePaimon")`时，nonebot会自动加载所有该目录下的包作为插件，但像utils这类的工具类包不应被当做插件加载。

根据nonebot的load_plugins函数的注释说明（\venv\Lib\site-packages\nonebot\plugin\load.py），建议重构"utils"包名为"_utils"以排除其作为插件，也可更好的在目录中区分包的功能性。
![image](https://user-images.githubusercontent.com/43535074/174077349-c31d25ff-8dbc-49b1-9e2e-ed8420ce7e72.png)

**Comment by meatjam** [comment]
经测试，按上述操作全局重命名包名后，即可正常地导入所有包作为插件。

**Comment by CMHopeSunshine** [comment]
`utils`和`user_data`文件夹中并没有`__init__.py`文件，它不会被自动识别为python软件包，load_plugins时是不会当成插件加载的，我这实际运行时也不会加载他们，可能是您做了一些操作让它被识别为软件包？

**Comment by meatjam** [comment]
> `utils`和`user_data`文件夹中并没有`__init__.py`文件，它不会被自动识别为python软件包，load_plugins时是不会当成插件加载的，我这实际运行时也不会加载他们，可能是您做了一些操作让它被识别为软件包？

utils的`__init__.py`确实不应该是仓库版本文件。。。可能是之前融合master分支时遗留下的，我再检查一下。
