### ISSUE TITLE
填写公共ck和私人ck后依然无法查询

### ISSUE THREAD

**Issue by ASOUL-D1ana** [CMHopeSunshine/LittlePaimon#63]
![Screenshot_20220620_134618_com tencent mobileqq_edit_384246515562687](https://user-images.githubusercontent.com/90080442/174533492-61c23072-0d06-4fe6-b2fd-750f4ab39581.jpg)
![Screenshot_20220620_134713](https://user-images.githubusercontent.com/90080442/174533503-69e481ba-30b8-4a5d-8d91-009cf0bab43c.jpg)

**Comment by CMHopeSunshine** [comment]
请确认米游社账号是否实际可用（没有在封号中、能查询别人游戏战绩），是否在获取完cookie之后就退出了米游社账号，退出账号会导致cookie马上失效。建议在无痕模式下获取cookie，获取完后不要点退出，直接关闭浏览器。

**Comment by ASOUL-D1ana** [comment]
用无痕模式获取之后成功了 谢谢！
