### ISSUE TITLE
更换登录设备

### ISSUE THREAD

**Issue by MueoMo** [CMHopeSunshine/LittlePaimon#64]
device.json文件好像可以自定义登录设备？
但我没能找到相关文档，现在只能提供手表登陆吗

**Comment by CMHopeSunshine** [comment]
请查阅[gocq官方文档](https://docs.go-cqhttp.org/)

**Comment by MueoMo** [comment]
对，我刚去看了。然后我把登录改为安卓手机了
![image](https://user-images.githubusercontent.com/97434905/174618309-a81f7605-5fa8-4999-a4d5-98b2ca04a324.png)
然后验证时依旧显示设备为手表

**Comment by CMHopeSunshine** [comment]
相关问题去[gocq仓库](https://github.com/Mrs4s/go-cqhttp)交流吧
