### ISSUE TITLE
升级最新版后那个新的插件无法import

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#69]
报错太长了，我全部复制放在网络剪切板了https://netcut.cn/p/0ba9bf175b279714    ，密码little。
好像我知道啥原因了，因为另一个插件也用到了这个htmlrender，冲突了，不过怎么解决呢

**Comment by CMHopeSunshine** [comment]
不存在用了同一个插件而冲突的情况吧...我这也有很多其他用htmlrender的插件，没冲突问题

**Comment by forchannot** [comment]
> 不存在用了同一个插件而冲突的情况吧...我这也有很多其他用htmlrender的插件，没冲突问题

好像是因为那个插件是用的nb安装的，派蒙是直接添加在botpy里面启动优先级高，那个插件启动时发现htmlrender已经被启动了，具体大佬可以看看剪切板是因为啥

**Comment by CMHopeSunshine** [comment]
那你调一下顺序试试咯，我的是先加载nb plugin的再加载LittlePaimon，报错日志没有什么用

**Comment by CMHopeSunshine** [comment]
找到问题了，是没有进行require操作。目前先加载其他需要htmlrender的插件的话就能正常运行。明天修复
