### ISSUE TITLE
大佬大佬，派蒙聊天好像有点问题。

### ISSUE THREAD

**Issue by bilili-syy** [CMHopeSunshine/LittlePaimon#70]
MDB已经配置完毕。功能目前100%响应的只有说怪话和不准说怪话。发癫偶尔响应一次。派蒙学习和变笨则是一点反应没有。都是用超级管理员发送的相关指令。是我的哪里指令不对吗？都是@机器人之后跟指令的。

**Comment by SCUOP** [comment]
说怪话表示机器人在该群进行机器学习，但是如果没有在该群打开机器学习功能，则没有任何反应，先打开机器学习再试其他指令。至于另外两条指令无法用可能是因为bot名字叫派蒙，会自动屏蔽派蒙作为@机器人，可以试试 降低学习能力 和 加强学习能力两条指令。先加入机器学习群组指令才会生效。（也有可能是和其他插件的优先级冲突了导致发不出文字，影响不大）
