### ISSUE TITLE
Paimon_Chat无法正常工作

### ISSUE THREAD

**Issue by RoundedOrange** [CMHopeSunshine/LittlePaimon#71]
MongoDB已经配置好，.env.prod文件也加入了url```paimon_mongodb_url=mongodb://localhost:27017/```，群内发送@派蒙<命令>也能做出回应，但是bot不主动说话，@派蒙 也不做出回应。请问是怎么回事呢。

**Comment by CMHopeSunshine** [comment]
可以打开mongodb看一下有没有paimonchat数据库，有且有消息存入才算成功。派蒙发言需要一定的学习时间，取决于你群消息数量和群员聊天习惯，一般都要几天

**Comment by RoundedOrange** [comment]
我查看了mongodb的数据库，mongo执行```show dbs```后有PaimonChat数据库，但是后边显示0.000G。
另外，我又看了下这个数据库的信息
```
> db
PaimonChat
> db.stats()
{
        "db" : "PaimonChat",
        "collections" : 3,
        "views" : 0,
        "objects" : 122,
        "avgObjSize" : 213.672131147541,
        "dataSize" : 26068,
        "storageSize" : 86016,
        "indexes" : 9,
        "indexSize" : 266240,
        "totalSize" : 352256,
        "scaleFactor" : 1,
        "fsUsedSize" : 262660620288,
        "fsTotalSize" : 368642617344,
        "ok" : 1
}
```
发现好像有存数据，是不是数据不够导致bot不说话的？

**Comment by CMHopeSunshine** [comment]
是的，简单来说Paimon_Chat就是个高级复读机或者叫问答bot，你可以连续发送3次同一组对话来让它强行学会，比如
```
诶嘿
诶嘿是什么意思啊
诶嘿
诶嘿是什么意思啊
诶嘿
诶嘿是什么意思啊
```
之后你再发`诶嘿`，它就会回复`诶嘿是什么意思啊`

**Comment by RoundedOrange** [comment]
请问是发送```欸嘿```然后再发送```欸嘿是什么意思啊 ```重复三次吗？要@派蒙吗

**Comment by CMHopeSunshine** [comment]
是的，不需要艾特。另外，该功能仅限群聊

**Comment by RoundedOrange** [comment]
成功了，谢谢。
