### ISSUE TITLE
好像运行不了？是哪里有问题呢？

### ISSUE THREAD

**Issue by FBIOpentheDoor26** [CMHopeSunshine/LittlePaimon#72]
之前一直都能用，重装系统之后按之前的方法配置，就运行不了。是哪里有问题呢？谢谢
[log.txt](https://github.com/CMHopeSunshine/LittlePaimon/files/8958367/log.txt)

**Comment by CMHopeSunshine** [comment]
更新beta4 ~~都不看更新日志是吗~~

**Comment by FBIOpentheDoor26** [comment]
嘿嘿嘿嘿嘿嘿嘿嘿嘿嘿嘿嘿嘿嘿嘿

**Comment by FBIOpentheDoor26** [comment]
能用了 3Q
