### ISSUE TITLE
大佬大佬，原神日历成功输出，但是不显示所有中文，请问如何处理

### ISSUE THREAD

**Issue by mawMOBai** [CMHopeSunshine/LittlePaimon#75]
原神日历成功相应，所有中文均为框框，查阅之前文档也没有相关问题，请问如何处理。
![VeryCapture_20220623195205](https://user-images.githubusercontent.com/87401346/175292390-0b110f53-e02e-42bc-a023-a33575214cda.jpg)
![QQ图片20220623195212](https://user-images.githubusercontent.com/87401346/175292395-d10e3444-2200-406f-9c7e-c3b48dba8629.png)

**Comment by linword** [comment]
缺失中文字体库的原因。具体的看你啥系统，然后对症去解决。

**Comment by nicklly** [comment]
缺少中文字体库 安装字体即可

**Comment by mawMOBai** [comment]
感谢大佬，成功了！
