### ISSUE TITLE
获取抽卡记录问题

### ISSUE THREAD

**Issue by TimeRainStarSky** [CMHopeSunshine/LittlePaimon#81]
无法成功获取抽卡记录，查看user_gacha_log.json发现每个&后面多了`amp;`，删除就能成功获取
![Screenshot_20220628-061903_ZeroTermux](https://user-images.githubusercontent.com/63490117/176048260-c2789f95-8e5e-4727-bb36-e461e9da81dc.png)

**Comment by CMHopeSunshine** [comment]
我在代码中将`amp;`去掉了，看看还有没有问题
