### ISSUE TITLE
大佬大佬，可否分享一下你的说怪话语料库呢

### ISSUE THREAD

**Issue by FunnelCakes** [CMHopeSunshine/LittlePaimon#83]
从头训练起来好难啊。。来个大库砸死我吧QAQ

**Comment by linword** [comment]
派蒙聊天的那个如果群聊很活跃的话，基本两三天mongodb的数据库数据就有很多了

**Comment by FunnelCakes** [comment]
关键我那群没那么多水b啊😂😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月28日(周二) 下午5:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CMHopeSunshine/LittlePaimon] 大佬大佬，可否分享一下你的说怪话语料库呢 (Issue #83)




 
派蒙聊天的那个如果群聊很活跃的话，基本两三天mongodb的数据库数据就有很多了

**Comment by linword** [comment]
emmm，给你试试看吧，我用的是mongodb官方的MongoDB Compass，导出的文件是json格式。如果要csv的话我再导出吧。
[https://www.123pan.com/s/k9ZDVv-mnArv](url)
提取码：paim

**Comment by FunnelCakes** [comment]
成了，感谢大哥~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CMHopeSunshine/LittlePaimon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月29日(星期三) 中午11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CMHopeSunshine/LittlePaimon] 大佬大佬，可否分享一下你的说怪话语料库呢 (Issue #83)





 
emmm，给你试试看吧，我用的是mongodb官方的MongoDB Compass，导出的文件是json格式。如果要csv的话我再导出吧。
 https://www.123pan.com/s/k9ZDVv-mnArv
 提取码：paim
