### ISSUE TITLE
通过博客中的教程部署时，安装依赖失败

### ISSUE THREAD

**Issue by victor-lcr** [CMHopeSunshine/LittlePaimon#84]
系统：Ubuntu Server
错误如下：
![image](https://user-images.githubusercontent.com/69039383/176206449-c3ddf955-de2e-48e1-953d-b4575152f1ea.png)

**Comment by CMHopeSunshine** [comment]
似乎是poetry的问题，尝试一下手动安装出错的包吧，这里是安zipp时出错了，`pip install zipp`

**Comment by victor-lcr** [comment]
我是按照手动部署的方式安装的，在运行
pip install -r requirements.txt
的时候出现错误

**Comment by CMHopeSunshine** [comment]
因为我是用`poetry export`生成的`requirements.txt`，搜索了相关问题说是poetry导出的bug
