### ISSUE TITLE
BUG反馈。原神猜语音

### ISSUE THREAD

**Issue by bilili-syy** [CMHopeSunshine/LittlePaimon#85]
貌似只要是主人发的。不管什么内容都算对
![3)PQN{EIXUTBYDI%2AC1@0S](https://user-images.githubusercontent.com/61721162/176356217-01d762ff-880f-46aa-bc76-004e2079f0ba.png)

**Comment by CMHopeSunshine** [comment]
今早已经修了，更新后再看看还有没有这个问题

**Comment by bilili-syy** [comment]
好的。。请问大佬。后续有考虑做在线更新那种吗？

**Comment by CMHopeSunshine** [comment]
目前已经是在线更新，语音来源是B站WIKI或米游社，那边更新了之后，发指令`更新原神语音资源`就会自动爬取下载

**Comment by bilili-syy** [comment]
好的大佬.那后续是能否通过QQ发送一个:更新派蒙,就能将派蒙整个更新呢。。

**Comment by CMHopeSunshine** [comment]
目前还没想到好的方案，打算先把原神功能做好点再考虑这些

**Comment by bilili-syy** [comment]
感谢大佬的付出
