### ISSUE TITLE
这个只是单纯的没抢到吗

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#86]
![image](https://user-images.githubusercontent.com/100580891/176421430-188d5210-5b7e-46b5-82ad-bce6e4b13f92.png)
命令台没有输出

**Comment by CMHopeSunshine** [comment]
是的，那有反脚本机制，所以最好还是不要同一个时间抢多个东西 ~~经验书、摩拉这些其实没什么人换，手动换就行了~~

**Comment by forchannot** [comment]
> 是的，那有反脚本机制，所以最好还是不要同一个时间抢多个东西 ~经验书、摩拉这些其实没什么人换，手动换就行了~

这个设置一次是只抢一次还是会每次都抢

**Comment by CMHopeSunshine** [comment]
只抢一次
