### ISSUE TITLE
能否将Learning_repeate单独拿出作为一个模块

### ISSUE THREAD

**Issue by rainyorange** [CMHopeSunshine/LittlePaimon#87]
这个学习模块确实相对于wordbank来说更适合一些懒鬼（比如我）使用
所以问一下作者能不能将其单独取出作为一个模块使用
（）
如果能投到nb2仓库就更好了

**Comment by CMHopeSunshine** [comment]
我并不是这个功能的原作者，机器学习的核心代码来自[牛牛](https://github.com/InvoluteHell/Pallas-Bot)
