### ISSUE TITLE
原神日程乱码问题

### ISSUE THREAD

**Issue by Admsec** [CMHopeSunshine/LittlePaimon#88]
环境是Centos 7.3，python3.9

![BS7R8}8 N9$6V5@$1{VY~WA](https://user-images.githubusercontent.com/86643414/176803849-b5f5a850-c1f4-459b-8142-f84ab72159b9.PNG)

**Comment by linword** [comment]
你的centos没装中文字体库的原因，具体百度一下。装了中文字体库就可以显示正常了。

**Comment by Admsec** [comment]
谢谢，问题解决了
