### ISSUE TITLE
nb run执行后报错

### ISSUE THREAD

**Issue by MueoMo** [CMHopeSunshine/LittlePaimon#90]
nb run执行后报错
![image](https://user-images.githubusercontent.com/97434905/177046518-c3203408-ffe4-4151-a447-8fc66e08d475.png)

**Comment by MueoMo** [comment]
我yum去安装提示缺少的三个依赖。发现已经安装了

**Comment by CMHopeSunshine** [comment]
`nonebot-plugin-htmlrender`的问题见[其仓库](https://github.com/kexue-z/nonebot-plugin-htmlrender)的常见疑难杂症

**Comment by MueoMo** [comment]
好的。问题已解决
机器人发送帮助菜单会报错
![image](https://user-images.githubusercontent.com/97434905/177050181-623d8f24-1b13-467e-ad77-d1c0b991ae68.png)
