### ISSUE TITLE
是我的错觉嘛，这次重构后机器人的平均回复时长比原来长了

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#91]
就感觉以前几秒钟能回复的现在要10s多有的甚至20s

**Comment by linword** [comment]
我的目前测试下来没有遇见你说的这个问题，可能其他占内存太高了？

**Comment by forchannot** [comment]
> 我的目前测试下来没有遇见你说的这个问题，可能其他占内存太高了？

没开其他的呀，我的服务器就只搭建了个机器人其他啥也没干

**Comment by CMHopeSunshine** [comment]
没有涉及性能的更新啊，没理由说慢那么多，也许是资源删了导致每次命令重下？每一个武器、圣遗物、天赋等图标要0.3秒左右下载
