### ISSUE TITLE
有人在腾讯轻量云centos7.6系统下部署成功过吗？

### ISSUE THREAD

**Issue by Ann-Charles** [CMHopeSunshine/LittlePaimon#92]
部署的时候提示缺少依赖Missing libraries:  libatk-bridge-2.0.so.0，libxkbcommon.so.0，libatspi.so.0  安装这三项之后再次运行还是提示缺少

**Comment by linword** [comment]
以缺少`libatspi.so.0`为例。
## 1.检索文件是否存在
```
//查看libcups.so.2文件是否存在
find / -name libatspi.so.0
//存在的话，添加libatspi.so.0的目录进系统共享库
export LD_LIBRARY_PATH=/path/to/libatspi.so.0:$LD_LIBRARY_PATH
```
## 2.检索`libatspi.so.0` 需要的依赖
```
yum provides libatspi.so.0
```
![image](https://user-images.githubusercontent.com/43131361/177069286-fe562bf9-3118-4e21-8388-04106c965fb5.png)
可以看到需要的依赖是`at-spi2-core-2.28.0-1.el7.i686`
## 3.安装缺少的依赖
```
yum install -y at-spi2-core
```
安装完成后，看看是否还会提示缺少。缺少的其他文件，都可按这个方法处理和解决，我是直接按2，3步骤来的。
