### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by forchannot** [CMHopeSunshine/LittlePaimon#93]
在首次git clone时增加使用depth命令，即git clone --depth=1 https://github.com/CMHopeSunshine/LittlePaimon.git  ，因为前面太多大文件的commit，会导致如果不使用depth命令会把很多commit给他clone下来，会特别慢而且很大概率会不成功，用depth命令就只会clone每个文件最后一次commit，大大缩小了大小，使用后只会clone3M多（多出来的都是..git\objects文件夹存的以前的commit，理论上对于大多数用户不需要）。
因为用这个的都是普通用户，并不需要使用git管理工具回到某一版本（大概），所以建议将默认clone模式增加depth命令，有需要的可以不用depth

**Comment by CMHopeSunshine** [comment]
感谢建议

**Comment by forchannot** [comment]
> 感谢建议

因为正好nonebot分支是主分支，这个命令只能clone主分支，不然的话还挺麻烦的，hoshinobot那边的分支就麻烦了（不过好像也没维护了）

**Comment by forchannot** [comment]
> > 感谢建议
> 
> 因为正好nonebot分支是主分支，这个命令只能clone主分支，不然的话还挺麻烦的，hoshinobot那边的分支就麻烦了（不过好像也没维护了）

好像也可以，使用git clone --depth=1 --branch master https://github.com/CMHopeSunshine/LittlePaimon.git     就可以clone下来hoshinobot分支最新的一次commit了
