### ISSUE TITLE
提个bug

### ISSUE THREAD

**Issue by wangyousama** [CMHopeSunshine/LittlePaimon#94]
用ysb绑定私人ck后，再用ys+uid查别人，就会绑定qq到这个uid上，其他功能查询的默认对象就变成这个uid，是我自己的问题还是bug？

**Comment by CMHopeSunshine** [comment]
本来就是这么设计的，记录上一次查询的uid

**Comment by wangyousama** [comment]
> 本来就是这么设计的，记录上一次查询的uid

行吧
