### ISSUE TITLE
求助，启动报错

### ISSUE THREAD

**Issue by DragCCCC** [CMHopeSunshine/LittlePaimon#96]
更新以后所有模块无法加载，提示如下
![LD9FJ@%HBMX7 0I~SH`%B0F](https://user-images.githubusercontent.com/95351456/177599368-bf10ccc4-16c7-4dfa-8f06-e1bd65cd3274.png)

这是我弄丢了什么么？…………感谢大佬

**Comment by DragCCCC** [comment]
重新安装了依赖，报错变了……
![)HLRMZ{ L6HJZ4YB L7RUGP](https://user-images.githubusercontent.com/95351456/177600742-a079f081-2d08-4d85-8590-14e164f61ed6.png)

**Comment by CMHopeSunshine** [comment]
图一`pip install littlepaimon_utils`，图二你误删了几个字，`_json`前面还有`load`，也就是`load_json`

**Comment by DragCCCC** [comment]
非常感谢
