### ISSUE TITLE
能否自定义派蒙昵称

### ISSUE THREAD

**Issue by Noctulus** [CMHopeSunshine/LittlePaimon#97]
rt，如果给群聊机器人起了别的昵称以后小派蒙插件依然用派蒙自称就很奇怪（
![16e7c56aa03310ae](https://user-images.githubusercontent.com/39023047/177672648-9e1a8ed2-3c5f-42f8-8369-14b1bc05022e.png)

**Comment by CMHopeSunshine** [comment]
emm，列入计划中
